### ISSUE TITLE
Sentry chart v3.0.0: HPA for worker and web are the same name

### ISSUE THREAD

**Issue by andrsp** [sentry-kubernetes/charts#101]
https://github.com/sentry-kubernetes/charts/blob/3.0.0/sentry/templates/hpa-web.yaml#L5
https://github.com/sentry-kubernetes/charts/blob/3.0.0/sentry/templates/hpa-worker.yaml#L5

they both use `name: {{ template "sentry.fullname" . }}`, it's better to add postfixes like `-web` and `-worker` to be able to enable both

**Comment by Mokto** [comment]
Should be fixed in 3.0.1.
