### ISSUE TITLE
How to cleanup data stored in Zookeeper-Clickhouse PVC

### ISSUE THREAD

**Issue by iRakic** [sentry-kubernetes/charts#1010]
Hello everyone,

For some reason, data stored in data-sentry-zookeeper-clickhouse-0 and other PVCs like this are getting high usage.
I have run ```
cleanup --concurrency 1 --days 30```, but it didn't delete the data from PVC.
Is there an automated way to clean it up, or maybe some manual way?

App version 23.6.1
Chart version: sentry-19.4.0

Thank you in advance!

**Comment by ohjongsung** [comment]
Hello
manual way like this:
```
cd /opt/bitnami/zookeeper/bin
./zkCleanup.sh -n 10
```
or

Add this env to deployment yaml
```
        - name: ZOO_AUTOPURGE_INTERVAL
          value: "1"
        - name: ZOO_AUTOPURGE_RETAIN_COUNT
          value: "3"
```

**Comment by iRakic** [comment]
@ohjongsung Thank you a lot! It works.
