### ISSUE TITLE
[Request] Move root system to sentry path in values file.

### ISSUE THREAD

**Issue by DandyDeveloper** [sentry-kubernetes/charts#105]
I can't see a good reason why this is in it's own root path in the values yaml. 

It's only referenced in the Sentry configmap.

https://github.com/sentry-kubernetes/charts/blob/264aa1db489288f4471306f77d4bd3f23a9176b0/sentry/values.yaml#L147

**Comment by DandyDeveloper** [comment]
Same can be said for mail: https://github.com/sentry-kubernetes/charts/blob/264aa1db489288f4471306f77d4bd3f23a9176b0/sentry/values.yaml#L153

**Comment by DandyDeveloper** [comment]
Ah I could be wrong here... It looks like root references a lot of Sentry specific stuff... but we also have `sentry.xyz` params which I think we'd be better off moving to root...

**Comment by Mokto** [comment]
In my opinion `sentry.xyz` is more for Kubernetes settings. And the other are for direct sentry settings.

**Comment by DandyDeveloper** [comment]
@Mokto Yeah, I just wonder if its confusing for someone to see them in the file but I'm having a hard time convincing myself this is a problem to be honest haha.

**Comment by Mokto** [comment]
What should we do with this @DandyDeveloper ? I also don't want to include too many breaking changes from the previous charts (yet).

**Comment by DandyDeveloper** [comment]
@Mokto Great question, I think its fine how it is. I don't think there's a strong enough argument for these changes. Closing.
