### ISSUE TITLE
Upgrade rabbitmq-ha helm chart

### ISSUE THREAD

**Issue by joscha-alisch** [sentry-kubernetes/charts#107]
Hi there, the sentry chart is currently depending on the rabbitmq-ha chart in version 1.38.2. 

With version 1.39.0 they added the option to specify `affinity` on the statefulset, which would be a nice to have. 
Since this is the only change in this version (https://github.com/helm/charts/commit/ca058a2194b36862ce14ce7e81a387e51d098473#diff-506629ccdea7dd5052345d0c0b8a7323), I think it should be safe to update to that version at least?

Thanks!

**Comment by Mokto** [comment]
Sure, we can do it 👍 

PR welcomed.
