### ISSUE TITLE
sentry-web should be statefulset 

### ISSUE THREAD

**Issue by jefimm** [sentry-kubernetes/charts#1091]
sentry-web should be statefulset  because of persistent storage
it does not work well with restarts - new pods cannot mount the volume

**Comment by paco-sisutech** [comment]
Yes, every time I try to redeploy it just fails since the pod is still attached to the persistence volume

**Comment by pavels** [comment]
Only with filesystem backend - with object store (like S3) backend, there is no PV needed

**Comment by Mokto** [comment]
Using an object store is recommended.
