### ISSUE TITLE
"Crash Free Session Rate" alert type not being displayed

### ISSUE THREAD

**Issue by lucas-cantelli** [sentry-kubernetes/charts#1104]
Hey,

I have Sentry on-prem running v23.8.0, but I can't see the "Crash Free Session Rate" alert type:

**Expected Result**:

![image](https://github.com/sentry-kubernetes/charts/assets/106745957/4b868125-66d0-4892-9cd1-76f1e4191322)

**Current Result:**

<img width="1275" alt="image" src="https://github.com/sentry-kubernetes/charts/assets/106745957/e7dfaa7e-2c18-497c-9f4b-78674bcd6694">

I see the same option available in the sandbox environment (v23.5.1) under the same project type (Android).

Am I missing something?

**Comment by kzonov** [comment]
@lucas-cantelli there is a feature flag `organizations:crash-rate-alerts` that you can enable to get this result.
One option to do so would be setting it like this in your Helm chart:
```
config:
            sentryConfPy: |
              SENTRY_FEATURES.update({"organizations:crash-rate-alerts": True})
```

Nevertheless I think it would be nice to have a possibility to pass arbitrary feature flags in the helm chart without a need of using the `sentryConfPy`.
I believe this issue can be closed.

**Comment by lucas-cantelli** [comment]
Perfect! Closing this.
