### ISSUE TITLE
some Sentry internal cron monitors failing since upgrading to Sentry 23.8.0

### ISSUE THREAD

**Issue by reneeckstein** [sentry-kubernetes/charts#1107]
Hi, 

we run 2 different Sentry environments and both have the same issue:
Some of the default cron monitors in the internal project fails since we upgraded to Sentry 23.8.0 (helm chart v20.5.3) on Sep 5, 2023.

affected cron monitors:
- flush-buffers
- sync-options
- schedule-digests
- check-monitors
- dynamic-sampling-prioritize-transactions
- dynamic-sampling-sliding-window
- dynamic-sampling-prioritize-projects
- schedule_auto_archive_issues
- schedule_auto_transition_new
- schedule_auto_transition_regressed

some of them run every minute so we have quite a lot of events for "missed_checkin" from these cron monitors.

My question is: Were these cron monitors removed or replaced in Sentry 23.8.0? Maybe a post-install hook had failed?
Does anyone have the same issue?

I honestly don't know where to start troubleshooting here, because other cron monitors run fine, some are also running every minute like `monitors-clock-pulse` so it doesn't seem to be a general issue. As far as I see the sentry-workers are responsible for executing the cron monitor jobs.

Since Oct 22, 2023, another cron monitor is failing: `hybrid-cloud-repair-mappings`
on this day we upgraded Sentry to 23.10.1 (helm chart v20.8.0)

With "failing" I mean every Check-in is in "missed" state (yellow) and the Last Check-In on the Cron Monitor details page has not been updated since the mentioned upgrades.

we currently running Sentry 23.11.2 (helm chart v20.12.2) but started in March 2021 with Sentry v21.3.0 (helm chart 10.1.0) so it could be an upgrade issue.

**Comment by zacharyarnaise** [comment]
Hi,

We had the same issue and I can confirm that these alerts come from CRONs that were removed in newer versions of Sentry. We ended up removing them manually.
You can check in Sentry source code which monitors are expected to be there: https://github.com/getsentry/sentry/blob/88c7f2d98d379e68d27adfaf5c9b815a4d54cb89/src/sentry/conf/server.py#L953

Somehow the monitors aren't removed when upgrading. This other comment confirms it: https://github.com/sentry-kubernetes/charts/issues/973#issuecomment-1722981818

**Comment by reneeckstein** [comment]
Hi @zacharyarnaise, thanks for sharing 👍. We removed them manually now.
