### ISSUE TITLE
Can not upgrade to 21.1.0

### ISSUE THREAD

**Issue by mosesdd** [sentry-kubernetes/charts#1135]
Upgrade to 21.1.0 from 20.12.2 fails with CrashLoopBackOff of Kafka pods. Upgrade instructions are not helpful.

**Comment by mosesdd** [comment]
fixed by deleting stateful set and recreating by chart

**Comment by hanife-Orthopy** [comment]
Hi @mosesdd ,  after recreating the sentry-kafka stateful set, there is an internal error in the sentry UI issues page. Have you experienced this too?
