### ISSUE TITLE
Sentry v20.6.0

### ISSUE THREAD

**Issue by l0nax** [sentry-kubernetes/charts#115]
#### Description

Since [sentry version v20.6.0](https://github.com/getsentry/sentry/releases/tag/20.6.0) has been released, it would be nice to be
able to install v20.6.0 also on the cluster.

**Comment by Mokto** [comment]
I think we currently use `Sentry 20.7.0.dev0cc9f7d1`?

**Comment by l0nax** [comment]
Because the `README.md` says
> Sentry 10 helm charts

Also in the [`Chart.yaml`](https://github.com/sentry-kubernetes/charts/blob/develop/sentry/Chart.yaml) `appVersion` is set to `10.0.0`.

**Comment by vishnu123sai** [comment]
Not able configure sentry 10.0.0 even i have change the image tag in values.yaml, can some one help here

**Comment by vishnu123sai** [comment]
I got to know that sentry 10.0.0 is not supported with version 4.3.0 but I want to use sentry 10.0.0, which version support sentry10.0.0

**Comment by Mokto** [comment]
You can try 1.3.1.
