### ISSUE TITLE
Error: INSTALLATION FAILED: failed post-install: 1 error occurred: * job sentry-db-check failed: DeadlineExceeded

### ISSUE THREAD

**Issue by tim1737** [sentry-kubernetes/charts#1151]
please help  I can't solve it in any way for 3 days, there is no solution in the third, I tried everything from setting the extra time to the storage class does not help, there are enough resources

logs ---

@k8s-telemetry-1:/opt/k8s-monitoring/sentry$ helm install sentry sentry/sentry --debug
install.go:214: [debug] Original chart version: ""
install.go:231: [debug] CHART PATH: /home/babenko/.cache/helm/repository/sentry-21.5.0.tgz

coalesce.go:237: warning: skipped value for kafka.config: Not a table.
clieed: 0
client.go:740: [debug] Add/Modify event for sentry-db-check: MODIFIED
client.go:779: [debug] sentry-db-check: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for sentry-db-check: MODIFIED
client.go:779: [debug] sentry-db-check: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:740: [debug] Add/Modify event for sentry-db-check: MODIFIED
Error: INSTALLATION FAILED: failed post-install: 1 error occurred:
        * job sentry-db-check failed: DeadlineExceeded

helm.go:84: [debug] failed post-install: 1 error occurred:
        * job sentry-db-check failed: DeadlineExceeded

INSTALLATION FAILED
main.newInstallCmd.func2
        helm.sh/helm/v3/cmd/helm/install.go:154
github.com/spf13/cobra.(*Command).execute
        github.com/spf13/cobra@v1.8.0/command.go:983
github.com/spf13/cobra.(*Command).ExecuteC
        github.com/spf13/cobra@v1.8.0/command.go:1115
github.com/spf13/cobra.(*Command).Execute
        github.com/spf13/cobra@v1.8.0/command.go:1039
main.main
        helm.sh/helm/v3/cmd/helm/helm.go:83
runtime.main
        runtime/proc.go:267
runtime.goexit
        runtime/asm_amd64.s:1650
@k8s-telemetry-1:/opt/k8s-monitoring/sentry$

**Comment by agronick** [comment]
I'm having this issue as well

**Comment by agronick** [comment]
Put `--timeout 1h` after `helm install`
