### ISSUE TITLE
Slack configuration supports only legacy bots

### ISSUE THREAD

**Issue by toabi** [sentry-kubernetes/charts#118]
Slack Apps created after June 2020 somehow are behaving differently.

The docs were updated here: https://github.com/getsentry/develop/blob/master/src/docs/integrations/slack/index.mdx

But the helm template only creates this structure:

```
  {{- if .Values.slack.clientId }}
    slack.client-id: "{{ .Values.slack.clientId }}"
    slack.client-secret: "{{ .Values.slack.clientSecret }}"
    slack.verification-token: "{{ .Values.slack.verificationToken }}"
    {{ end }}
```

**Comment by Mokto** [comment]
This has been fixed a while ago, forgot to close the issue!
