### ISSUE TITLE
Sentry chart 22.2.0 is not released

### ISSUE THREAD

**Issue by kimxogus** [sentry-kubernetes/charts#1226]
Sentry chart 22.2.0 release is made in github release, and it seems releasing chart job succeeded, but I can't find it in the chart repository

https://sentry-kubernetes.github.io/charts/index.yaml
https://github.com/sentry-kubernetes/charts/actions/runs/8719675690

**Comment by kimxogus** [comment]
@Mokto Is there a delay to be released in the chart repository?

**Comment by Mokto** [comment]
The build failed yesterday. I restarted it.

**Comment by Mokto** [comment]
https://github.com/sentry-kubernetes/charts/actions/runs/8719683470
