### ISSUE TITLE
Scalability: How to increase the number of partitions and consumers 

### ISSUE THREAD

**Issue by yildizozgur** [sentry-kubernetes/charts#1252]
Hi,

How to increase the number of partitions and the number of consumers for Snuba and sentry to achieve a high level of scalability. 
I saw some information on the forums like:

config:
  snubaSettingsPy: |
    TOPIC_PARTITION_COUNTS = {
      "errors-replacements": 1,
      "event-replacements": 1,
      "events": 2,
      "ingest-attachments": 1,
      "ingest-events": 2,
      "ingest-sessions": 1,
      "ingest-transactions": 1,
      "outcomes": 2,
      "snuba-commit-log": 2,
    }
    
I have tried this setting and checked # of partitions in Kafka. They are still the same number which is 1. Did I missed something?

 `I have no name!@sentry-qa-kafka-0:/$ kafka-consumer-groups.sh --bootstrap-server 127.0.0.1:9092 --describe --group snuba-consumers

GROUP           TOPIC           PARTITION  CURRENT-OFFSET  LOG-END-OFFSET  LAG             CONSUMER-ID                                  HOST            CLIENT-ID
snuba-consumers outcomes        0          63270           63272           2              
snuba-consumers events          0          43812           43814           2        

`

**Comment by NikolaiIuzhaninYS** [comment]
Not sure if snuba can utilize partitioning (might be wrong), but for sentry consumers it's possible to partition the corresponding topics. Example section in values.yaml:
```
kafka:
  provisioning:
    topics:
      - name: ingest-transactions
        partitions: 4
     ...
```
You can copy the list from values.yaml of this chart and add partitions to the topics you need to have it in

**Comment by NikolaiIuzhaninYS** [comment]
Afair with snuba consumers you can just play with concurrency and resource quotas

**Comment by yildizozgur** [comment]
Thank you very much @NikolaiIuzhaninYS , that seems worked
