### ISSUE TITLE
Typo in deployment-snuba-subscription-consumer-metrics.yaml

### ISSUE THREAD

**Issue by cloud-digitaltag** [sentry-kubernetes/charts#1271]
There is typo in charts/sentry/templates/deployment-snuba-subscription-consumer-metrics.yaml in line 78
Currently is:
```
- "--consumer-group=nuba-metrics-subscriptions-consumers"
```
I think should be:
```
- "--consumer-group=snuba-metrics-subscriptions-consumers"
```

**Comment by Mokto** [comment]
Fixed in https://github.com/sentry-kubernetes/charts/commit/d667d0cd18e36af06e6ba3050a850265df540e1d
