### ISSUE TITLE
New workers in 23.x: workerEvents is disabled, workerTransactions is enabled

### ISSUE THREAD

**Issue by eht16** [sentry-kubernetes/charts#1274]
I'm not sure if I understand the new splitted worker setup completely:

In the `values.yaml` 
- `workerEvents` deployment is disabled (https://github.com/sentry-kubernetes/charts/blob/develop/sentry/values.yaml#L216) and 
- `workerTransactions` is enabled (https://github.com/sentry-kubernetes/charts/blob/develop/sentry/values.yaml#L245).

Is this on purpose?

What is the effect in relation to the existing `worker` deployment?

I'd understand this as the `worker` POD(s) consume events *and* transactions and the specific `workerTransactions` POD(s) consume only transactions in addition to the `worker` POD(s)?

If this assumption is correct, then I could disable the `workerTransactions` deployment as well, provided that I'm fine with having them all processed by the generic `worker` POD(s)?

**Comment by NikolaiIuzhaninYS** [comment]
Enabling transactions-worker by default was not on purpose. My mistake =/
Both events- and transactions- worker deployments are dedicated to shift the performance balance to the queues specific to these types of ingestion. So they **could** be enabled in case of insufficient performance (specific queues' lengths are growing).
I'll revise this part and propose a fix ASAP

**Comment by eht16** [comment]
Thanks for the explanation and values fix in https://github.com/sentry-kubernetes/charts/pull/1275.
