### ISSUE TITLE
Issue with image replacement of sentry 10.0.0

### ISSUE THREAD

**Issue by vishnu123sai** [sentry-kubernetes/charts#129]
If we edit the deployment with sentry 10.0.0, pods are not creating, thronging Error and POD is going BackOff state

**Comment by Mokto** [comment]
Sorry, I don't plan on supporting version 10.0.0 anymore (version 1 of this chart).
Why don't you just use the latest one?

**Comment by vishnu123sai** [comment]
My requirement is to use 10.0.0 only, I am try all versions but getting lot of errors with 10.0.0
