### ISSUE TITLE
Bitnami version mismatch

### ISSUE THREAD

**Issue by benedikt-bartscher** [sentry-kubernetes/charts#1333]
https://github.com/sentry-kubernetes/charts/pull/1301 introduced a regression.

With sourcemaps/memcached enabled like this:
```yaml
# sentry values.yaml
sourcemaps:
  # this enables memcached subchart
  enabled: true
```

Helm install fails with this error:

```log
rendering helm chart sentry for release sentry has failed: template: sentry/charts/nginx/templates/tls-secret.yaml:13:14: executing "sentry/charts/nginx/templates/tls-secret.yaml" at <include "common.labels.standard" (dict "customLabels" .Values.commonLabels "context" $)>: error calling include: template: sentry/charts/memcached/charts/common/templates/_labels.tpl:11:27: executing "common.labels.standard" at <include "common.names.name" .>: error calling include: template: sentry/charts/memcached/charts/common/templates/_names.tpl:11:18: executing "common.names.name" at <.Chart.Name>: nil pointer evaluating interface {}.Name
```

There are many issues like these in the bitnami helm chart repo. It happens if you mix and match bitnami charts with different versions.

Possible solution: Update memcached chart?

**Comment by TartanLeGrand** [comment]
Why do you think it's related to nginx when the error you describe is a memcache error?

**Comment by benedikt-bartscher** [comment]
take a close look at the error message. it's a version conflict between nginx and memcached

**Comment by TartanLeGrand** [comment]
You are in the `23.9.1` ?

**Comment by benedikt-bartscher** [comment]
This error occurs with every tagged version of this chart since #1301 was merged.

**Comment by TartanLeGrand** [comment]
Okay I got the version: https://github.com/sentry-kubernetes/charts/releases/tag/sentry-v23.7.0

But your issue is linked with the issue:

- https://github.com/sentry-kubernetes/charts/issues/1315
