### ISSUE TITLE
Post process forwarder: commit-batch-size=1

### ISSUE THREAD

**Issue by joscha-alisch** [sentry-kubernetes/charts#138]
Hi there :) 

is there specific reason why commit batch size is set to 1 in the post-process-forward deployment? I've seen the app be able to process a much higher volume of post processing when I remove this option. 

In case this can be removed, I am happy to provide a PR, either removing it altogether or at least making it configurable :)

**Comment by Mokto** [comment]
The idea was to follow the official docker solution -> https://github.com/getsentry/onpremise/blob/master/docker-compose.yml#L172

But you can make it configurable if you want ;)

**Comment by joscha-alisch** [comment]
Ah cool, it even says that this should be adapted according to needs in the comment. I'll get that PR ready :)
