### ISSUE TITLE
i am not able to assign cutom image to helm chart with --set images.sentry.repository=sentry ,  --set images.sentry.tag=9.1.2

### ISSUE THREAD

**Issue by vishnu123sai** [sentry-kubernetes/charts#139]
helm install stable/sentry --version 4.3.0 --set images.sentry.repository=sentry --set images.sentry.tag=9.1.2 --set user.email=xxxxx@gmail.com --set user.password=Qwerty@123

I am not able to change the image while installing.

**Comment by Mokto** [comment]
What do you mean by "I am not able to change the image while installing"? It crashes, it shows an error ?

**Comment by vishnu123sai** [comment]
it is not effecting the chart, we are getting same image what is by default.

**Comment by Mokto** [comment]
You're not using this chart, you're using the deprecated one.

**Comment by vishnu123sai** [comment]
even with 4.6.0 it is not working

**Comment by Mokto** [comment]
Please use https://sentry-kubernetes.github.io/charts
