### ISSUE TITLE
Current chart doesn't deploy broker - No sentry errors processed

### ISSUE THREAD

**Issue by matias-easymile** [sentry-kubernetes/charts#1394]
```2024-08-22T14:18:54+02:00 [2024-08-22 12:18:54,635] INFO [QuorumController id=0] CreateTopics result(s): CreatableTopic(name='__consumer_offsets', numPartitions=50, replicationFactor=3, assignments=[], configs=[CreateableTopicConfig(name='compression.type', value='producer'), CreateableTopicConfig(name='cleanup.policy', value='compact'), CreateableTopicConfig(name='segment.bytes', value='104857600')]): INVALID_REPLICATION_FACTOR (Unable to replicate the partition 3 time(s): The target replication factor of 3 cannot be reached because only 1 broker(s) are registered.) (org.apache.kafka.controller.ReplicationControlManager)```

Seems we need to overwrite the following value of controller replicacount for fresh install : 
```
kafka:
  controller:
    replicaCount: 1
```

To : 
```
kafka:
  controller:
    replicaCount: 3
```

I personally choosed to add enough brokers to be compliant with replicationFactor using an upgrade with : 
```

kafka:
  broker:
    replicaCount: 3
```
Note: broker number is 0 with default kafka deployment because controller do both controller+broker.

To ensure low resources consumption as started in following PR : https://github.com/sentry-kubernetes/charts/pull/1379/files
We should change the replication factor to 1 for offset topics (which is 3 by default).

> <h4 style="box-sizing: border-box; line-height: 1.4; -webkit-font-smoothing: antialiased; text-rendering: optimizelegibility; font-size: 2rem; font-weight: 700; margin: 0px; color: rgb(0, 0, 0); font-family: Roboto, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a id="connectconfigs_offset.storage.replication.factor" href="https://kafka.apache.org/documentation/#connectconfigs_offset.storage.replication.factor" style="box-sizing: border-box; color: rgb(0, 0, 0); -webkit-font-smoothing: antialiased; text-rendering: optimizelegibility;">offset.storage.replication.factor</a></h4><p style="box-sizing: border-box; color: rgb(0, 0, 0); font-family: Roboto, sans-serif; font-size: 15px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Replication factor used when creating the offset storage topic</p>
> Type: | short
> -- | --
> 3
> Positive number not larger than the number of brokers in the Kafka cluster, or -1 to use the broker's default
> low
> 
> [offset.storage.replication.factor](https://kafka.apache.org/documentation/#connectconfigs_offset.storage.replication.factor)
> Replication factor used when creating the offset storage topic
> 
> Type:	short
> Default:	3
> Valid Values:	Positive number not larger than the number of brokers in the Kafka cluster, or -1 to use the broker's default
> Importance:	low
See: https://kafka.apache.org/documentation/#brokerconfigs_offsets.topic.replication.factor

Switch the number of replica factor was suggested here (comment seems old i suspect the env var to be deprecated): 
https://github.com/getsentry/self-hosted/issues/502#issuecomment-647401190

**Comment by matias-easymile** [comment]
I think 2 broker+1controller can be compliant (in term of the replicationFactor), so adding this to the default chart shall allow the deployment to work again:
```
kafka:
  broker:
    replicaCount: 2```
 Note: Using simple broker in place of controller+broker shall reduce resource consumption without tuning to much the default replication factor behavior (which will be hard to document and maintain).

**Comment by Mokto** [comment]
Thanks I changed that again in 25.0.0.
