### ISSUE TITLE
Hardcoded config map fails on deployment not named "sentry"

### ISSUE THREAD

**Issue by ts-mini** [sentry-kubernetes/charts#145]
I believe this line is the culprit:   

https://github.com/sentry-kubernetes/charts/blob/7ae365187da883efd891c351dc75c2e566112718/sentry/values.yaml#L247

How to reproduce: Install this chart from scratch with the release name "sentry-test" - everything will boot but `sentry-test-nginx` as its looking for the wrong config map

**Comment by Mokto** [comment]
Unfortunately I'm leaving for 2 weeks tomorrow so I don't have time to fix that, but I'm sure someone else will find a solution.

One would be to use nginx without a chart:
Like here : https://github.com/sentry-kubernetes/charts/pull/130/files#diff-be3a4173e7b3150feac7a6214ee6a288

**Comment by hairmare** [comment]
I ran into this exact case when I named my release `test-sentry`. The hardcoded `existingServerBlockConfigmap` should be based on something generated, leaving the value available to folx that have a real need to override it. 

As a workaround you'll have to specify a value matching your configmap.

**Comment by Mokto** [comment]
Fixed through 5.3.0
