### ISSUE TITLE
No ability to add tolerations/nodeselectors/nodeAffinity to Subcharts

### ISSUE THREAD

**Issue by ivanblack19** [sentry-kubernetes/charts#151]
Helm chart 5.0.0 installed but I could not to force clickhouse , kafka , rabbitmq, postgresql , redis , zookeeper services to dedicated node pool for Sentry.
Could you suggest how to deal with that ?

**Comment by hairmare** [comment]
With some of these (esp. those from external chart repos) you will probably want to replace them with your own/an other chart and configure them as an external services in the actual sentry deployment.

In most cases sentry-kubernetes offers the option to do this, but you might be off the well trodden path and would have to PR some fixes to make this possible.

clickhouse is the only chart hosted in this repo you mention and it would benefit from some changes that make it possible to deploy it with tolerations/nodeselectors/nodeAffinity. tbh I don't know clickhouse enough to recommend any of those atm, maybe someone that has more clickhouse experience can chip in.

Given that you are mentioning almost all of the deps on the sentry chart, have you considered other venues (i.e. using a mutating admission controller or a helm + kustomize combo) to achieve your goals?

**Comment by ivanblack19** [comment]
We are using it on Google Kubernetes Engine with Terraform + Helm (not sure if mutating admission controller or a helm + kustomize available  )
The issue actually that extra charts are given as .tgz and we are not able to pass any values to it, and modifying them for sure will need much effort to keep consistent

**Comment by hairmare** [comment]
> The issue actually that extra charts are given as .tgz and we are not able to pass any values to it

Hmm... I was under the impression that the charts do not support what you need (which is not the case for postgresql).

You can pass extra values to the included charts (ie. specifying a nodeSelector for the postgresql master) as follows:

```
postgresql:
  master:
    nodeSelector:
      foo: bar
```

See [here](https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#overriding-values-from-a-parent-chart) for more docs on how to pass values to subcharts.

**Comment by ivanblack19** [comment]
Hello your suggestion actually works fine
How about sentry-zookeeper ? I can not find how it is deployed or configured ?

**Comment by ivanblack19** [comment]
Zookeeper in Jafka actually!

**Comment by ivanblack19** [comment]
Zookeeper in Kafka actually! Solved!
