### ISSUE TITLE
github integration fails

### ISSUE THREAD

**Issue by KrawczowaKris** [sentry-kubernetes/charts#1511]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/sentry-kubernetes/charts/issues)

### Describe the bug (actual behavior)

hi team, 
I have problem with github integration, can you help me, please?
I configured the github app with the following parameters:

```bash
Homepage URL: https://sentry.domain.com
Callback URL: https://sentry.domain.com/auth/sso/
Callback URL: https://sentry.domain.com/extensions/github/setup/
Setup URL:    https://sentry.domain.com/extensions/github/setup/
Webhook URL:  https://sentry.domain.com/extensions/github/webhook/
```

and passed all params to the sentry configuration
but now after trying to install the application, it is installed in github, but not installed in sentry, and I get the following error (in the picture). What could this be related to?

### Expected behavior

github integration will be installed correctly

### values.yaml

```bash
github:
  appId: "XXXX"
  appName: sentry-app
  clientId: XXXX
  clientSecret: XXXX
  privateKey: "XXXX"
  webhookSecret: "XXXX"
```

### Helm chart version

25.11.1

### Steps to reproduce

- create a github app;
- pass parameters to values.yaml;
- try to install github integration.

### Screenshots

![image](https://github.com/user-attachments/assets/9057f074-48b7-4362-9f2a-7d2670c3384d)

**Comment by sdernbach-ionos** [comment]
@KrawczowaKris I also had problems with the installation. I just copy our internal documentation, which worked for us:

```
Create a app via this: [Self-Hosted Single Sign-On (SSO)](https://develop.sentry.dev/self-hosted/sso/#github-auth)
Save everything as a secret and configure the values.yaml file

github:
  appId: xxxxxx
  appName: "xxxx-sentry-integration"
  existingSecret: "sentry-github"

Setup the following in ResourceOverride (Chrome extension, or change URL manually in the browser during setup instead):
https://sentry.domain.com/auth/sso/** -> https://sentry.domain.com/extensions/github/setup/**

Go to the app in GitHub and install to the organization (eg: https://github.com/organizations/xxxxx/settings/apps/xxxx-sentry-integration/installations)

Confirm in Sentry that it should get installed to the “Sentry” organization. After that a popup opens informing about an invalid redirect_uri, copy the url open in the browser and change the redirect_uri from redirect_uri=https://sentry.domain.com/extensions/github/setup/ to redirect_uri=https://sentry.domain.com/auth/sso/

Confirm the GitHub setup screen until GitHub returns you to the setup window and says “you can safely close this window now”. GitHub is installed now.
```

**Comment by sinkr** [comment]
Hi guys,

I've been battling this all day and have attempted the method above.  The secrets are correctly  being injected into the pods, however, I cannot make it work with the above method and am certain I'm missing something.

I have tried recreating the app multiple times to no avail.  I must be missing something.

I have tried both the app ID and installation ID for the appID.  The app ID that is on the application's page atop and the installation ID found at `settings/installations`.

I've set up other apps to use GitHub like [Kodiak](https://github.com/chdsbd/kodiak), so I feel like something's not being conveyed somehow/where.

values.yaml:
```
github:
  appId: "<redacted-from-app-page>"
  appName: "Sentry-Integration-Self-Hosted"
  existingSecret: sentry-github-secret
```

sentry-github-secret:
```
apiVersion: v1
data:
  client-id: <verified b64 client ID from GH App page>
  client-secret: <verified b64 client secret>
  private-key: <verified b64 certificate>
  webhook-secret: <verified b64 value>
kind: Secret
```

Any help would be appreciated.

**Comment by sdernbach-ionos** [comment]
@sinkr you definitely have to use the app id, not the installation id. What error is shown or why do you think it is not working?

**Comment by sinkr** [comment]
Hi @sdernbach-ionos, thank you for the response, I am definitely now using the correct app ID, as displayed atop the app's settings page.

What happens is, when I initiate "Install" from GitHub's side, I get the consent screen and click "Install and Authorize," then I'm taken into my self-hosted Sentry's issues page.

I see this log entry, which I guess is the crux of it, but I have changed and verified and re-verified that the webhook signing token that I gave GitHub is what's in the Kubernetes secret and translates to the environment variable `GITHUB_APP_WEBHOOK_SECRET`:

```
08:00:57 [WARNING] django.request: Unauthorized: /extensions/github/webhook/ (status_code=401 request=<WSGIRequest: POST '/extensions/github/webhook/'>)
```

**Comment by sdernbach-ionos** [comment]
@sinkr I think it is best to check your network calls in the browser dev tools, so you can see where the redirect from Github is going and if there is a redirect of Sentry happening. Regarding the webhook you can also check that within your GitHub app in the advanced section. It lists all webhook calls with results.

For us the first time we had the problem that the secret accidentally contained a space in a secret, so best if you compare the base64 value with manually creating a base64 string of your value in terminal for example.

**Comment by sinkr** [comment]
I've verified everything at least 5x now.  No spaces, the values match, and they sha256 out both what's in pod and I have verified what is in GitHub is correct.  I'm at a loss.

**Comment by sinkr** [comment]
@sdernbach-ionos I have quadruple-checked everything and there is no spaces.  I can see in the logs that the requests are definitely hitting my server, and in advanced, this is a typical `401` I get:

```
Access-Control-Allow-Headers: X-Sentry-Auth, X-Requested-With, Origin, Accept, Content-Type, Authentication, Authorization, Content-Encoding, sentry-trace, baggage, X-CSRFToken
Access-Control-Allow-Methods: POST, OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: X-Sentry-Error, X-Sentry-Direct-Hit, X-Hits, X-Max-Hits, Endpoint, Retry-After, Link
Allow: POST, OPTIONS
Content-Language: en
Content-Length: 0
Content-Security-Policy-Report-Only: font-src 'self' data:; media-src *; base-uri 'none'; object-src 'none'; frame-ancestors 'none'; style-src 'unsafe-inline' *; default-src 'none'; script-src 'self' 'unsafe-inline' 'report-sample'; worker-src 'none'; connect-src 'self' *.algolia.net *.algolianet.com *.algolia.io; img-src blob: data: *
Content-Type: text/html; charset=utf-8
Date: Wed, 09 Oct 2024 13:27:39 GMT
Strict-Transport-Security: max-age=31536000; includeSubDomains
Vary: Accept-Language, Cookie
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-Xss-Protection: 1; mode=block
```

I'm out of ideas--I've restarted everything to no avail.

**Comment by sdernbach-ionos** [comment]
@sinkr a 401 is totally fine if GitHub already sends a webhook event but the integration is not installed yet as far as I remember. What is shown in your network log? Is the redirect made to the integration of Sentry or directly to the root path/issues view?

Have you started the integration on sentry side or on GitHub side (by installing the app to the organization) ?

**Comment by sinkr** [comment]
@sdernbach-ionos, yes, the app is installed to the organization.

I can see in the logs of sentry-web, when I attempt to install the app, I get this error:
```
sentry sentry-web-59f48d57bf-tf28b sentry-web 14:13:26 [ERROR] sentry.webhooks: github.webhook.invalid-signature (request_method='POST' request_path='/extensions/github/webhook/')
sentry sentry-web-59f48d57bf-tf28b sentry-web 14:13:26 [INFO] sentry.access.api: api.access (method='POST' view='sentry.integrations.github.webhook.GitHubIntegrationsWebhookEndpoint' response=401 user_id='None' is_app='None' token_type='None' is_frontend_request='False' organization_id='None' auth_id='None' path='/extensions/github/webhook/' caller_ip='140.82.115.243' user_agent='GitHub-Hookshot/ea13e4a' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.010591506958007812 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
sentry sentry-web-59f48d57bf-tf28b sentry-web 14:13:26 [WARNING] django.request: Unauthorized: /extensions/github/webhook/ (status_code=401 request=<WSGIRequest: POST '/extensions/github/webhook/'>)
```

**Comment by sdernbach-ionos** [comment]
@sinkr sorry I mean the network logs of the developer tools, so if you uninstall the app again, then click install, what urls are shown in the network developer tools tab, to see what redirects are happening

**Comment by sinkr** [comment]
@sdernbach-ionos, Yes, I see it hitting my server:
<img width="340" alt="image" src="https://github.com/user-attachments/assets/4fee61de-465d-4356-84ac-549ea48a44ff">

**Comment by sdernbach-ionos** [comment]
@sinkr please install ResourceOverride or any other extension and setup this redirect as mentioned above:

```
Setup the following in ResourceOverride (Chrome extension, or change URL manually in the browser during setup instead):
https://sentry.domain.com/auth/sso/** -> https://sentry.domain.com/extensions/github/setup/**
```

**Comment by sinkr** [comment]
@sdernbach-ionos thank you for your continued help.

I did try the ResourceOverride extension at one point, but wasn't having any luck getting the last mile.

What did help was downgrading and reinstalling from the latest app / chart to the previous chart 25.5.1 / app 24.5.1.

At this point, with the same values.yaml, my `401`s from the advanced tab became `204`s, but I still wasn't getting the last mile redirect after I acknowledged all the screens.  Maybe this is where ResourceOverride came in handy.

Finally, what worked was disabling `Request user authorization (OAuth) during installation` and the app finally installed and my repositories populated.

**Comment by mxsxs2** [comment]
Sorry to necro this but I cant seem to find an answer:

How did you save the private-key? I keep getting the following:

> 09:47:02 [WARNING] sentry.integrations.utils.metrics: integrations.installation.failure (organization_id=1 integration_domain='source_code_management' integration_name='github' interaction_type='oauth_login' slo_event_id='944c3ff50dea4c94a4877be8f522610b' exception_summary="ValueError('Unable to load PEM file. See https://cryptography.io/en/latest/faq/#why-can-t-i-import-my-pem-file for more details. InvalidData(InvalidByte(0, 92))')")
09:47:02 [INFO] sentry_sdk.errors: event processor (<function DedupeIntegration.setup_once.<locals>.processor at 0x7f0db138b740>) dropped event
Traceback (most recent call last):
  File "/.venv/lib/python3.13/site-packages/jwt/algorithms.py", line 257, in prepare_key
    key = load_pem_private_key(key, password=None)
ValueError: ('Could not deserialize key data. The data may be in an incorrect format, the provided password may be incorrect, it may be encrypted with an unsupported algorithm, or it may be an unsupported key type (e.g. EC curves with explicit parameters).', [<OpenSSLError(code=503841036, lib=60, reason=524556, reason_text=unsupported)>])

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/.venv/lib/python3.13/site-packages/sentry_sdk/integrations/django/views.py", line 94, in sentry_wrapped_callback
    return callback(request, *args, **kwargs)
  File "/.venv/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/.venv/lib/python3.13/site-packages/django/views/decorators/csrf.py", line 65, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/usr/src/sentry/src/sentry/web/frontend/base.py", line 417, in dispatch
    return self.handle(request, *args, **kwargs)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/web/frontend/pipeline_advancer.py", line 61, in handle
    response = pipeline.current_step()
  File "/usr/src/sentry/src/sentry/pipeline/base.py", line 189, in current_step
    return step.dispatch(self.request, pipeline=self)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/integrations/github/integration.py", line 797, in dispatch
    self.client = GithubSetupApiClient(access_token=payload["access_token"])
                  ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/integrations/github/client.py", line 74, in __init__
    self.jwt = get_jwt()
               ~~~~~~~^^
  File "/usr/src/sentry/src/sentry/integrations/github/utils.py", line 33, in get_jwt
    return jwt.encode(payload, github_private_key, algorithm="RS256")
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/utils/jwt.py", line 109, in encode
    return pyjwt.encode(payload, key, algorithm=algorithm, headers=headers)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.13/site-packages/jwt/api_jwt.py", line 64, in encode
    return api_jws.encode(json_payload, key, algorithm, headers, json_encoder)
           ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.13/site-packages/jwt/api_jws.py", line 133, in encode
    key = alg_obj.prepare_key(key)
  File "/.venv/lib/python3.13/site-packages/jwt/algorithms.py", line 259, in prepare_key
    key = load_pem_public_key(key)
ValueError: Unable to load PEM file. See https://cryptography.io/en/latest/faq/#why-can-t-i-import-my-pem-file for more details. InvalidData(InvalidByte(0, 92))
09:47:02 [ERROR] django.request: Internal Server Error: /extensions/github/setup/ (status_code=500 request=<WSGIRequest: GET '/extensions/github/setup/?code=6315c583f4a94a47538d&state=28bd7193c72c28d1fadddd61049d4b48'>)
09:47:02 [INFO] sentry.access.api: api.access (method='GET' view='sentry.web.frontend.pipeline_advancer.PipelineAdvancerView' response='500' user_id='1' is_app='False' is_frontend_request='True' path='/extensions/github/setup/' caller_ip='86.43.84.89' user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36' rate_limited='False' request_duration_seconds='0.9938869476318359' rate_limit_type='DNE')


I have the key in my .env file which I use to create the secret. Something like this:
```
private-key="-----BEGIN RSA PRIVATE KEY-----\nMIIEp...dv1YO5\nfQkP...1ExNtvvm7K\n...VYSj+Jg==\n-----END RSA PRIVATE KEY-----\n"
```
Each new line in the key file is replaced with a `\n`. Obviously this does not work for me.
I also tried to not have `\n` between the lines of the key and only add the beginning, end and the trailing one. That did not work either.

I tried to add to the secret as a string the same way how it is present in the key file and that did not work either.

I can see that the pod gets the value of private-key:

> GITHUB_APP_PRIVATE_KEY="-----BEGIN RSA PRIVATE KEY-----\nMIIEpA
