### ISSUE TITLE
Getting Error if i click on events , Errors in clickhouse

### ISSUE THREAD

**Issue by vishnu123sai** [sentry-kubernetes/charts#156]
![image](https://user-images.githubusercontent.com/35533739/90790652-f0b65e00-e325-11ea-8a6a-0201189b17d3.png)

events page is not loading, getting errors clickhouse

<Debug> MemoryTracker: Peak memory usage (total): 0.00 B. 2020.08.20 21:26:05.420204 [ 10 ] {35e1674afab5945846e3284f57300e04} <Error> executeQuery: Code: 60, e.displayText() = DB::Exception: Table default.sentry_dist doesn't exist. (version 19.16.19.85 (official build)) (from 10.28.3.63:48462) (in query: SELECT (arrayJoin(tags.key) AS tags_key), (count() AS count) FROM sentry_dist SAMPLE 1 PREWHERE project_id IN (1) WHERE project_id IN (1) AND timestamp >= toDateTime('2020-05-22T13:26:05') AND timestamp < toDateTime('2020-08-20T13:26:05') AND deleted = 0 GROUP BY (tags_key) ORDER BY count DESC LIMIT 0, 1000), Stack trace: 0. 0x557f5408e544 StackTrace::StackTrace() /usr/bin/clickhouse

**Comment by J0sh0nat0r** [comment]
@vishnu123sai Please could you provide the output of the `clickhouse-init` job, along with any custom configuration you have for ClickHouse?

**Comment by vishnu123sai** [comment]
Actually job was failing, so i manually doing the tasks which are in jobs. Can you please let me know the manual steps for clickhouse init job and what it will do if we ran the job?


what type of information will be stored in clickhouse?

**Comment by vishnu123sai** [comment]
Received exception from server (version 19.16.19):
Code: 170. DB::Exception: Received from sentry-1598017392-clickhouse-0.sentry-1598017392-clickhouse-headless:9000. DB::Exception: Bad get: has UInt64, requested String.

**Comment by vishnu123sai** [comment]
Can you please provide manual steps for clickhouse init job

**Comment by J0sh0nat0r** [comment]
The steps the job takes depend on your ClickHouse configuration and the template can be found [here](https://github.com/sentry-kubernetes/charts/blob/7ae365187da883efd891c351dc75c2e566112718/sentry/templates/hooks/clickhouse-init.job.yaml#L42), you could run them manually however your deployment is likely to break at some point in the future if this job cannot run successfully.

**Comment by Mokto** [comment]
@vishnu123sai have you fixed your issue ?

**Comment by vishnu123sai** [comment]
yes,

**Comment by Mokto** [comment]
Cool, thanks.
