### ISSUE TITLE
Make App Version = Chart Version

### ISSUE THREAD

**Issue by sharkymcdongles** [sentry-kubernetes/charts#1586]
It is very counter intuitive to have the chart version differ so much from the app version. It would make sense to make them 1:1 or at least share the same major and minor versions if the chart needs special updates independent of Sentry releases.

**Comment by Mokto** [comment]
With such a system we wouldn't be able to follow SemVer properly.

**Comment by sdernbach-ionos** [comment]
To be honest I think it is more important to see if there are breaking changes within the chart then saving the one click to check the app version within the chart.yaml - if you would have 24.10.100 you wouldn't know if switch from 99 to 100 means a fix, new functionality or even a breaking change

**Comment by sharkymcdongles** [comment]
Then I suggest being on a much higher number for the chart version. There
are hardly any chart versions of any mainstream charts commonly used that
are 20.x.x+ which makes it confusing IMO. And having the app be 24.x.x and
the chart also in the 20s it is a bit confusing.

**Comment by Mokto** [comment]
It's at 26 right now, so I don't think that's an issue anymore.
