### ISSUE TITLE
CSRF Verification Failed

### ISSUE THREAD

**Issue by aidenpearce001** [sentry-kubernetes/charts#1587]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/sentry-kubernetes/charts/issues)

### Describe the bug (actual behavior)

When access sentry-nginx and sentry-web logs i got this issue.
![image](https://github.com/user-attachments/assets/a9d614b5-7e60-4373-8570-3fb957e3c357)

### Expected behavior

I can see Sentry Issues and Dashboard after login.

### values.yaml

user:
  create: false

asHook: true

# nginx:
#   enabled: false

ingress:
  enabled: true
  regexPathStyle: nginx
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/proxy-set-header: "Referer $http_referer"
    nginx.ingress.kubernetes.io/proxy-set-header: "Origin $http_origin"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
  hostname: sentry.yitec.dev

service:
  type: ClusterIP
  externalPort: 9000
  annotations: {}

hooks:
  activeDeadlineSeconds: 1000

snuba:
  api:
    replicas: 1
  consumer:
    replicas: 1
  issueOccurrenceConsumer:
    replicas: 1
  outcomesConsumer:
    replicas: 1
  profilingFunctionsConsumer:
    replicas: 1
  profilingProfilesConsumer:
    replicas: 1
  replacer:
    replicas: 1
  replaysConsumer:
    replicas: 1
  sessionsConsumer:
    replicas: 1
  subscriptionConsumerEvents:
    replicas: 1
  subscriptionConsumerSessions:
    replicas: 1
  subscriptionConsumerTransactions:
    replicas: 1
  transactionsConsumer:
    replicas: 1
memcached:
  replicaCount: 1
rabbitmq:
  replicaCount: 1
symbolicator:
  replicas: 1

relay:
  enabled: true
  replicas: 1
  mode: managed
  authentication:
    internal_key: true
  logging:
    level: debug
  probeFailureThreshold: 5
  probeInitialDelaySeconds: 10
  probePeriodSeconds: 10
  probeSuccessThreshold: 1
  probeTimeoutSeconds: 2
  service:
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: 'true'

  autoscaling:
    enabled: false
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 50

sentry:
  singleOrganization: true
  web:
    logLevel: "DEBUG"
    csrf:
      enabled: true
      trustedOrigins: ["sentry.mydomain.dev"]
  auth:
    allowedDomains: ["mydomain.dev"]
  worker:
    replicas: 2
    resources:
      limits:
        cpu: 3000m
        memory: 12288Mi
      requests:
        cpu: 1000m
        memory: 4096Mi
  ingestConsumer:
    replicas: 1
  ingestMetricsConsumerPerf:
    replicas: 1
  ingestMetricsConsumerRh:
    replicas: 1
  ingestMonitors:
    replicas: 1
  resources:
    limits:
      cpu: 2048m
      memory: 8192Mi
    requests:
      cpu: 512m
      memory: 1024Mi

clickhouse:
  clickhouse:
    replicas: "1"
  tabix:
    replicas: "1"

kafka:
  replicaCount: 3
  resources:
    limits:
      cpu: 1000m
      memory: 4096Mi
    requests:
      cpu: 500m
      memory: 2048Mi
  zookeeper:
    replicaCount: 1
zookeeper:
  replicaCount: 3

externalPostgresql:
  host: postgresql.database.svc.cluster.local
  port: 5432
  existingSecret: sentry-postgresql-secret
  database: sentrydb

postgresql:
  enabled: false

system:
  url-prefix: 'https://sentry.mydomain.dev'

### Helm chart version

version.BuildInfo{Version:"v3.16.2", GitCommit:"13654a52f7c70a143b1dd51416d633e1071faffb", GitTreeState:"clean", GoVersion:"go1.22.7"}

### Steps to reproduce

helm upgrade --install sentry sentry/sentry --version 25.3.0 -f sentry/value.yml --namespace sentry --create-namespace --wait --timeout=1000s

after install done i port-forward to local machine for test
kubectl port-forward svc/sentry-nginx 8080:80

access http://localhost:8080/auth/login/sentry/ on local machine thru web brower

### Screenshots

![image](https://github.com/user-attachments/assets/1a2d12b2-9ab9-441a-b5d9-35cd4e50e307)
![image](https://github.com/user-attachments/assets/552cb090-6e64-47a2-a4a6-f4aa63813ef6)
![image](https://github.com/user-attachments/assets/99fa8888-fbb5-4ec3-b17d-7f4137611e4d)
![image](https://github.com/user-attachments/assets/c2c2a327-895d-4756-9f2d-297f2b8469b8)

### Logs

sentry-web logs
```
14:58:42 [INFO] sentry.access.api: api.access (method='POST' view='django.views.generic.base.RedirectView' response=403 user_id='None' is_app='None' token_type='None' is_frontend_request='False' organization_id='None' auth_id='None' path='/api/1/envelope/' caller_ip='42.1.77.204' user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.05183744430541992 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
14:58:49 [WARNING] django.security.csrf: Forbidden (Origin checking failed - http://localhost:8080 does not match any trusted origins.): /auth/login/sentry/ (status_code=403 request=<WSGIRequest: POST '/auth/login/sentry/'>)
14:58:49 [INFO] sentry.access.api: api.access (method='POST' view='sentry.web.frontend.auth_organization_login.AuthOrganizationLoginView' response=403 user_id='None' is_app='None' token_type='None' is_frontend_request='True' organization_id='None' auth_id='None' path='/auth/login/sentry/' caller_ip='10.244.2.75' user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.04647707939147949 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
14:58:49 [WARNING] django.security.csrf: Forbidden (Origin checking failed - http://localhost:8080 does not match any trusted origins.): /api/1/envelope/ (status_code=403 request=<WSGIRequest: POST '/api/1/envelope/?sentry_key=cf484ed2b1b3b78d874fe32aa9547e45&sentry_version=7&sentry_client=sentry.javascript.react%2F8.0.0'>)
14:58:49 [INFO] sentry.access.api: api.access (method='POST' view='django.views.generic.base.RedirectView' response=403 user_id='None' is_app='None' token_type='None' is_frontend_request='False' organization_id='None' auth_id='None' path='/api/1/envelope/' caller_ip='42.1.77.204' user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.03535652160644531 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
14:58:50 [WARNING] django.security.csrf: Forbidden (Origin checking failed - http://localhost:8080 does not match any trusted origins.): /api/1/envelope/ (status_code=403 request=<WSGIRequest: POST '/api/1/envelope/?sentry_key=cf484ed2b1b3b78d874fe32aa9547e45&sentry_version=7&sentry_client=sentry.javascript.react%2F8.0.0'>)
14:58:50 [INFO] sentry.access.api: api.access (method='POST' view='django.views.generic.base.RedirectView' response=403 user_id='None' is_app='None' token_type='None' is_frontend_request='False' organization_id='None' auth_id='None' path='/api/1/envelope/' caller_ip='42.1.77.204' user_agent='Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0' rate_limited='False' rate_limit_category='None' request_duration_seconds=0.033735036849975586 rate_limit_type='DNE' concurrent_limit='None' concurrent_requests='None' reset_time='None' group='None' limit='None' remaining='None')
```

**Comment by aidenpearce001** [comment]
i switch to ingress and it's work fine now

**Comment by WallferJDI** [comment]
> i switch to ingress and it's work fine now

Hi! Faced same issue. Can you please elaborate solution. What you mean by switching to ingress ?

**Comment by aidenpearce001** [comment]
> > i switch to ingress and it's work fine now
> 
> Hi! Faced same issue. Can you please elaborate solution. What you mean by switching to ingress ?

I have write a blog how to develope sentry on k8s with helm: https://medium.com/@aidenpearcewd01/how-to-set-up-sentry-with-helm-on-kubernetes-and-securely-expose-it-via-cloudflared-99928db258a8
You can take a look
