### ISSUE TITLE
9->10 Instructions Clarification

### ISSUE THREAD

**Issue by emcdonnel** [sentry-kubernetes/charts#159]
Hello-

Currently, I am running the deprecated 9 version (specifically the chart sentry-1.3.1). I would like to upgrade Sentry using this repo.

I believe my upgrade will require:
- stable/sentry 1.3.1 to sentry/sentry 3.1.0
- sentry/sentry 3.1.0 to sentry/sentry 4.0.0
- sentry/sentry 4.0.0 to sentry/sentry 5.0.0

For me, Sentry is running in a K8S namespace with other apps.

In the README for 9->10, there is a command listed:
`helm upgrade -n . --set redis.usePassword=true --set redis.password= --set postgresql.postgresqlPassword=`

Is that command the same thing as running the following two commands?
`helm get values sentry > sentry.yaml`
&
`helm upgrade sentry sentry/sentry --version 3.1.0 -f sentry.yaml`

I am not familiar `helm upgrade -n .` but it appears to me that this command will try any upgrades for charts deployed in that namespace. Is that correct?

Thanks for the help.

Thanks so much for creating this repo!

**Comment by DandyDeveloper** [comment]
@emcdonnel Pretty sure the bit over `-n` is hidden by markdown.. It's just for declaring a namespace which in upgrades isn't necessary in helm 2. 

It's only relevant for helm 3, which does require the namespace. This is how it actually looks: 

```
helm upgrade -n <Sentry namespace> <Sentry Release> . --set redis.usePassword=true --set redis.password=<Redis Password> --set postgresql.postgresqlPassword=<Postgresql Password>
```

**Comment by emcdonnel** [comment]
Thanks @DandyDeveloper! That is super helpful.
