### ISSUE TITLE
Variable for set global SAMPLED_DEFAULT_RATE

### ISSUE THREAD

**Issue by artBass-rip** [sentry-kubernetes/charts#1613]
### Discussed in https://github.com/sentry-kubernetes/charts/discussions/1611

<div type='discussions-op-text'>

<sup>Originally posted by **artBass-rip** November 25, 2024</sup>
templates/sentry/_helper-sentry.tpl:
`sentry.conf.py: |-`
`  # Set default for SAMPLED_DEFAULT_RATE:`
`  SAMPLED_DEFAULT_RATE = {{ .Values.global.sampledDefaultRate | default 1.0 }}`</div>

**Comment by artBass-rip** [comment]
I did this 2 weeks ago. It's working! We have more then 10 millions issues for a day, and this helped us to stay alive :)

**Comment by patsevanton** [comment]
@artBass-rip You can make a pull request.

**Comment by Jorgagu** [comment]
👋 @Mokto, perhaps we can close the issue and discussion #1611 since it has been merged into #1634.

**Comment by Mokto** [comment]
Thanks!
