### ISSUE TITLE
Transactions not showing up in the Performance tab

### ISSUE THREAD

**Issue by abhishek-ram** [sentry-kubernetes/charts#162]
## Description

I Installed sentry using this helm chart and I was able to get it up and running. I was able to connect it to my django backend and the issues and events started flowing into sentry. But there is one issue which is that I am able to see transactions being recorded in the Events tab but when I open the Performance tab it says "No Results Found"

## Steps to Reproduce

1. Open the Events tab to see the transactions
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/7054720/91383638-41f4af00-e84a-11ea-9171-246064f7117f.png">

2. Open the Performance tab and it shows no results
<img width="1264" alt="image" src="https://user-images.githubusercontent.com/7054720/91383688-65b7f500-e84a-11ea-87aa-397b3ebe8502.png">

**Comment by Mokto** [comment]
See https://github.com/sentry-kubernetes/charts/pull/142

**Comment by DandyDeveloper** [comment]
@Mokto @abhishek-ram Worth noting, this could also be if Kafka is out of wack and the Snuba consumers can't find their place. I had a similar issue where I had to reset the position in Snuba / Clear out the queue entirely to get it working.

**Comment by Mokto** [comment]
It should be fixed through 5.1.0.

@DandyDeveloper @abhishek-ram let us know if this is enough ;)
