### ISSUE TITLE
Missing profilingFunctionsConsumer.sidecars parameter in values.yaml causes template error in sentry:26.8.0

### ISSUE THREAD

**Issue by rpovoroznyk** [sentry-kubernetes/charts#1624]
### Issue submitter TODO list

- [X] I've searched for an already existing issues [here](https://github.com/sentry-kubernetes/charts/issues)

### Describe the bug (actual behavior)

In the Sentry Helm Chart version 26.8.0, the file charts/sentry/templates/snuba/deployment-snuba-profiling-functions-consumer.yaml includes the following lines:

```
{{- if .Values.profilingFunctionsConsumer.sidecars }}
{{ toYaml .Values.profilingFunctionsConsumer.sidecars | indent 6 }}
{{- end }}
```

However, the parameter profilingFunctionsConsumer.sidecars is not defined in the values.yaml file provided with the chart. This leads to errors during deployment since the template references a non-existent value.

### Expected behavior

The values.yaml file should include a definition for profilingFunctionsConsumer.sidecars, even if it’s commented out or set to null by default.

### values.yaml

```
profilingFunctionsConsumer:
  sidecars: []
```

### Helm chart version

26.8.0

### Steps to reproduce

1. Download or use the Sentry Helm Chart version 26.8.0.
2. Use the default values.yaml without any modifications.
3. Attempt to deploy the chart using Helm:
`helm install sentry ./sentry -f values.yaml`
4. Observe any errors or warnings related to the missing profilingFunctionsConsumer.sidecars parameter.

### Additional context

It is probable that the profilingFunctionsConsumer parameter should be included under `.Values.snuba` rather than at the root level of values.yaml.

**Comment by sdernbach-ionos** [comment]
Same problem here

**Comment by patsevanton** [comment]
@roman-povoroznyk @sdernbach-ionos fix by https://github.com/sentry-kubernetes/charts/releases/tag/sentry-v26.8.1
