### ISSUE TITLE
Unable to restore the backup to postgress pod

### ISSUE THREAD

**Issue by vishnu123sai** [sentry-kubernetes/charts#163]
Unable to restore the backup to postgres pod, how it can be done. what are the steps we need to implement.

**Comment by DandyDeveloper** [comment]
@vishnu123sai This is more likely a question for the pg chart as we use that as a dependency, but in my experience, you just enable restore on the chart, add the details of the backup you wanna restore and upgrade. I believe this creates an init container which restores the data. Obviously, you'd need to clear the existing PVC first so make sure you have a recent backup and an empty directory for pg!

**Comment by Mokto** [comment]
Yeah I'm going to close this, as this is not related to this chart.

But thanks @DandyDeveloper for your help.

**Comment by vishnu123sai** [comment]
Thanks @Mokto @DandyDeveloper , 

I tried by scaling required deployments to zero and then restored my backup in to postgres pod.
