### ISSUE TITLE
Traefik 2.2 Ingress Issues

### ISSUE THREAD

**Issue by achichenin** [sentry-kubernetes/charts#166]
It's not directly an issue of this chart, yet it can be handled internally or, at least, explicitly documented.

**Routes**

Traefik 2.2.x Ingress does require path to be configured as
-  `'/api/{[1-9][0-9]*}/{(.*)}'`
 instead of 
- `'/api/[1-9][0-9]*/(.*)'`

I do not believe that there is a universal version of the configuration for all modern ingress controllers, so helm charts generally have to adapt via explicit ingress class definition in `values` and conditional template rendering with specifics.

The simplest workaround, for now, is to explicitly set route matches in the ingress configuration. 

**CSRF**

Due to issues with csrf I've had to tweak the sentry primary config-map as follows:

- add `system.url-prefix: "sentry.domain.my"` into `config.yml` section
- add `CSRF_TRUSTED_ORIGINS = ['sentry.domain.my']`  into `sentry.conf.py` section

It might be a good idea to add this to the chart as well.

**Comment by Mokto** [comment]
Thanks for this ;)

Maybe you could add this to the README ?

**Comment by Mokto** [comment]
Fixed with 8.1.1, Thanks @szeber

**Comment by daniel5gh** [comment]
Hi, I am running into the same issue with the latest released chart.

I don't see any change/code containing `CSRF_TRUSTED_ORIGINS` either, did this get lost?

I did add `CSRF_TRUSTED_ORIGINS` to my setup manually and it resolved the issue.

thanks!

**Comment by daniel5gh** [comment]
> Hi, I am running into the same issue with the latest released chart.
> 
> I don't see any change/code containing `CSRF_TRUSTED_ORIGINS` either, did this get lost?
> 
> I did add `CSRF_TRUSTED_ORIGINS` to my setup manually and it resolved the issue.
> 
> thanks!

I now changed this to use

```python
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SOCIAL_AUTH_REDIRECT_IS_HTTPS = True
```

instead. As this [seems the intended method](https://github.com/sentry-kubernetes/charts/blob/8.1.2/sentry/templates/configmap-sentry.yaml#L274) and forcing `CSRF_TRUSTED_ORIGINS` could actually open up a security issue.

**Comment by TimShilov** [comment]
> I now changed this to use
> 
> ```python
> SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
> SESSION_COOKIE_SECURE = True
> CSRF_COOKIE_SECURE = True
> SOCIAL_AUTH_REDIRECT_IS_HTTPS = True
> ```
> 
> instead. As this [seems the intended method](https://github.com/sentry-kubernetes/charts/blob/8.1.2/sentry/templates/configmap-sentry.yaml#L274) and forcing `CSRF_TRUSTED_ORIGINS` could actually open up a security issue.

Hi, I just deployed the chart today and I have the same problem. I've configured/uncommented the `SECURE_PROXY_SSL_HEADER`, `SESSION_COOKIE_SECURE`, `CSRF_COOKIE_SECURE` and `SOCIAL_AUTH_REDIRECT_IS_HTTPS` but that didn't solve the problem.
However, adding `CSRF_TRUSTED_ORIGINS = ['sentry.domain.my']` as averagely has worked like a charm. Since you have mentioned that it's a security issue and not a solution, can you please point me on how to solve this properly?
