### ISSUE TITLE
ErrImagePull when deploying the chart (Sentry 20.8.1 not released yet)

### ISSUE THREAD

**Issue by martinraison** [sentry-kubernetes/charts#168]
I'm unable to deploy the current version of the chart because Sentry 20.8.1 has not been released yet. I guess the chart should be using 20.8.0 instead ?

**Comment by Mokto** [comment]
Could you try again with version 5.1.2 of the chart ?

**Comment by martinraison** [comment]
Great, version 5.1.2 is working for me, I was able to upgrade to Sentry 20.8.0. Thanks!
