### ISSUE TITLE
Clickhouse logs should be writing to stdout

### ISSUE THREAD

**Issue by DandyDeveloper** [sentry-kubernetes/charts#170]
It looks like logs for Clickhouse (init and running pods) logs are missing. 

Since we're managing the clickhouse side, this is probably something we have the power to update.

**Comment by Mokto** [comment]
Are you sure ?
I do have logs:

<img width="922" alt="Screenshot 2020-10-07 at 08 10 39" src="https://user-images.githubusercontent.com/5103928/95293904-9f7e1180-0874-11eb-9385-72f3e12c875b.png">
