### ISSUE TITLE
Sentry stops processing new events

### ISSUE THREAD

**Issue by sagor999** [sentry-kubernetes/charts#171]
Hi,

I have upgraded to 5.1.0 chart, and noticed that after X hours sentry will stop processing new events.  
Right before it would stop, this is the last thing that I see in events:
```
HTTPConnectionPool(host='sentry-symbolicator', port=3021): Max retries exceeded with url: /symbolicate?scope=78&timeout=4 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa79c345f50>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```
And there is a whole bunch of those.

But as far as I know symbolicator is not even enabled in this chart, correct? 
I am wondering why it attempts to establish connection to it?
Has anyone seen this? 

Restarting sentry-worker pods helps to get things going again.

**Comment by DandyDeveloper** [comment]
@Mokto Looks like we have the config options here: https://github.com/sentry-kubernetes/charts/blob/d2705c3317da466c70b62ec24c6c0ec11810af04/sentry/templates/configmap-sentry.yaml#L23

But we never actually created or we at some point removed this from the chart?

**Comment by Mokto** [comment]
It was never created and should never be enabled : https://github.com/sentry-kubernetes/charts/blob/d2705c3317da466c70b62ec24c6c0ec11810af04/sentry/values.yaml#

Cf #54.

@sagor999 Have you changed that value ?

**Comment by sagor999** [comment]
@Mokto nope, it is set to `false`

**Comment by DandyDeveloper** [comment]
@Mokto 

It won't matter if someone disables it, it's still references in the config by default. We should probably just wrap the whole thing in an `{{- if ... }}`

https://github.com/sentry-kubernetes/charts/blob/d2705c3317da466c70b62ec24c6c0ec11810af04/sentry/templates/configmap-sentry.yaml#L24

**Comment by Mokto** [comment]
Just did that here, hopefully that will solve the issue.

https://github.com/sentry-kubernetes/charts/pull/173

**Comment by Mokto** [comment]
Could you try again with 5.1.3 ?

@sagor999

**Comment by sagor999** [comment]
@Mokto for what it worth, it has not done this since last week. But I deployed this update and so far so good. I will close this issue now, but if it will happen again, will re-open. 
Thank you!!
