### ISSUE TITLE
Upladed source maps are not visible from sentry ui

### ISSUE THREAD

**Issue by kpbll** [sentry-kubernetes/charts#172]
Sentry was deployed by helm chart 5.0.1 and upgraded to 5.1.0, we have same exceptions(see below) for both versions in sentry-worker's logs
Source maps uploaded by sentry-cli with success status.
But we have no artifacts in release in UI.

exception:
`IOError: [Errno 2] No such file or directory: u'/var/lib/sentry/files/a4/5fe5/b312bc4f8f941d50fe4908bd2f'
16:03:15 [ERROR] celery.app.trace: Task sentry.tasks.assemble.assemble_artifacts[ffccc9b5-2ce2-4022-9dc6-9433f6a9e4f9] raised unexpected: IOError(2, 'No such file or directory') (data={u'internal': False, u'traceback': u'Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 375, in trace_task\n    R = retval = fun(*args, **kwargs)\n  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 632, in __protected_call__\n    return self.run(*args, **kwargs)\n  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/integrations/celery.py", line 171, in _inner\n    reraise(*exc_info)\n  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/integrations/celery.py", line 166, in _inner\n    return f(*args, **kwargs)\n  File "/usr/local/lib/python2.7/site-packages/sentry/tasks/base.py", line 48, in _wrapped\n    result = func(*args, **kwargs)\n  File "/usr/local/lib/python2.7/site-packages/sentry/tasks/assemble.py", line 183, in assemble_artifacts\n    file_type="release.bundle",\n  File "/usr/local/lib/python2.7/site-packages/sentry/tasks/assemble.py", line 343, in assemble_file\n    temp_file = file.assemble_from_file_blob_ids(file_blob_ids, checksum)\n  File "/usr/local/lib/python2.7/site-packages/sentry/models/file.py", line 416, in assemble_from_file_blob_ids\n    for chunk in blob.getfile().chunks():\n  File "/usr/local/lib/python2.7/site-packages/sentry/models/file.py", line 299, in getfile\n    return storage.open(self.path)\n  File "/usr/local/lib/python2.7/site-packages/django/core/files/storage.py", line 38, in open\n    return self._open(name, mode)\n  File "/usr/local/lib/python2.7/site-packages/django/core/files/storage.py", line 300, in _open\n    return File(open(self.path(name), mode))\nIOError: [Errno 2] No such file or directory: u\'/var/lib/sentry/files/a4/5fe5/b312bc4f8f941d50fe4908bd2f\'\n', u'name': 'sentry.tasks.assemble.assemble_artifacts', u'args': '()', u'kwargs': "{'chunks': ['32d97be8574950b3768353308656df31370c6032'], 'checksum': '32d97be8574950b3768353308656df31370c6032', 'version': u'9f46ad35308ea553883e56813f9f0e282cc973b4', 'org_id': 1L}", u'description': u'raised unexpected', u'hostname': u'celery@sentry-worker-977796477-ckpvr', u'id': 'ffccc9b5-2ce2-4022-9dc6-9433f6a9e4f9', u'exc': "IOError(2, 'No such file or directory')"})
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 375, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 632, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/integrations/celery.py", line 171, in _inner
    reraise(*exc_info)
  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/integrations/celery.py", line 166, in _inner
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/tasks/base.py", line 48, in _wrapped
    result = func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/sentry/tasks/assemble.py", line 183, in assemble_artifacts
    file_type="release.bundle",
  File "/usr/local/lib/python2.7/site-packages/sentry/tasks/assemble.py", line 343, in assemble_file
    temp_file = file.assemble_from_file_blob_ids(file_blob_ids, checksum)
  File "/usr/local/lib/python2.7/site-packages/sentry/models/file.py", line 416, in assemble_from_file_blob_ids
    for chunk in blob.getfile().chunks():
  File "/usr/local/lib/python2.7/site-packages/sentry/models/file.py", line 299, in getfile
    return storage.open(self.path)
  File "/usr/local/lib/python2.7/site-packages/django/core/files/storage.py", line 38, in open
    return self._open(name, mode)
  File "/usr/local/lib/python2.7/site-packages/django/core/files/storage.py", line 300, in _open
    return File(open(self.path(name), mode))`

Also there are many warning like this in apps which mount sentry-data:
`15:46:18 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
/usr/local/lib/python2.7/site-packages/cryptography/__init__.py:39: CryptographyDeprecationWarning: Python 2 is no longer supported by the Python core team. Support for it is now deprecated in cryptography, and will be removed in a future release.
  CryptographyDeprecationWarning,
15:46:23 [INFO] sentry.plugins.github: apps-not-configured`

What should I check to try resolve the issue? Thanks!

**Comment by Mokto** [comment]
Can you share your values.yaml file ?
