### ISSUE TITLE
[5.3.0] sentry hooks keep firing indefinetely

### ISSUE THREAD

**Issue by sagor999** [sentry-kubernetes/charts#187]
Hi @Mokto ,

I noticed starting with 5.1.0ish version, that sentry helm hooks would keep on firing, things like snuba-db-init, snuba-db-migrate, snuba-user-create, etc, they complete successfully, and then several minutes later would fire up again, and again.
I have to set `hooks.enabled` to false.
I was wondering if you by any chance know why that might be happening? or how to debug why it keeps firing?
All jobs complete correctly. So hook should have been removed after that, but for some reason it did not. 

Thank you!

**Comment by Mokto** [comment]
Not sure, to be honest. How do you deploy the helm chart ?

- manual cli
- argocd
- other ?

**Comment by sagor999** [comment]
@Mokto I am deploying it using [helm operator](https://github.com/fluxcd/helm-operator) which in turn uses Helm v3 to make deployment. There are no errors or warnings during deploy.

**Comment by sagor999** [comment]
Re-installing helm chart fixed this issue. So I guess something just got borked locally. I will close this issue now.
