### ISSUE TITLE
Disable Kafka

### ISSUE THREAD

**Issue by eloo** [sentry-kubernetes/charts#188]
Hello,

i'm just migrating from the helm/charts repo to this chart and i'm not sure how to disable kafka (or is kafka necessary?) 

When i try to disable kafka using the values like this
```
kafka:
  enabled: false
```

I'm getting an error from the helper because no valid kafka host is set. But i don't use kafka anyway :D

I guess the problem is in the helper template 
```
{{/*
Set Kafka Confluent host
*/}}
{{- define "sentry.kafka.host" -}}
{{- if .Values.kafka.enabled -}}
{{- template "sentry.kafka.fullname" . -}}
{{- else -}}
{{ required "A valid .Values.externalKafka.host is required" .Values.externalKafka.host }}
{{- end -}}
{{- end -}}
```
so when i disable kafka i need to configure kafka.. but i dont want to use it anyway.

Did i miss something

Thanks
eloo

**Comment by J0sh0nat0r** [comment]
It's necessary as Sentry's new event processing architecture depends on it
