### ISSUE TITLE
[sentty] undefined_tables (tag:5.3)

### ISSUE THREAD

**Issue by peppe77** [sentry-kubernetes/charts#192]
k8s 1.18
external redis and postgres

deployed successfully and waited until it was stable. tried to access it and got error below. help is appreciated. thanks

[sentry-web-66578b7f66-jz8kz] 100.124.64.13 - - [07/Oct/2020:05:47:45 +0000] "GET /auth/login/ HTTP/1.0" 500 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15"
[sentry-snuba-api-c6486ffb9-mggqd] 100.124.64.0 - - [07/Oct/2020:05:47:47 +0000] "GET / HTTP/1.1" 200 12113 "-" "kube-probe/1.18"
error: unexpected EOF
[sentry-worker-7779b85bd-mxd67] Traceback (most recent call last):
[sentry-worker-7779b85bd-mxd67]   File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 375, in trace_task
[sentry-worker-7779b85bd-mxd67]     R = retval = fun(*args, **kwargs)
[sentry-worker-7779b85bd-mxd67]   File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 632, in __protected_call__
[sentry-worker-7779b85bd-mxd67]     return self.run(*args, **kwargs)
[sentry-worker-7779b85bd-mxd67]   File "/usr/local/lib/python2.7/site-packages/sentry_sdk/integrations/celery.py", line 171, in _inner
[sentry-worker-7779b85bd-mxd67]     reraise(*exc_info)
[sentry-worker-7779b85bd-mxd67]   File "/usr/local/lib/python2.7/site-packages/sentry_sdk/integrations/celery.py", line 166, in _inner
[sentry-worker-7779b85bd-mxd67]     return f(*args, **kwargs)
[sentry-worker-7779b85bd-mxd67]   File "/usr/local/lib/python2.7/site-packages/sentry/tasks/base.py", line 48, in _wrapped
[sentry-worker-7779b85bd-mxd67]     result = func(*args, **kwargs)
[sentry-worker-7779b85bd-mxd67]   File "/usr/local/lib/python2.7/site-packages/sentry/tasks/options.py", line 29, in sync_options
[sentry-worker-7779b85bd-mxd67]     for option in Option.objects.filter(last_updated__gte=cutoff_dt).iterator():
[sentry-worker-7779b85bd-mxd67]   File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__
[sentry-worker-7779b85bd-mxd67]     results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
[sentry-worker-7779b85bd-mxd67]   File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql
[sentry-worker-7779b85bd-mxd67]     raise original_exception
[sentry-worker-7779b85bd-mxd67] ProgrammingError: UndefinedTable('relation "sentry_option" does not exist\nLINE 1: ...ion"."value", "sentry_option"."last_updated" FROM "sentry_op...\n                                                             ^\n',)
[sentry-worker-7779b85bd-mxd67] SQL: SELECT "sentry_option"."id", "sentry_option"."key", "sentry_option"."value", "sentry_option"."last_updated" FROM "sentry_option" WHERE "sentry_option"."last_updated" >= %s
[sentry-worker-7779b85bd-mxd67] 05:47:50 [ERROR] celery.app.trace: Task sentry.tasks.options.sync_options[e6ec3de2-14e3-444d-8fec-cd7313393a1a] raised unexpected: ProgrammingError(u'UndefinedTable(\'relation "sentry_option" does not exist\\nLINE 1: ...ion"."value", "sentry_option"."last_updated" FROM "sentry_op...\\n                                                             ^\\n\',)\nSQL: SELECT "sentry_option"."id", "sentry_option"."key", "sentry_option"."value", "sentry_option"."last_updated" FROM "sentry_option" WHERE "sentry_option"."last_updated" >= %s',) (data={u'internal': False, u'traceback': u'Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 375, in trace_task\n    R = retval = fun(*args, **kwargs)\n  File "/usr/local/lib/python2.7/site-packages/celery/app/trace.py", line 632, in __protected_call__\n    return self.run(*args, **kwargs)\n  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/integrations/celery.py", line 171, in _inner\n    reraise(*exc_info)\n  File "/usr/local/lib/python2.7/site-packages/sentry_sdk/integrations/celery.py", line 166, in _inner\n    return f(*args, **kwargs)\n  File "/usr/local/lib/python2.7/site-packages/sentry/tasks/base.py", line 48, in _wrapped\n    result = func(*args, **kwargs)\n  File "/usr/local/lib/python2.7/site-packages/sentry/tasks/options.py", line 29, in sync_options\n    for option in Option.objects.filter(last_updated__gte=cutoff_dt).iterator():\n  File "/usr/local/lib/python2.7/site-packages/django/db/models/query.py", line 53, in __iter__\n    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)\n  File "/usr/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 899, in execute_sql\n    raise original_exception\nProgrammingError: UndefinedTable(\'relation "sentry_option" does not exist\\nLINE 1: ...ion"."value", "sentry_option"."last_updated" FROM "sentry_op...\\n                                                             ^\\n\',)\nSQL: SELECT "sentry_option"."id", "sentry_option"."key", "sentry_option"."value", "sentry_option"."last_updated" FROM "sentry_option" WHERE "sentry_option"."last_updated" >= %s\n', u'name': 'sentry.tasks.options.sync_options', u'args': '()', u'kwargs': '{}', u'description': u'raised unexpected', u'hostname': u'celery@sentry-worker-7779b85bd-mxd67', u'id': 'e6ec3de2-14e3-444d-8fec-cd7313393a1a', u'exc': 'ProgrammingError(u\'UndefinedTable(\\\'relation "sentry_option" does not exist\\\\nLINE 1: ...ion"."value", "sentry_option"."last_updated" FROM "sentry_op...\\\\n                                                             ^\\\\n\\\',)\\nSQL: SELECT "sentry_option"."id", "sentry_option"."key", "sentry_option"."value", "sentry_option"."last_updated" FROM "sentry_option" WHERE "sentry_option"."last_updated" >= %s\',)'})

**Comment by peppe77** [comment]
NAME                                                              READY   STATUS      RESTARTS   AGE
sentry-clickhouse-0                                               1/1     Running     0          18m
sentry-clickhouse-1                                               1/1     Running     0          104s
sentry-clickhouse-2                                               1/1     Running     0          18m
sentry-clickhouse-init-chzjb                                      0/1     Completed   0          15m
sentry-clickhouse-replica-0                                       1/1     Running     0          18m
sentry-clickhouse-replica-1                                       1/1     Running     0          103s
sentry-clickhouse-replica-2                                       1/1     Running     0          18m
sentry-clickhouse-tabix-75698686bc-gr4wj                          1/1     Running     0          108s
sentry-cron-976c8bb68-tnwgm                                       1/1     Running     0          109s
sentry-ingest-consumer-5bf7d5594b-9zgvp                           1/1     Running     0          109s
sentry-kafka-0                                                    1/1     Running     2          18m
sentry-kafka-1                                                    1/1     Running     2          18m
sentry-kafka-2                                                    1/1     Running     0          99s
sentry-metrics-bfcd4c66c-4trgh                                    1/1     Running     0          107s
sentry-ng-nginx-ingress-external-controller-645fc669f9-cjf4b      1/1     Running     0          8d
sentry-ng-nginx-ingress-external-controller-645fc669f9-rchn7      1/1     Running     0          7d19h
sentry-ng-nginx-ingress-external-default-backend-569bdb795ndxjd   1/1     Running     0          7d19h
sentry-nginx-58747db8cd-8qnmf                                     1/1     Running     0          108s
sentry-post-process-forward-6cfdbbb7b8-k5j4l                      1/1     Running     1          109s
sentry-sessions-consumer-649f45d7d5-mlkjs                         1/1     Running     1          108s
sentry-snuba-api-c6486ffb9-xp5lc                                  1/1     Running     0          108s
sentry-snuba-consumer-666b75545d-k8bt2                            1/1     Running     0          110s
sentry-snuba-db-init-ncc2q                                        0/1     Completed   0          15m
sentry-snuba-migrate-8jz6j                                        0/1     Completed   0          15m
sentry-snuba-outcomes-consumer-747c46b75f-64w9f                   1/1     Running     2          109s
sentry-snuba-replacer-7d49f78946-mblxq                            1/1     Running     0          110s
sentry-snuba-transactions-consumer-5ff87ffcbf-h2294               1/1     Running     0          108s
sentry-web-66578b7f66-k4ss6                                       1/1     Running     0          109s
sentry-worker-7779b85bd-hl8tb                                     1/1     Running     0          109s
sentry-worker-7779b85bd-jnm74                                     1/1     Running     0          18m
sentry-worker-7779b85bd-mxd67                                     1/1     Running     0          18m
sentry-zookeeper-0                                                1/1     Running     0          18m

-

**Comment by Mokto** [comment]
Could you share the logs of db-init ?
& your values.yaml file

**Comment by peppe77** [comment]
Hi @Mokto , thanks. Here you go (note that i just tried chart/4.2 and had same problem as 5.3). db_init logs is from most recent attempt @ 4.2. Pls let me know what do you suggest. thanks [/Pedro]
[db-init.log](https://github.com/sentry-kubernetes/charts/files/5338563/db-init.log)

**Comment by peppe77** [comment]
had to override resources for kafka as default requested is no good (quick OOM).

**Comment by Mokto** [comment]
You're supposed to have a sentry-db-init job running somewhere, that's the one I need ;) 

Not the snuba one.

It's weird we don't see it in your kubectl get pods command.

**Comment by peppe77** [comment]
@Mokto this is the reason...will see how to overwrite (resources request/limit) used by this (sentry-db-init) job?

  Limits:
      memory:  2Gi
    Requests:
      cpu:        300m
      memory:     2Gi
    Environment:  <none>
    Mounts:
      /etc/sentry from config (ro)
  Volumes:
   config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      sentry-sentry
    Optional:  false
Events:
  Type     Reason        Age                    From            Message
  ----     ------        ----                   ----            -------
  Warning  FailedCreate  3m6s (x49 over 4h51m)  job-controller  (combined from similar events): Error creating: Pod "sentry-db-init-kgzq6" is invalid: spec.containers[0].resources.requests: Invalid value: "300m": must be less than or equal to cpu limit

**Comment by Mokto** [comment]
You must have a namespace default limit value I suppose.

I'll close the issue.

**Comment by peppe77** [comment]
@Mokto ns has base limits though cpu is 250 and request for that job is 300m. Current approach takes ns limit for granted as to be bigger or same as the job. I should be able to overwrite job and set cpu limit in it to 500m. On the other hand, other jobs started ( which means they were requesting 250m or less or setting cpu limit within ). Wouldn't be better to document this as well as set limits within all jobs and allow overwrite via values?

**Comment by peppe77** [comment]
@Mokto let alone, it would be more consistent to set cpu/limit for sentry-db-init as other jobs already have...

Name:           sentry-snuba-db-init
Namespace:      sentry-ng
Selector:       controller-uid=c2b419ad-47d2-47f3-a54b-244a6006d0d2
Labels:         app=sentry
                chart=sentry-4.2.0
                heritage=Helm
                release=sentry
Annotations:    helm.sh/hook: post-install,post-upgrade
                helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
                helm.sh/hook-weight: 3
Parallelism:    1
Completions:    1
Start Time:     Tue, 06 Oct 2020 23:09:53 -0700
Completed At:   Tue, 06 Oct 2020 23:10:02 -0700
Duration:       9s
Pods Statuses:  0 Running / 1 Succeeded / 0 Failed
Pod Template:
  Labels:       app=sentry
                controller-uid=c2b419ad-47d2-47f3-a54b-244a6006d0d2
                job-name=sentry-snuba-db-init
                release=sentry
  Annotations:  checksum/config.yaml: 2aae5796e85550413c25d14a050d66ce8aac129660b225a1223979567196cb09
                checksum/snubaSettingsPy: d5f85a6a8afbc55eebe23801e1a51a0fb4c0428c9a73ef6708d8dc83e079cd49
  Containers:
   snuba-init:
    Image:      getsentry/snuba:882be95ba0d462a29759a49b2e9aad0c1ce111a9
    Port:       <none>
    Host Port:  <none>
    Command:
      /bin/bash
      -ec
      for ((i=0;i<3;i++)); do
        export CLICKHOUSE_HOST=sentry-clickhouse-$i.sentry-clickhouse-headless;
        snuba bootstrap --force;
        export CLICKHOUSE_HOST=sentry-clickhouse-replica-$i.sentry-clickhouse-replica-headless;
        snuba bootstrap --force;
      done
    Limits:
      cpu:     2
      memory:  1Gi
    Requests:
      cpu:     700m
      memory:  1Gi
