### ISSUE TITLE
Please add support regex for ingress by default

### ISSUE THREAD

**Issue by kudodenko** [sentry-kubernetes/charts#194]
When ingress is enabled it return 403 error.
I trying to fix this issue by added nginx.ingress.kubernetes.io/use-regex: "true" annotation and it works.
Please add this annotation as default when ingress is enabled.

**Comment by Mokto** [comment]
Ingress usage is not limited to the nginx ingress controller. That's why it's not activated per default.

But it's a comment, and documented in the README.
