### ISSUE TITLE
[clickhouse] Document that timezone shouldn't be changed (or avoid being able to change it)

### ISSUE THREAD

**Issue by davelosert** [sentry-kubernetes/charts#199]
I was just finally able to fix a bug I was chasing for weeks with this helm chart here.

The Problem: I could not get event details to show up in sentry. Events were written correctly, but viewing them always resulted in `404`s. I just found the hint for the fix [in this official issue](https://github.com/getsentry/sentry/issues/16436):

My Error: I actually set the clickhouse-timezone to `Europe/Berlin`, thinking that would make it show the Events in my correct time. However, this seems to make clickhouse query the data wrong.

Maybe I'd be a good idea to document in the clickhouse chart that the timezone **must** be UTC (or maybe the timezone of the cluster - not sure).

What do you think? (I am happy to send a PR if you aggree)

**Comment by Mokto** [comment]
Yeah, indeed. 
See https://github.com/sentry-kubernetes/charts/pull/82

But the note should be in the sentry readme, not the clickhouse chart. The clickhouse chart could be used for something else.

PR welcomed ;) Thanks!

**Comment by Mokto** [comment]
Fixed in 6.0.0

**Comment by yildizozgur** [comment]
Hi, I have a similar issue like https://github.com/getsentry/sentry/issues/58224 . I have an external Postgre(PG) which has Europe/Berlin Time zone. But all other components are on K8s and use UTC. So I need to set one of them to other. I would prefer to set K8s Sentry components to use Europe/Berlin. But I could not see anyway to do it. In values.yaml file no options are given to change it. What should I do to synch Sentry components with external PG?
Thanks a lot.
