### ISSUE TITLE
Ingress 404 on GKE 1.17.12-gke.500

### ISSUE THREAD

**Issue by jadbaz** [sentry-kubernetes/charts#205]
I ran: `helm install mysentry sentry/sentry --set ingress.enabled=true`
Everything finished successfully and I get the following ingress (different IP of course):
`my-sentry-1   *       1.2.3.4   80      7m35s`

curl this IP returns 404.

I haven't changed any defaults except for enabling ingress. Not quite sure what I did wrong

**Comment by dnlsndr** [comment]
When enabling the ingress, you will also need to pass in some more information which defines the Hostname, TLS, etc.
Have a look at the `/sentry/values.yaml` of this repo, to see what it needs.

**Comment by jadbaz** [comment]
I didn't have an ingress controller
- helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
- helm install ingress-nginx ingress-nginx/ingress-nginx

And now visit the external IP _by hostname_
