### ISSUE TITLE
DSN endpoint changed and no option to go back to previous one

### ISSUE THREAD

**Issue by Leen15** [sentry-kubernetes/charts#208]
We just upgraded the chart to 6.0.0, and all ours DSN endpoints changed from:
`https://<sentry-dsn>@<subdomain>.<domain>.tld`
To:
`https://<sentry-dsn>@o<number>.ingest.<subdomain>.<domain>.<tld>`
We have a wildcard SSL that doesn't support oX.ingest.
We checked that this new option is available only if `organizations:org-subdomains` is set to True.
Unfortunately, there is no way on the chart to set it, because it's forced to true in the configmap:
https://github.com/sentry-kubernetes/charts/blob/945e4c0e44facbeae402fbb5f32a7ce05dd53dfe/sentry/templates/configmap-sentry.yaml#L327

Is there a way for set this option to false without manually change the configmap at every chart update?

Thanks.

**Comment by mthoretton** [comment]
I'm also facing this problem.
Even if we wanted to use the `o<number>.ingest.<subdomain>.<domain>.<tld>` format, how would that work?
Would we have to manually update the sentry ingress to add a new domain any time there is a new organisation? (we use external-dns/ingress-nginx/cert-mananager)
I would also prefer to keep the good old endpoint.
Thanks 😃

**Comment by Mokto** [comment]
I guess we can remove that value entirely ? But it probably means a new major release.

What do you think ?

**Comment by Leen15** [comment]
@Mokto I agree, it should be removed with the ability to set in values file.

**Comment by mthoretton** [comment]
I created https://github.com/sentry-kubernetes/charts/pull/209 which should solve this specific problem wihout introducing any breaking change. At least that would do the job for me 😄

**Comment by mthoretton** [comment]
Thanks a lot for your reactivity. I was able to deploy the new chart version and I can confirm that it has fixed the issue (by setting sentry.features.orgSubdomains to `false`. 🎉
