### ISSUE TITLE
Support .spec.strategy block in sentry-web to update correctly with persistent volumes.

### ISSUE THREAD

**Issue by sklusz** [sentry-kubernetes/charts#214]
When sentry-web is updated with `helm upgrade --install`, the sentry-web deployment spins up another pod, as it's set to a rolling deployment strategy by default.

Two web pods are created - 
```
default       sentry-web-1234                             1/1     Running             0          3d23h
default       sentry-web-1235                             0/1     ContainerCreating   0          4m36s
``` 

The sentry-web deployment strategy:
```
Replicas:               1 desired | 1 updated | 2 total | 1 available | 1 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
```

This leads to a timeout if using a persistent volume in the deployment, as the volume can't be mounted to the new pod while it is mounted to the old one. This is the case in AWS EKS, and I assume the same on other platforms. 

Logs for the new pod - 
```
  Normal   TriggeredScaleUp    4m41s  cluster-autoscaler       pod triggered scale-up: [{eks-... 10->11 (max: 16)}]
  Warning  FailedAttachVolume  30s    attachdetach-controller  Multi-Attach error for volume "pvc-..." Volume is already used by pod(s) sentry-web-1234
```

It is possible to make the persistent volume multi-attach using the cli, but that may cause issues with sentry (two pods writing/reading from the same volume).

This can be more easily resolved by allowing an optional `.spec.strategy` block to change the `.spec.strategy.type` to Recreate, which would bring sentry-web down prior to spinning up a new pod for the deployment. Another option is automatically changing the `.spec.strategy.type` to recreate if `.Values.filestore.filesystem.persistence.enabled`.

The only way to deploy an update while using persistence without these changes is to delete the sentry-web deployment prior to running `helm upgrade --install`.

**Comment by Mokto** [comment]
Fixed in 6.2.1.
You can now change strategy type.
