### ISSUE TITLE
Correct labels/annotations for "asHook" deployments

### ISSUE THREAD

**Issue by james64** [sentry-kubernetes/charts#217]
Hello,

initial installation (`asHook: true`) is going through ok. Upgrades however (`asHook: false`) are not coming through because of Helm error (helm v3.3.4):
```
"Error: UPGRADE FAILED: rendered manifests contain a resource that already exists.
Unable to continue with update: Deployment "sentry-relay" in namespace "infra-sentry" exists and cannot
be imported into the current release: invalid ownership metadata; label validation error: missing key
"app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key
"meta.helm.sh/release-name": must be set to "sentry"; annotation validation error: missing key
"meta.helm.sh/release-namespace": must be set to "infra-sentry"
```

Only way to proceed is to manually add label and annotation in cluster. This is happening for all resources affected by `asHook` parameter:
- sentry-relay
- sentry-snub-outcomes-consumer
- sentry-snuba-replacer
- sentry-sessions-consumer

Other resources are correctly labeled/annotated. Can we add these to hook deployments as well? Or is there any reason why not to?

Thank you for this chart!

**Comment by Mokto** [comment]
Yes, let's add them if necessary. Never got any issue though ;)

PR welcomed!

**Comment by james64** [comment]
I am happy to provide PR for this. I am going to hold it for now. I asked about this on helm side. Let's see what they have to say here.

**Comment by james64** [comment]
Helm guys says what I see is expected. What is still interesting for me is that sometimes I do see the error and sometimes it is ok and I do not need to do any manual edits. I will observe this for a while so I can understand better what is going on.

**Comment by james64** [comment]
When one wants to do some configuration change and switch `asHook` from true to false at the same time that is when described helm issue occurs. Only way how to not have issues with this is to do upgrade with `asHook=false` immediately after initial deploy **without** any changes. On the second run helm adds these annotations automatically. So we do not need to add these labels manually. Maybe include this info to comment above `asHook` value only. Thanks

**Comment by james64** [comment]
Even without any changes to user configuration this has the effect of removing helm hook annotations which is enough to cause helm crash from the beginning. We do not necessarily need to re-open this. Just if you guys have some way around this I would love to hear about it. And I guess you do since you "never got any issue" like this :)

**Comment by paulshannon** [comment]
I am also running into this problem but it appears to be every time I attempt to upgrade.

```
$ helm upgrade --install --namespace sentry -f sentry.values.yml --set asHook=true sentry ./charts/sentry
Release "sentry" does not exist. Installing it now.
NAME: sentry
LAST DEPLOYED: Fri Dec 18 08:29:16 2020
NAMESPACE: sentry
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
* When running upgrades, make sure to give back the `system.secretKey` value.

kubectl -n sentry get configmap sentry-sentry -o json | grep -m1 -Po '(?<=system.secret-key: )[^\\]*'
$ helm upgrade --install --namespace sentry -f sentry.values.yml --set asHook=false sentry ./charts/sentry
Error: UPGRADE FAILED: rendered manifests contain a resource that already exists. Unable to continue with update: Deployment "sentry-relay" in namespace "sentry" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "sentry"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "sentry"
```

Running an otherwise unmodified upgrade with `asHook=False` immediately after deploy also fails
This is using a clean local copy of the December release
