### ISSUE TITLE
Insufficient ingress configuration

### ISSUE THREAD

**Issue by james64** [sentry-kubernetes/charts#218]
Hey,

let's say I want to operate sentry on public domain `sentry.example.com`. Setting `.Values.ingress.hostname` to `sentry.example.com` is not enough since this matches host exactly. In other words UI on `sentry.example.com` would be accessible but project DSN url (usually on something like `o1.ingest.sentry.example.com`) is not since this is not exact match. My setup starting to work when I manually edited ingress and I added second rule with same http paths but host `*.sentry.example.com`.

There may be more ways to fix it but AFAIK all of them requires more http rules. Ingress as written now only supports one rule.

First of all am I missing something or do you agree that this needs to be changed? If so what do you suggest? My first approach would be to simply double the rule and use `*.` prefix for second one but maybe there is a better way...

**Comment by Mokto** [comment]
Hey. You can use that value to disable the DSN subdomains : 
https://github.com/sentry-kubernetes/charts/blob/develop/sentry/values.yaml#L74

**Comment by james64** [comment]
Thanks Mokto, that is new to me and looks interesting. Is there any downside in turning this off? I mean it must provide some benefit if someone bother implementing it. Quick googling yield no documentation. Or relevant link is enough.

**Comment by Mokto** [comment]
Not really, it's been set up like that by Sentry so that they can prioritise between enterprise & classic customers (on event processing), I believe.

**Comment by james64** [comment]
I need to re-open this. We are migrating already existing setup from sentry9-swarm to sentry10-k8s. It's used by multiple projects with DSN addresses already configured at many different places. They of course include subdomains. Disabling dsn subdomains would require migration of all these projects. Is it no-go to support wildcard ingress in this chart?

**Comment by DandyDeveloper** [comment]
I'd also like to question this being on by default. As the ingress rules by default, will not support this and wildcards can be dumbersome during helm templating.

@Mokto What's the justification for this feature being enabled by default?

**Comment by Mokto** [comment]
The only reason for it is not being a breaking change.

I'm up for changing it per default too, but we'll need a new major version.

PR welcomed!

**Comment by Mokto** [comment]
I think we can close this.
