### ISSUE TITLE
socket.gaierror: [Errno -3] Temporary failure in name resolution

### ISSUE THREAD

**Issue by nilpntr** [sentry-kubernetes/charts#221]
Got this error `socket.gaierror: [Errno -3] Temporary failure in name resolution` on the following machines:

- Worker
- Web
- Post-Proces-Forward
- Ingest Consumer

**Comment by DandyDeveloper** [comment]
Looks DNS related, what CNI / DNS are you using in k8s? 

Please give the full context of the error message.,
