### ISSUE TITLE
DSN URL not working

### ISSUE THREAD

**Issue by nilpntr** [sentry-kubernetes/charts#225]
Do I have to add this url to ingress or nginx myself:
`https://${public_key}@o1.ingest.${system_url}/${project_id}`?
Or is it already configured somewhere in the chart(didn't find any config for it)

**Comment by LennardWesterveld** [comment]
I think this is because of my issue as well it's related that there is a feature flag that shouldn't be enabled: https://forum.sentry.io/t/o1-ingest-appears-in-dsn-settings-after-upgrading-from-v9-to-20

**Comment by nilpntr** [comment]
Yes that fixed it for me, already saw your issue but forgot to close this comment :)
