### ISSUE TITLE
Feature organizations:org-subdomains should be disabled for on prem instances.

### ISSUE THREAD

**Issue by LennardWesterveld** [sentry-kubernetes/charts#226]
Hi,

I was having weird issues with the DSN were "01.ingest" appeared.
@untitaker said on the forum that it's because the feature "organizations:org-subdomains" was enabled and seems that it is in the default config. Maybe it shouldn't be enabled in sentry. But it worked for me by disabling it.

See also the forum topic:
https://forum.sentry.io/t/o1-ingest-appears-in-dsn-settings-after-upgrading-from-v9-to-20

**Comment by JustDoItSascha** [comment]
Hey, I installed sentry a few days ago for the first time and I have the same problem. Sentry is not usable at the moment? Disabling organizations:org-subdomains did not help either.

Are there any workarounds?

**Comment by untitaker** [comment]
@JustDoItSascha if disabling this featureflag does not solve it you either don't have the same issue or you did not restart your server after changing the config.

**Comment by JustDoItSascha** [comment]
I think the configmap got overwritten after restarting the server. But I upgraded to 7.2.0 chart und set the sentry.orgSubdomains to false. I was wondering why this domain is set to true on default in the first place?

And I was wondering why this setting is not documented?

**Comment by Mokto** [comment]
Yeah, we should "disable" that per default, I'll do it before the next major release!

**Comment by Mokto** [comment]
Fixed with 8.0.0
