### ISSUE TITLE
django.security.csrf error persists when using ingress

### ISSUE THREAD

**Issue by Yomanz** [sentry-kubernetes/charts#228]
I noticed there was a fix for nginx, but if `nginx.enabled` is `false` and `ingress.enabled` is `true` then this fix isn't applied.
Fix: https://github.com/sentry-kubernetes/charts/commit/a680856c0208f4df626e05163f754442f59fca10

Error:
```
10.42.0.0 - - [04/Nov/2020:13:59:03 +0000] "POST /api/2/store/ HTTP/1.1" 403 5558 "-" "-"

13:59:03 [WARNING] django.security.csrf: Forbidden (Referer checking failed - no Referer.): /api/2/store/ (status_code=403 request=<WSGIRequest: POST u'/api/2/store/'>)
```

I tried adding this to the ingress with no avail.
```
nginx.org/server-snippets: |
      proxy_redirect off;
      proxy_set_header Host $host;
```

**Comment by SajoLuo** [comment]
Same problem.Have you solved this problem?

**Comment by Yomanz** [comment]
> 
> 
> Same problem. Have you solved this problem?

Sadly not, I'm probably going to have to run an outdated version or try and fix it myself.

**Comment by SajoLuo** [comment]
I use nginx to bypass this problem, at least sentry can be used temporarily

**Comment by Yomanz** [comment]
> 
> 
> I use nginx to bypass this problem, at least sentry can be used temporarily

Not sure what you mean, do you mean the nginx that deploys automatically with sentry?

**Comment by dis-sid** [comment]
Hello,
If you disabled nginx it's because you have your own nginx ingress controller deployed right ? Then I guess you could use [annotations](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations) to reproduce the fix for your own nginx server.

**Comment by easayliu** [comment]
I get the same program. you should add nginx ingress annotions live:
`    nginx.ingress.kubernetes.io/server-snippet: |-
      proxy_redirect off;
      proxy_set_header Host $host;
    nginx.ingress.kubernetes.io/use-regex: "true"`
