### ISSUE TITLE
Reliance on deprecated RabbitMQ and Postgres subcharts

### ISSUE THREAD

**Issue by OvervCW** [sentry-kubernetes/charts#233]
The chart currently relies on the `stable/rabbitmq-ha` and `stable/postgres` despite the `stable` repository *and* the charts themselves being deprecated. Interestingly, the redis & kafka *do* come from bitnami.

Is there any reason not to switch to the bitnami alternatives for RabbitMQ and PostgreSQL as well?

**Comment by Mokto** [comment]
No specific reason apart from time needed to make the move.

PR welcomed ;)

**Comment by asummers** [comment]
This can be closed, I believe.

**Comment by Mokto** [comment]
Yes, thanks!
