### ISSUE TITLE
Question: raise replicas count

### ISSUE THREAD

**Issue by Antiarchitect** [sentry-kubernetes/charts#243]
Is it actually safe to raise replicas count for all sentry components which are deployments (except cron I suppose)?

**Comment by Mokto** [comment]
Yes it is! As long as you don't use a PVC with RWO

**Comment by Antiarchitect** [comment]
@Mokto For clarification. I'm interested in:
```
ingest-consumer
post-process-forward
relay
sessions-consumer
snuba-api
snuba-consumer
snuba-outcomes-consumer
snuba-replacer
snuba-transactions-consumer
symbolicator-api
```

And I mean not only shared filesystem issue, but there are some services that meant to be run as a single instance for consistency reasons. E.g. Thanos Compactor (still deployment in their chart - but there is a warning in their docs)

**Comment by Antiarchitect** [comment]
BTW. Cannot login into tabix ui. Should I perform some actions on this?

**Comment by Mokto** [comment]
Yep, I really believe you can scale those up

**Comment by Antiarchitect** [comment]
Thank you!
