### ISSUE TITLE
November Release 20.11.1

### ISSUE THREAD

**Issue by simonslama** [sentry-kubernetes/charts#256]
Hi there, we are currently moving our sentry from the "on-premise" version that is running on version 20.11.1 to sentry-kubernetes. 

When are you planning to include the 20.11 into your project? Are you planning to update the readme.md with some update notes for the current version?

Thank you for your assistance and  best regards,

Simon

**Comment by Mokto** [comment]
We have an ongoing PR already but it doesn't work properly. And I don't have time to fix it right now.

https://github.com/sentry-kubernetes/charts/pull/245

**Comment by Mokto** [comment]
The december release is now available ;)
