### ISSUE TITLE
System configuration issue banner after install (Sentry 20.12.1)

### ISSUE THREAD

**Issue by tw1nk** [sentry-kubernetes/charts#269]
After installing sentry the top of the screen has a banner with the text "There is 1 issue with your system configuration".

I installed this over an existing database from Sentry 9.1.2 and it seems the database migration worked as I can see all old issues. It also seems to accept new issues when I test it from an application. 

I've looked through the logs and the only thing I can find that might be related is: 
"2020-12-22T12:40:36Z [relay_server::actors::events] ERROR: project state for key e8b19d80b63a4a19a9587b3d72bc16c9 is missing key id"

It seems the log line is generated from here: https://github.com/getsentry/relay/blob/e2b777eef83970799da0d2fc456e296851a56825/relay-server/src/actors/events.rs#L948

Do I have to manually generate public keys and in that case where should I put the public keys in the values.yaml file?

**Comment by tw1nk** [comment]
~For some reason when I set `sentry.cleanup.enabled: false` I don't get the error banner.~
My login token didn't have admin access so I couldn't see the error.

**Comment by BYK** [comment]
>After installing sentry the top of the screen has a banner with the text "There is 1 issue with your system configuration".

If you are using Sentry 20.12.1, this is very likely to be a false alert and will be fixed in future releases. If you had GitHub integrations though, you may need to move some settings over to `config.yml` file. You can see which settings are causing this warning from Sentry web logs.

**Comment by tw1nk** [comment]
Yes. it's the Sentry 20.12.1 Release. We don't use GitHub integrations. 
I can't find anything in the sentry web logs that indicates why I get the banner, so I guess it's a false alert then. 

Thanks for the info.

**Comment by gboor** [comment]
I just ran into this as well on an upgrade. I performed a complete purge and reinstall of Sentry, so only the old database remains (and was upgraded).

In the logs of sentry-web I do see this as the very first entry;

```
E 2020-12-29T11:04:30.925147094Z /usr/local/lib/python3.6/site-packages/sentry/runner/initializer.py:189: DeprecatedSettingWarning: The EMAIL_USE_SSL setting is deprecated. Please use SENTRY_OPTIONS['mail.use-ssl'] instead.
 
E 2020-12-29T11:04:30.925220583Z   warnings.warn(DeprecatedSettingWarning(options_mapper[k], "SENTRY_OPTIONS['%s']" % k))
 ```

Not sure if that is related, or how to get rid of it, since I didn't manually configure anything...

**Comment by zifeo** [comment]
@gboor Also facing that, looks like this is indeed issue based on https://github.com/getsentry/onpremise/issues/718 similar case.

**Comment by BYK** [comment]
@gboor yeah that's the false alert that we've fixed in subsequent versions. This issue can be closed as the fine folks here cannot do anything about it and it is already fixed :)

**Comment by Mokto** [comment]
Ah, indeed, thanks!
