### ISSUE TITLE
Upgrade from 9.1.2 to latest - db-init-job keeps complaining about Kafka being unreachable and does nothing

### ISSUE THREAD

**Issue by gboor** [sentry-kubernetes/charts#275]
I am trying to use this chart to upgrade from Sentry 9.1.2 to the most recent. I only kept the database of the old install, so in theory it should work if the migration work - the rest is a fresh install.

The db-init-job does not complete and continuously spits stuff like this into the logs;

```
%5|1609706659.134|REQTMOUT|rdkafka#producer-1| [thrd:sentry-kafka-0.sentry-kafka-headless.sentry.svc.cluster.local:9]: sentry-kafka-0.sentry-kafka-headless.sentry.svc.cluster.local:9092/0: Timed out ProduceRequest in flight (after 1070ms, timeout #0)
...
%3|1609706659.134|FAIL|rdkafka#producer-1| [thrd:sentry-kafka-0.sentry-kafka-headless.sentry.svc.cluster.local:9]: sentry-kafka-0.sentry-kafka-headless.sentry.svc.cluster.local:9092/0: 6 request(s) timed out: disconnect (after 240155ms in state UP)
```

I have let it run for several hours now with no change - just that over and over again. It does not appear anything is actually being migrated.

Kafka is up and running according to K8S and the logs look normal. Sentry-snuba-consumer is crashlooping, it complains about key errors and then shuts down. Not sure if that's related.

Can anyone point me in the right direction here?

**Comment by DandyDeveloper** [comment]
Sounds like your Kafka consumer groups are likely out of whack and need reset. Easy fix there would be to delete the PVC and pods, to clear up Kafka, then try to run the init job again. 

Kafka is a bit of a dark horse in terms of "health". It may look healthy, but consumer / client level issues can be pretty common.

**Comment by gboor** [comment]
I did just that and it indeed resolved... Not good that Kafka is so opaque. I also don't understand why Sentry uses Kafka AND RabbitMQ AND Redis - this whole thing seems very overengineered to me compared to 9.1.2 - but that's a matter for the Sentry team.

Thanks for the pointer!

**Comment by DandyDeveloper** [comment]
Wait till you find out how inefficient Django is ;)
