### ISSUE TITLE
when i upload  sourcemap,something is error.

### ISSUE THREAD

**Issue by 291723286** [sentry-kubernetes/charts#277]
sentry-relay:

2021-01-05T07:09:23Z [relay_server::actors::events] ERROR: project state for key bcbeb26f7dab43b5abf6e8deb980d3d3 is missing key id
2021-01-05T07:09:24Z [relay_server::actors::events] ERROR: project state for key bcbeb26f7dab43b5abf6e8deb980d3d3 is missing key id
2021-01-05T07:09:25Z [relay_server::actors::events] ERROR: project state for key bcbeb26f7dab43b5abf6e8deb980d3d3 is missing key id

sentry-worker:
07:02:22 [ERROR] celery.app.trace: Task sentry.tasks.assemble.assemble_artifacts[857ba565-2287-478a-a9c2-1fe16be21d08] raised unexpected: FileNotFoundError(2, 'No such file or directory') (data={'hostname': 'sentry-worker-78dc75c5dc-x2zhm', 'id': '857ba565-2287-478a-a9c2-1fe16be21d08', 'name': 'sentry.tasks.assemble.assemble_artifacts', 'exc': "FileNotFoundError(2, 'No such file or directory')", 'traceback': 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 412, in trace_task\n    R = retval = fun(*args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 704, in __protected_call__\n    return self.run(*args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/sentry_sdk/integrations/celery.py", line 197, in _inner\n    reraise(*exc_info)\n  File "/usr/local/lib/python3.6/site-packages/sentry_sdk/_compat.py", line 54, in reraise\n    raise value\n  File "/usr/local/lib/python3.6/site-packages/sentry_sdk/integrations/celery.py", line 192, in _inner\n    return f(*args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/sentry/tasks/base.py", line 48, in _wrapped\n    result = func(*args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/sentry/tasks/assemble.py", line 188, in assemble_artifacts\n    file_type="release.bundle",\n  File "/usr/local/lib/python3.6/site-packages/sentry/tasks/assemble.py", line 348, in assemble_file\n    temp_file = file.assemble_from_file_blob_ids(file_blob_ids, checksum)\n  File "/usr/local/lib/python3.6/site-packages/sentry/models/file.py", line 426, in assemble_from_file_blob_ids\n    for chunk in blob.getfile().chunks():\n  File "/usr/local/lib/python3.6/site-packages/sentry/models/file.py", line 299, in getfile\n    return storage.open(self.path)\n  File "/usr/local/lib/python3.6/site-packages/django/core/files/storage.py", line 38, in open\n    return self._open(name, mode)\n  File "/usr/local/lib/python3.6/site-packages/django/core/fil
es/storage.py", line 300, in _open\n    return File(open(self.path(name), mode))\nFileNotFoundError: [Errno 2] No such file or directory: \'/var/lib/sentry/files/d8/7ab6/faee564f2fbcb8df8fcbe11f2f\'\n', 'args': '()', 'kwargs': "{'org_id': 1, 'version': '2021-01-05 15:01:38', 'checksum': '0c7f705163010e77267f381adbd7131e7461b20c', 'chunks': ['0c7f705163010e77267f381adbd7131e7461b20c']}", 'description': 'raised unexpected', 'internal': False})
07:03:47 [WARNING] sentry.tasks.release_registry: Release registry URL is not specified, skipping the task.
07:08:47 [WARNING] sentry.tasks.release_registry: Release registry URL is not specified, skipping the task.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry_sdk/integrations/celery.py", line 197, in _inner
    reraise(*exc_info)
  File "/usr/local/lib/python3.6/site-packages/sentry_sdk/_compat.py", line 54, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/sentry_sdk/integrations/celery.py", line 192, in _inner
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/tasks/base.py", line 48, in _wrapped
    result = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/tasks/assemble.py", line 188, in assemble_artifacts
    file_type="release.bundle",
  File "/usr/local/lib/python3.6/site-packages/sentry/tasks/assemble.py", line 348, in assemble_file
    temp_file = file.assemble_from_file_blob_ids(file_blob_ids, checksum)
  File "/usr/local/lib/python3.6/site-packages/sentry/models/file.py", line 426, in assemble_from_file_blob_ids
    for chunk in blob.getfile().chunks():
  File "/usr/local/lib/python3.6/site-packages/sentry/models/file.py", line 299, in getfile
    return storage.open(self.path)
  File "/usr/local/lib/python3.6/site-packages/django/core/files/storage.py", line 38, in open
    return self._open(name, mode)
  File "/usr/local/lib/python3.6/site-packages/django/core/files/storage.py", line 300, in _open
    return File(open(self.path(name), mode))
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/sentry/files/58/a738/c28ca548e8b8a8fc3f446c9481'
07:09:28 [ERROR] celery.app.trace: Task sentry.tasks.assemble.assemble_artifacts[d0b2ca48-18a1-4cf6-8835-6d4b805f34b6] raised unexpected: FileNotFoundError(2, 'No such file or directory') (data={'hostname': 'sentry-worker-78dc75c5dc-x2zhm', 'id': 'd0b2ca48-18a1-4cf6-8835-6d4b805f34b6', 'name': 'sentry.tasks.assemble.assemble_artifacts', 'exc': "FileNotFoundError(2, 'No such file or directory')", 'traceback': 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 412, in trace_task\n    R = retval = fun(*args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/celery/app/trace.py", line 704, in __protected_call__\n    return self.run(*args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/sentry_sdk/integrations/celery.py", line 197, in _inner\n    reraise(*exc_info)\n  File "/usr/local/lib/python3.6/site-packages/sentry_sdk/_compat.py", line 54, in reraise\n    raise value\n  File "/usr/local/lib/python3.6/site-packages/sentry_sdk/integrations/celery.py", line 192, in _inner\n    return f(*args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/sentry/tasks/base.py", line 48, in _wrapped\n    result = func(*args, **kwargs)\n  File "/usr/local/lib/python3.6/site-packages/sentry/tasks/assemble.py", line 188, in assemble_artifacts\n    file_type="release.bundle",\n  File "/usr/local/lib/python3.6/site-packages/sentry/tasks/assemble.py", line 348, in assemble_file\n    temp_file = file.assemble_from_file_blob_ids(file_blob_ids, checksum)\n  File "/usr/local/lib/python3.6/site-packages/sentry/models/file.py", line 426, in assemble_from_file_blob_ids\n    for chunk in blob.getfile().chunks():\n  File "/usr/local/lib/python3.6/site-packages/sentry/models/file.py", line 299, in getfile\n    return storage.open(self.path)\n  File "/usr/local/lib/python3.6/site-packages/django/core/files/storage.py", line 38, in open\n    return self._open(name, mode)\n  File "/usr/local/lib/python3.6/site-packages/django/core/fil
es/storage.py", line 300, in _open\n    return File(open(self.path(name), mode))\nFileNotFoundError: [Errno 2] No such file or directory: \'/var/lib/sentry/files/58/a738/c28ca548e8b8a8fc3f446c9481\'\n', 'args': '()', 'kwargs': "{'org_id': 1, 'version': '2021-01-05 15:08:45', 'checksum': '1e211fc977b2af8a618f7635c2b7c448b2e3b8b1', 'chunks': ['1e211fc977b2af8a618f7635c2b7c448b2e3b8b1']}", 'description': 'raised unexpected', 'internal': False})
07:13:47 [INFO] sentry.tasks.update_user_reports: update_user_reports.records_updated (reports_to_update=0 reports_with_event=0 updated_reports=0)
07:13:47 [WARNING] sentry.tasks.release_registry: Release registry URL is not specified, skipping the task.
07:18:47 [WARNING] sentry.tasks.release_registry: Release registry URL is not specified, skipping the task.
07:23:47 [WARNING] sentry.tasks.release_registry: Release registry URL is not specified, skipping the task.
07:28:47 [INFO] sentry.tasks.update_user_reports: update_user_reports.records_updated (reports_to_update=0 reports_with_event=0 updated_reports=0)
07:28:47 [WARNING] sentry.tasks.release_registry: Release registry URL is not specified, skipping the task.
07:33:47 [WARNING] sentry.tasks.release_registry: Release registry URL is not specified, skipping the task.
07:38:47 [WARNING] sentry.tasks.release_registry: Release registry URL is not specified, skipping the task.

**Comment by Mokto** [comment]
Are you using persistentWorkers ?

**Comment by Mokto** [comment]
I'll close, please reopen if needed.
