### ISSUE TITLE
PVC does not get mounted

### ISSUE THREAD

**Issue by i5okie** [sentry-kubernetes/charts#28]
There is a discrepancy between pvc and deployment templates:
claimName in deployment is set to sentry.fullname https://github.com/sentry-kubernetes/charts/blob/develop/sentry/templates/deployment-sentry-web.yaml#L106

but name of pvc in template is sentry-data https://github.com/sentry-kubernetes/charts/blob/develop/sentry/templates/pvc.yaml#L5

So I can't install with persistence enabled, or without creating a PVC manually.

**Comment by Mokto** [comment]
Thanks ! I fixed it in 0.9.4
