### ISSUE TITLE
Alternative to Sentry in AWS CloudFormation

### ISSUE THREAD

**Issue by mariusmitrofan** [sentry-kubernetes/charts#281]
Hi guys,

If anyone else is interested, I've written an alternative to this stack in CloudFormation which is deployed via AWS ECS (through either SPOT and ON-DEMAND Fargate containers) and supports all relevant micro-services.

It has been battle-tested alongside Performance Monitoring on a platform with 5 different environments which generates on average about 5k events per hour.

Link = https://github.com/Rungutan/sentry-performance-monitoring

Disclaimer: Yes, I am the one who wrote it.

Cheers!

**Comment by DandyDeveloper** [comment]
@Mokto We good with this?

**Comment by Mokto** [comment]
I don't have anything against sharing a project that could potentially help people installing Sentry in a different way.

What I really don't like is seeing you making advertisement for your company.

**Comment by Mokto** [comment]
I just removed your company link from your post.
