### ISSUE TITLE
how allocate more heap to sentry-web?

### ISSUE THREAD

**Issue by peppe77** [sentry-kubernetes/charts#289]
went through readme as well as values file and did not find how to increase sentry web heap size. any help is appreciated.

**Comment by ebuildy** [comment]
I believe sentry is written in Python.

You can set container resources by using ``sentry.web.resources`` field:

https://github.com/sentry-kubernetes/charts/blob/develop/sentry/templates/deployment-sentry-web.yaml#L117

**Comment by Mokto** [comment]
Yes, indeed.
