### ISSUE TITLE
Chart version 8.2.0 not available in repository

### ISSUE THREAD

**Issue by Fgruntjes** [sentry-kubernetes/charts#295]
The chart version 8.2.0 is not available in the repository https://sentry-kubernetes.github.io/charts/.

Am I missing something? Thnx!

**Comment by Mokto** [comment]
I'll deploy 9.0.0 in a second

**Comment by Mokto** [comment]
9.0.0 has been deployed successfully! ;)

**Comment by Fgruntjes** [comment]
Thats great thank you very much!
