### ISSUE TITLE
Stuck on sentry-db-init with no logs

### ISSUE THREAD

**Issue by switz** [sentry-kubernetes/charts#31]
Made it pretty far, but getting stuck here. Just stays pending forever with no logs:

```
sentry-db-init-j56m6                0/1     Pending     0          4m19s
snuba-db-init-mkzgt                 0/1     Completed   0          4m49s
snuba-migrate-4tm7d                 0/1     Completed   0          4m37s
```

```client.go:467: [debug] Add/Modify event for snuba-migrate: MODIFIED
client.go:234: [debug] Starting delete for "sentry-db-init" Job
client.go:98: [debug] creating 1 resource(s)
client.go:439: [debug] Watching for changes to Job sentry-db-init with timeout of 20m0s
client.go:467: [debug] Add/Modify event for sentry-db-init: ADDED
client.go:506: [debug] sentry-db-init: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
```

I'm running bare-metal on digital ocean, any ideas?

**Comment by Mokto** [comment]
No idea to be honest. Have you put enough resources on it ? I think it's quite resources consuming.
Are you sure it can connect to postgres?

**Comment by DandyDeveloper** [comment]
@switz Do a describe on the resource, it'll give more information:

`kubectl describe pod sentry-db-init-j56m6`

**Comment by switz** [comment]
Ah! Great call -- I'm still fairly new to k8s so I wasn't aware of all of the introspection tools.

Looks like the pod doesn't have enough memory:

```
Name:           sentry-db-init-j56m6
Namespace:      prod
Priority:       0
Node:           <none>
Labels:         app=sentry
                controller-uid=b4ee48a5-f255-4959-a07b-d09386186e9a
                job-name=sentry-db-init
                release=sentry-1584700073
Annotations:    checksum/configmap.yaml: 0edc2c7ac926402e71ba8dcdb229caafda6a7c7d7bfdadd948cec169dbf9c332
Status:         Pending
IP:             
Controlled By:  Job/sentry-db-init
Containers:
  db-init-job:
    Image:      getsentry/sentry:10.0.0
    Port:       <none>
    Host Port:  <none>
    Command:
      sentry
      upgrade
      --noinput
    Limits:
      memory:  2Gi
    Requests:
      cpu:        300m
      memory:     2Gi
    Environment:  <none>
    Mounts:
      /etc/sentry from config (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-6zqqk (ro)
Conditions:
  Type           Status
  PodScheduled   False 
Volumes:
  config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      sentry
    Optional:  false
  default-token-6zqqk:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-6zqqk
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason            Age        From               Message
  ----     ------            ----       ----               -------
  Warning  FailedScheduling  <unknown>  default-scheduler  0/2 nodes are available: 1 Insufficient memory, 1 node(s) had taints that the pod didn't tolerate.

```

That said, the machine has **plenty** of resources. A few dozen GB free of memory and more than enough spare CPU. Any idea how I can best bump the pods' resources up?

**Comment by DandyDeveloper** [comment]
Double check all your nodes. There's a hard-coded 2gb requirement for that init pod. Definitely the scheduler is unable to assign it to a node because your nodes don't have sufficient memory.

Best way to check is to do the same describe command on the nodes in your cluster, that'll break down how much memory and where that memory is going.

**Comment by switz** [comment]
Ah, I am truly sorry for my lack of knowledge. My worker node was full and my master node had plenty of space, but it was "tainted". After _untainting_ it (is that right?) I was able to deploy that db-init to my master node. Cheers and thanks so much for walking me through this. Apologies for wasting your time.

I still don't have it fully running, but I hopefully can figure it out from here. Much obliged!
