### ISSUE TITLE
Error: failed post-install: timed out waiting for the condition

### ISSUE THREAD

**Issue by manuschillerdev** [sentry-kubernetes/charts#319]
Thanks for creating and maintaining the charts for sentry.
I tried to install sentry locally (minikube) to check its resource usage before deploying it to our cluster.

What I tried:
* set up a fresh minikube cluster: `minikube start --vm=true --cpus=4 --memory=8192`
* `git clone git@github.com:sentry-kubernetes/charts.git`
* `cd charts/sentry`
* `helm install -f values.yaml sentry-on-prem .`

Result:
`Error: failed post-install: timed out waiting for the condition`

Unfortunately, it does not output any more debug information and I don't know, how to debug this any further.

Thanks in advance for any hint in the right direction :)

**Comment by manuschillerdev** [comment]
It seems to be a problem with `rabbitmq`

```
│ 2021-02-28 18:13:01.838 [warning] <0.269.0> Error while waiting for Mnesia tables: {timeout_waiting_for_tables,['rabbit@sentry-on-premise-rabbitmq-2.sentry-on-premise-rabbitmq-headless.default.svc.cluster.local','rabbit@sentry-on-prem │
```

<img width="1902" alt="Screen Shot 2021-02-28 at 19 14 14" src="https://user-images.githubusercontent.com/56154253/109428865-351f6680-79f9-11eb-9036-9e5e578a8c80.png">

**Comment by manuschillerdev** [comment]
I got it to work. 🎉 
Leaving this here, in case it helps someone.  

**Two points remain unclear to me:**
1. I could not get it to work with rabbitmq enabled at all :/ 
2. Why do I need to run `helm upgrade sentry-on-premise . --set asHook=false`, in order to access the GUI? 

An easy Getting Started Wiki would be awesome. Let me know, if I can help with it.

**Solution:**

`values.yaml`
```diff
 clickhouse:
     configmap:
       remote_servers:
-        internal_replication: true
+        internal_replication: false
###
 postgresql:
+  postgresqlPassword: postgres
   replication:
+    password: postgres
###
rabbitmq:
-  enabled: true
+  enabled: false
```

```bash
minikube delete
minikube start --vm=true --cpus=4 --memory=8192
helm install -f values.yaml sentry .
```

then I waited until all deployments were running (took around 6 minutes on my machine), and upgraded the deployment via
```
helm upgrade sentry-on-premise . --set asHook=false
```

after that, I could kubectl port-forward the `sentry-web` service to `localhost:9000` and access the GUI via my browser:
```bash
kubectl port-forward service/sentry-web 9000:9000
```

**Comment by dledanseur** [comment]
It seems the forceBoot option is misplaced in the rabbitmq options.

Adding the following in the chart's values.yml should do the trick:

```yaml
    rabbitmq:
      clustering:
        forceBoot: true
``` 

EDIT: corrected with this PR: https://github.com/sentry-kubernetes/charts/pull/320

**Comment by Mokto** [comment]
Version 10.0.0 should fix this.
