### ISSUE TITLE
Revert separation of the database / Readd database dependencies.

### ISSUE THREAD

**Issue by DandyDeveloper** [sentry-kubernetes/charts#32]
I'll undertake this in a local fork for the time being, but I really think this chart should offer a direct upgrade path if it is replacing the official stable repository. 

In my case, we'd like to go from Sentry 9 -> Sentry 10, but at present, out of the box, this chart does not offer that. I'll be making updates to support this. 

**Updating this last statement: It's a helm3 chart. Deps exist. Egg on face!**

**Comment by Mokto** [comment]
:)

But it is still true that we don't offer a migration path. I had a lot of troubles migrating the data from v9 to v10, so I personnally made the decision to restart from scratch.

**Comment by DandyDeveloper** [comment]
@Mokto I am in the process of trying to find a nice upgrade path, it won't be so painful if I can figure out a few things.

**Comment by DandyDeveloper** [comment]
@Mokto https://github.com/sentry-kubernetes/charts/pull/33

Mostly done.

**Comment by DandyDeveloper** [comment]
@Mokto Run out of time today. I'll finish off the upgrade path tomorrow, hopefully. If given the time.

**Comment by DandyDeveloper** [comment]
@Mokto You got a nice way to communicate more easily? I suspect I'll be adding more to the repo as I go along.

Thanks for the merge!

**Comment by Mokto** [comment]
Not sure, to be honest! Do you have Telegram?

Or Whatsapp, Slack (I have one for another [Github project](https://github.com/komakio/app)), whatever.

**Comment by DandyDeveloper** [comment]
@Mokto Slack would be great for me, can you drop me the credentials or an invite to aaron.layfield@gmail.com? I'll close this issue for now as we're all good.
