### ISSUE TITLE
Any changes for web/worker/cron infras?

### ISSUE THREAD

**Issue by rgaoistheone** [sentry-kubernetes/charts#330]
Hey guys, 
It's been a while since I integrate this sentry cluster to our dev environment, great job guys. However we also observe some issues along the way , the very pressing one is (correct me if I'm wrong) : the sentry web/workeer/ingest consumer/post-process are sharing the same persistent storage which in our case is ebs backend. Now the problem is , the ebs backend is sharing within the availability zones and can't be mounted on different nodes so we end up running web/workeer/ingest consumer/post-process pods on the same node.
So just curious is there any updates about this parts that we can really split those pods on different nodes in different AZs ? Or there is other best practices for the backend storage plan.

**Comment by Mokto** [comment]
Hi,

I would really recommend not using a volume for Sentry data. Even if you make it work on different AZs, the loading time of the containers increases a lot the more data you have.

You can use S3 instead.

**Comment by rgaoistheone** [comment]
Thanks, I'll try S3 instead.
