### ISSUE TITLE
Changing domain name / Multiple domains

### ISSUE THREAD

**Issue by sr258** [sentry-kubernetes/charts#351]
We're migrating sentry from a VM based installation into one in a Kubernetes cluster. We don't need to migrate data but we don't want a huge outtime as well. So we are using a new domain name for the Kubernetes installation. 

Current setup:
```
oldsentry.example.com --> X.X.X.X (VM)
newsentry.example.com --> Y.Y.Y.Y (Kubernetes)
```

We now want to migrate by changing the IP address in the DNS record of the old domain:
```
oldsentry.example.com --> Y.Y.Y.Y (Kubernetes)
newsentry.example.com --> Y.Y.Y.Y (Kubernetes)
```

I know how to add a second ingress to Kubernetes to accept requests for the new domain, but I'm a bit worried that Sentry won't be happy about getting requests to a different domain from the one configured during initial setup. Will this work?

Once the transition is complete, we'd like to stop using newsentry.example.com and only use oldsentry.example.com. This means we must change the hostname in Sentry. I've found in https://forum.sentry.io/t/how-to-configure-root-url/3404/3 how to change the domain in a traditional VM based installation, but this obviously won't work for Helm. Can I simply change the domain name in the Helmchart and ugprade the chart?

**Comment by Mokto** [comment]
I think it should work yes!

For your use case you could also change your /etc/hosts file to only use the new sentry on your computer.

**Comment by sr258** [comment]
Thanks for your answer! The sentry client is part of a desktop app, so we have to roll out an update to it to change the domain.
