### ISSUE TITLE
Cleanup job options not supported in 21.4.0

### ISSUE THREAD

**Issue by zifeo** [sentry-kubernetes/charts#362]
https://github.com/sentry-kubernetes/charts/commit/84c56ac5417c94a15ec53374b63fe56ab5e9b9a2#diff-5cd2be4801110251b39d66ba836b7a25350271b116c6d82d30c9c64fcf307528R56-R57 does not look to be supported in 21.4.0 (latest release) https://github.com/getsentry/sentry/blob/21.4.0/src/sentry/runner/commands/cleanup.py#L94-L117.

**Comment by Mokto** [comment]
Should be fixed in 21.4.2
