### ISSUE TITLE
Upgrading from 10.1.0 to 11.2.0: post-upgrade hooks failed: timed out waiting for the condition

### ISSUE THREAD

**Issue by sagor999** [sentry-kubernetes/charts#379]
Hi @Mokto
I did upgrade from 10.1.0 to 11.2.0, and it seems like everything rolled out just fine and sentry is working, but helm upgrade did fail with error: `Upgrade "sentry" failed: post-upgrade hooks failed: timed out waiting for the condition`

I noticed that `snuba-db-init` job was still running. It took about 18 minutes for it to complete, but I think default helm timeout is about 5 min. 

After it finished running, I re-run upgrade and it finished running the other jobs and upgrade was finally completed.

Just wanted to post it here in case if someone else will encounter this issue.

Also, is there a way to specify a longer timeout for post-upgrade jobs? So that helm upgrade will not fail just because one job is taking longer than usual to complete?

**Comment by JMSwag** [comment]
@sagor999 Helm has a timeout option. [Helm Helpful Options](https://helm.sh/docs/intro/using_helm/#helpful-options-for-installupgraderollback)

**Comment by acjohnson** [comment]
I was able to get the helm release to finish by doubling the `activeDeadlineSeconds` value to `200`
```
hooks:
  activeDeadlineSeconds: 200
```
