### ISSUE TITLE
Update Ingress to use networking.k8s.io/v1 api version

### ISSUE THREAD

**Issue by z0rc** [sentry-kubernetes/charts#407]
```
networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
```

Helm recently updated default ingress template to accommodate new api version, see https://github.com/helm/helm/pull/9621

**Comment by razuos** [comment]
This would be nice, just had problems juggling with `pathType`s and had to enable nginx for event ingestion to work.
