### ISSUE TITLE
Snuba API timeout too short -- CrashLooping under load

### ISSUE THREAD

**Issue by jandersen-plaid** [sentry-kubernetes/charts#408]
We have been scaling up our k8s Sentry recently and, as it has taken on more users and load, we are finding that the snuba API pods have a habit of going into `CrashLoopBackOff`. Looking further into this issue, we have found that the issue only comes up when the snuba-api pods are undergoing high load and always happens because the pods miss liveness and readiness checks. Specifically, while under high load, the snuba-api pods will timeout when responding to the kube-probe, but will respond to `/query` requests in a reasonable amount of time.

The pods themselves are behaving fine -- serving query requests normally -- and the resource usage for the pods look fine:
* CPU is under 20~ish% and not being throttled
* Memory is around 30%

but it looks like there might be some blocking behavior in the WSGI responding to a high volume of requests to `/query`.

Now, this isn't something that is super fixable, and only happens when the snuba-api pods are under just enough load to hit the HPA scaling thresholds (and even out that high load) but have not scaled out yet. 

For that reason, I think the snuba api readiness and liveness timeouts should be configurable -- it is a pretty easy fix, so I will likely open a PR against it, but I am definitely open for other solutions here!

**Comment by source-xm** [comment]
in addition to the adjustment liveness and readiness checks.
How to improve the stability and performance of snuba-api under high load?
