### ISSUE TITLE
11.5.1 using outdated clickhouse without service account changes

### ISSUE THREAD

**Issue by kibble1** [sentry-kubernetes/charts#453]
11.5.1 uses an outdated Sentry\Charts\clickhouse-3.0.0.tgz that doesn't contain the service account changes.

Recreating clickhouse-3.0.0.tgz to include the service account changes for clickhouse fails to install with nil value error.

yrmv

**Comment by sagor999** [comment]
Does the chart work if you don't have service accounts enabled?
`serviceAccount.enabled: false`

**Comment by z0rc** [comment]
Seems clickhouse chart needs version bump. After that update dependency in sentry chart.

@kibble1 please clarify the issue. Show us what you did and exact error you got.

**Comment by kibble1** [comment]
forgot what the error was, moved on to other things and **unable to replicate it now**.
basically my steps were,

- delete the file Sentry\Charts\clickhouse-3.0.0.tgz
- copy charts\clickhouse into Sentry\Charts
- commit and push to GH
- the GH actions package and publish to gh-pages

Should be able to update Clickhouse with no trouble Sentry\onpremise is using  image: "yandex/clickhouse-server:20.3.9.70"
