### ISSUE TITLE
[Sentry] Enforce Chart version bump at CI

### ISSUE THREAD

**Issue by jandersen-plaid** [sentry-kubernetes/charts#456]
When using the Sentry chart, we will often make incremental tuning changes to our Sentry deployment based on the workload that comes in (autoscaling counts, pod settings, etc.). Sometimes, we will run our deploy job which diffs the version deployed to our cluster with the new version, and we will see changes apart from our own even when we have not changed the version!

Almost all of the time this is fine and works great for us, as the new changes are usually improvements. That being said, it does make us wonder what happens if a bad change comes through and we are negligent about reviewing differences between the deployed version and the new version. We could potentially get Sentry into a bad state.

With that disaster scenario in mind (potentially deploying a new version of the chart when there has been no versioned change), I was wondering if it would be possible to add a CI time check to enforce version bumps? That way surprise changes like https://github.com/sentry-kubernetes/charts/pull/446 don't get deployed on the same version and users have to opt in to the changes by going up a version (patch, minor, etc.).

Happy to submit a PR for this, but I wanted to know if this is wanted by the community first (or if another CI process would be too onerous).

**Comment by Mokto** [comment]
Would be nice! Go ahead :)
