### ISSUE TITLE
FATAL:  password authentication failed for user "postgres"

### ISSUE THREAD

**Issue by joker-bai** [sentry-kubernetes/charts#465]
PG logs:
```
2021-08-31 09:31:34.573 GMT [346] FATAL:  password authentication failed for user "postgres"
2021-08-31 09:31:34.573 GMT [346] DETAIL:  Password does not match for user "postgres".
	Connection matched pg_hba.conf line 1: "host     all             all             0.0.0.0/0               md5"

```
db init logs:
```
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/__init__.py", line 196, in main
    func(**kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/decorators.py", line 29, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/commands/upgrade.py", line 103, in upgrade
    _upgrade(not noinput, traceback, verbosity, not no_repair, with_nodestore)
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/commands/upgrade.py", line 43, in _upgrade
    _check_history()
  File "/usr/local/lib/python3.6/site-packages/sentry/runner/commands/upgrade.py", line 11, in _check_history
    cursor = connection.cursor()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 254, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/decorators.py", line 40, in inner
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sentry/db/postgres/base.py", line 96, in _cursor
    return super()._cursor()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 229, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python3.6/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 213, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/base/base.py", line 189, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.6/site-packages/django/db/backends/postgresql/base.py", line 176, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  password authentication failed for user "postgres"

```
value.yaml
```
  postgresqlDataDir: /bitnami/postgresql/data
  postgresqlDatabase: sentry
  postgresqlSharedPreloadLibraries: pgaudit
  postgresqlUsername: postgres
  postgresqlPassword: "postgres"
```
i don't know why?

**Comment by joker-bai** [comment]
chart version is: 11.6.0

**Comment by pierreyves-lebrun** [comment]
@qiaokebaba How did you resolve your issue?

**Comment by aca** [comment]
@qiaokebaba Have same issues. Could you share any info about this issue?

**Comment by pierreyves-lebrun** [comment]
> @qiaokebaba Have same issues. Could you share any info about this issue?

In my case I actually had a password mismatch in sentry chart values, it could be your case too

**Comment by mblanloeil** [comment]
I had the same mistake recently, during my deployment tests, I realized that I had simply forgotten to delete the postgres volume... after a complete deletion of the PVC, it worked better...

**Comment by lapwat** [comment]
> I had the same mistake recently, during my deployment tests, I realized that I had simply forgotten to delete the postgres volume... after a complete deletion of the PVC, it worked better...

If you delete the pvc won't you lose all of your data?

**Comment by lapwat** [comment]
@mblanloeil 

> I had the same mistake recently, during my deployment tests, I realized that I had simply forgotten to delete the postgres volume... after a complete deletion of the PVC, it worked better...

If you delete the pvc won't you lose all of your data?

**Comment by lapwat** [comment]
I successfuly installed the Helm Chart the first time using default `values.yaml`.

I have this error when I am trying to update the Helm Chart, maybe the postgres password was changed or auto-generated by this chart ?

I retrieved the postgres password:

```sh
kubectl describe secret sentry-sentry-postgresql
Data
====
postgresql-password:           10 bytes
postgresql-postgres-password:  10 bytes

kubectl get secret sentry-sentry-postgresql -ojsonpath='{.data.postgresql-password}' | base64 -d
xxx

kubectl get secret sentry-sentry-postgresql -ojsonpath='{.data.postgresql-postgres-password}' | base64 -d
yyy
```

Then start a shell in one of the postgres container:

```sh
kubectl exec sentry-sentry-postgresql-0 -it bash
```

And try to connect to the database:

```sh
psql -h localhost -p 5432 -U postgres
Password for user postgres: xxx / yyy
psql: FATAL:  password authentication failed for user "postgres"
```

No success on connecting to the database. What is the password?

**Comment by pierreyves-lebrun** [comment]
> I successfuly installed the Helm Chart the first time using default `values.yaml`.
> 
> I have this error when I am trying to update the Helm Chart, maybe the postgres password was changed or auto-generated by this chart ?
> 
> I retrieved the postgres password:
> 
> ```shell
> kubectl describe secret sentry-sentry-postgresql
> Data
> ====
> postgresql-password:           10 bytes
> postgresql-postgres-password:  10 bytes
> 
> kubectl get secret sentry-sentry-postgresql -ojsonpath='{.data.postgresql-password}' | base64 -d
> xxx
> 
> kubectl get secret sentry-sentry-postgresql -ojsonpath='{.data.postgresql-postgres-password}' | base64 -d
> yyy
> ```
> 
> Then start a shell in one of the postgres container:
> 
> ```shell
> kubectl exec sentry-sentry-postgresql-0 -it bash
> ```
> 
> And try to connect to the database:
> 
> ```shell
> psql -h localhost -p 5432 -U postgres
> Password for user postgres: xxx / yyy
> psql: FATAL:  password authentication failed for user "postgres"
> ```
> 
> No success on connecting to the database. What is the password?

It also seemed to me like the password secret gets renewed on each helm upgrade, in which case the former password is simply lost

**Comment by lapwat** [comment]
> It also seemed to me like the password secret gets renewed on each helm upgrade, in which case the former password is simply lost

Yes I may have upgraded too many times :o

**Comment by Yuliang-Lee** [comment]
I guess the problem is cause by https://github.com/bitnami/bitnami-docker-postgresql#creating-a-database-user-on-first-run
> Note! When POSTGRESQL_USERNAME is specified, the postgres user is not assigned a password and as a result you cannot login remotely to the PostgreSQL server as the postgres user. If you still want to have access with the user postgres, please set the POSTGRESQL_POSTGRES_PASSWORD environment variable (or the content of the file specified in POSTGRESQL_POSTGRES_PASSWORD_FILE).

**Comment by ghost** [comment]
This is still an issue I'm having right now.
Why is this issue closed?

**Comment by bhargavsunkara9** [comment]
I still have the same issue. Installed sentry using helm. chart version - 12.0 and app version - 21.8.0. The ingress is set. But when i try to access the web URL i get 502 bad gateway. So i checked the logs of sentry-web pod and i get the below error:
File "/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: FATAL:  password authentication failed for user "postgres"

How do we resolve this issue? And please keep this issue open.

**Comment by ghost** [comment]
are you passing in the secret that's output after the first install?

**Comment by bhargavsunkara9** [comment]
> are you passing in the secret that's output after the first install?

i tried using the password using values.yaml as well as a secret in different scenarios. still the same error. Is it working for you?

**Comment by ghost** [comment]
yes, works fine for me

**Comment by bhargavsunkara9** [comment]
> yes, works fine for me

could you mention the chart version and app version and also can you tell me how you resolved your issue?

**Comment by cristianrat** [comment]
I got this error when I was upgrading and was doing it wrong (yeah, docs, could be better)
anyway, this is what I do now and it works fine
`helm upgrade sentry sentry/sentry -f values.yaml -n sentry  --set system.secretKey=secretkey`
where secretKey is the key you can see in your terminal after first deployment (and I presume somewhere in secrets)

**Comment by bhargavsunkara9** [comment]
@crisrat : In the above upgrade command how are dealing with authentication issue for postgres? As far i understand the postgres password is generated every deployment. Could you please share you values.yaml it will help me understand better

**Comment by cristianrat** [comment]
@bhargavsunkara9 if I'm not mistaken, the password is only generated IF you don't send it the current one.
So as long as you are sending your existing password, as per the command above, I think you'll be fine
