### ISSUE TITLE
Workers unable to reconnect to RabbitMQ after unexpected restart

### ISSUE THREAD

**Issue by DandyDeveloper** [sentry-kubernetes/charts#47]
So I appear to have a problem in a cluster I'm working with where the readiness probes are failing and the mq components keep restarting (This is my issue to deal with).

However, the workers appear to struggle reconnecting as a consumer to the MQ server even though RabbitMQ seems to be OK. This MAY be because the service doesn't see the pod as "ready" because the readiness probe isn't finishing. 

This may be an entirely localised issue, but I'm jotting it down here just insane. 

@Mokto

**Comment by Mokto** [comment]
Are you only talking about the workers ? Because there isn't any readiness probe here.
And sentry-web & sentry-workers should be independent.

**Comment by DandyDeveloper** [comment]
@Mokto Readiness probe in Rabbit is dying and I don't think the workers are registering as consumers after the rabbitmq comes back.

**Comment by Mokto** [comment]
Oh, ok, RabbitMQ is dying ?

I would say make sure you have put enough memory on each node + set an high enough watermark:

https://github.com/sentry-kubernetes/charts/blob/develop/sentry/values.yaml#L301

**Comment by DandyDeveloper** [comment]
@Mokto 

> So I appear to have a problem in a cluster I'm working with where the readiness probes are failing and the mq components keep restarting (This is my issue to deal with).

I know why the Rabbitmq is dying, my concern is the reconnection of the workers to Rabbitmq when it comes back up. 

I'm not even sure this is an issue yet. Just writing it down whilst I investigate,

**Comment by Mokto** [comment]
@DandyDeveloper Have you found something new regarding this?
Or should we close this ?

Thanks.

**Comment by DandyDeveloper** [comment]
@Mokto I'm like.... 99% sure this was cluster specific. So I think we're good to close for now.

**Comment by Mokto** [comment]
Thanks!
