### ISSUE TITLE
frequent sentry-worker restart in 11.7.0(livenessProbe)

### ISSUE THREAD

**Issue by hippoz** [sentry-kubernetes/charts#477]
09:40:37 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
09:40:40 [INFO] sentry.plugins.github: apps-not-configured
09:40:40 [INFO] sentry.bgtasks: bgtask.spawn (task_name='sentry.bgtasks.clean_dsymcache:clean_dsymcache')
09:40:40 [INFO] sentry.bgtasks: bgtask.spawn (task_name='sentry.bgtasks.clean_releasefilecache:clean_releasefilecache')

 -------------- celery@sentry-eks-worker-5cfdbf8dc6-qqnwz v4.4.7 (cliffs)
--- ***** -----
-- ******* ---- Linux-5.4.129-63.229.amzn2.x86_64-x86_64-with-debian-10.10 2021-09-11 09:40:41
- *** --- * ---
- ** ---------- [config]
- ** ---------- .> app:         sentry:0x7f6a46761f98
- ** ---------- .> transport:   amqp://guest:**@sentry-eks-rabbitmq:5672//
- ** ---------- .> results:     disabled://
- *** --- * --- .> concurrency: 4 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** -----
 -------------- [queues]
                .> activity.notify  exchange=default(direct) key=activity.notify
                .> alerts           exchange=default(direct) key=alerts
                .> app_platform     exchange=default(direct) key=app_platform
                .> appstoreconnect  exchange=default(direct) key=sentry.tasks.app_store_connect.#
                .> assemble         exchange=default(direct) key=assemble
                .> auth             exchange=default(direct) key=auth
                .> buffers.process_pending exchange=default(direct) key=buffers.process_pending
                .> cleanup          exchange=default(direct) key=cleanup
                .> code_owners      exchange=default(direct) key=code_owners
                .> commits          exchange=default(direct) key=commits
                .> counters-0       exchange=counters(direct) key=default
                .> data_export      exchange=default(direct) key=data_export
                .> default          exchange=default(direct) key=default
                .> digests.delivery exchange=default(direct) key=digests.delivery
                .> digests.scheduling exchange=default(direct) key=digests.scheduling
                .> email            exchange=default(direct) key=email
                .> events.preprocess_event exchange=default(direct) key=events.preprocess_event
                .> events.process_event exchange=default(direct) key=events.process_event
                .> events.reprocess_events exchange=default(direct) key=events.reprocess_events
                .> events.reprocessing.preprocess_event exchange=default(direct) key=events.reprocessing.preprocess_event
                .> events.reprocessing.process_event exchange=default(direct) key=events.reprocessing.process_event
                .> events.reprocessing.symbolicate_event exchange=default(direct) key=events.reprocessing.symbolicate_event
                .> events.save_event exchange=default(direct) key=events.save_event
                .> events.symbolicate_event exchange=default(direct) key=events.symbolicate_event
                .> files.delete     exchange=default(direct) key=files.delete
                .> group_owners.process_suspect_commits exchange=default(direct) key=group_owners.process_suspect_commits
                .> incident_snapshots exchange=default(direct) key=incident_snapshots
                .> incidents        exchange=default(direct) key=incidents
                .> integrations     exchange=default(direct) key=integrations
                .> merge            exchange=default(direct) key=merge
                .> options          exchange=default(direct) key=options
                .> relay_config     exchange=default(direct) key=relay_config
                .> releasemonitor   exchange=default(direct) key=releasemonitor
                .> reports.deliver  exchange=default(direct) key=reports.deliver
                .> reports.prepare  exchange=default(direct) key=reports.prepare
                .> search           exchange=default(direct) key=search
                .> sleep            exchange=default(direct) key=sleep
                .> stats            exchange=default(direct) key=stats
                .> subscriptions    exchange=default(direct) key=subscriptions
                .> triggers-0       exchange=triggers(direct) key=default
                .> unmerge          exchange=default(direct) key=unmerge
                .> update           exchange=default(direct) key=update

**/usr/local/lib/python3.6/site-packages/sentry/utils/strings.py:45: DeprecationWarning: invalid escape sequence '\['
  "unicode-escape", "unicode-escape-recovery"
/usr/local/lib/python3.6/site-packages/celery/platforms.py:801: RuntimeWarning: You're running the worker with superuser privileges: this is
absolutely not recommended!

Please specify a different user using the --uid option.

User information: uid=0 euid=0 gid=0 egid=0

  uid=uid, euid=euid, gid=gid, egid=egid,
09:43:44 [INFO] sentry.bgtasks: bgtask.stop (task_name='sentry.bgtasks.clean_dsymcache:clean_dsymcache')
09:43:44 [INFO] sentry.bgtasks: bgtask.stop (task_name='sentry.bgtasks.clean_releasefilecache:clean_releasefilecache')

worker: Warm shutdown (MainProcess)**

**Comment by prskr** [comment]
#478 just got merged, as soon as it is released could you please confirm if the problem persists?

**Comment by hippoz** [comment]
@baez90 thanks, sure :)

**Comment by hippoz** [comment]
I upgraded to the latest version now. thanks
