### ISSUE TITLE
` [Errno 2] No such file or directory` while uploading sourcemap 

### ISSUE THREAD

**Issue by rovast** [sentry-kubernetes/charts#489]
![image](https://user-images.githubusercontent.com/9459488/133768868-36e4066a-3074-447c-a774-1bfec1933e57.png)

Similar issues
- https://github.com/getsentry/sentry/issues/16462
- https://github.com/sentry-kubernetes/charts/issues/277
- https://github.com/sentry-kubernetes/charts/issues/172

> By the way, with the same configuration(except `auth` and `url`), uploading to sentry.io is OK. So I guess the problem is in deployment scope.

**Comment by mayocream** [comment]
I have same problem and looking for help.

**Comment by hippoz** [comment]
do you use ReadWriteOnce Storage? 

**Note**: If you need to run or cannot avoid running sentry-worker and sentry-web on different cluster nodes, you need to set filestore.filesystem.persistence.accessMode: ReadWriteMany or might get problems. HOWEVER, [not all volume drivers support that](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes) , like AWS EBS or GCP disks. So you would want to create and use a StorageClass with a supported volume driver like AWS EFS

**Comment by rovast** [comment]
> do you use ReadWriteOnce Storage?
> 
> **Note**: If you need to run or cannot avoid running sentry-worker and sentry-web on different cluster nodes, you need to set filestore.filesystem.persistence.accessMode: ReadWriteMany or might get problems. HOWEVER, [not all volume drivers support that](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes) , like AWS EBS or GCP disks. So you would want to create and use a StorageClass with a supported volume driver like AWS EFS

Thank you for your reply. Set web and worker share the same PVC, the problem has been solved.

refer: https://github.com/getsentry/onpremise/issues/486#issuecomment-637084593

**Comment by teebu** [comment]
GCP doesn't support ReadWriteMany. What do I do? Is there a way to force them to be on the same node?
