### ISSUE TITLE
[Release 11.9.0] chart version is still 11.8.0 in Chart.yaml 

### ISSUE THREAD

**Issue by hippoz** [sentry-kubernetes/charts#490]
[Release 11.9.0] chart version is still 11.8.0 in Chart.yaml 

https://github.com/sentry-kubernetes/charts/releases/tag/11.9.0

https://github.com/sentry-kubernetes/charts/blob/develop/sentry/Chart.yaml

**Comment by Mokto** [comment]
Fixed, thanks

**Comment by sagor999** [comment]
I just downloaded the chart from releases section and it still says 11.8.0 version in there. Not sure if it was supposed to be fixed in there too. @Mokto

**Comment by Mokto** [comment]
No it wasn't. But the helm chart version should match!
