### ISSUE TITLE
503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by omartinez74** [sentry-kubernetes/charts#497]
Hi everyone. 
I have deployed the chart version 12.0.0 and I have found an error in the sentry-relay service. 
To solve it you have to indicate in the selector:
    app: sentry-io
    **release: sentry-io**
    role: relay
otherwise, the ingress controller returns a 503.
Thank you

**Comment by iburrows** [comment]
Hi, what do you mean by selector? NodeSelector?

**Comment by iburrows** [comment]
ok yes nodeSelector it is. I changed this and no 503 errors are seen anymore. Thanks
