### ISSUE TITLE
Exception: KafkaError{code=OFFSET_OUT_OF_RANGE}

### ISSUE THREAD

**Issue by flixx** [sentry-kubernetes/charts#512]
Hello,

I have installed sentry via helm. After some time, I see a lot of errors from the `sentry-snuba-subscription-consumer-events` and `sentry-snuba-subscription-consumer-transactions` pods: 

```
 File "/usr/local/lib/python3.8/site-packages/arroyo/backends/kafka/consumer.py", line 392, in poll
    raise OffsetOutOfRange(str(error))
arroyo.errors.OffsetOutOfRange: KafkaError{code=OFFSET_OUT_OF_RANGE,val=1,str="Broker: Offset out of range"}
```

After googling a bit I found that it is a [common issue](https://github.com/getsentry/onpremise/issues/478).
It seems to be so common that sentry even added this to their [troubleshooting guide](https://develop.sentry.dev/self-hosted/troubleshooting/) (with instructions for `docker-compose` )

What would be the correct way of handling this error using the helm installation?

Thanks!
Felix

**Comment by sagor999** [comment]
Hi,
correct way is to follow sentry's troubleshooting guide for this error. Just shell into kafka container and run the commands listed in troubleshooting guide to fix this.

**Comment by flixx** [comment]
Hello @sagor999, thanks for that answer. However it is not that simple it seems. But I got it now. Here are my steps:

1. Exicing into the `sentry-kafka-0` pod.
2. Executing `kafka-consumer-groups` gives me a `command not found`.
3. Found the script at `/opt/bitnami/kafka/bin/kafka-console-consumer.sh`.
4. There it must be executed like this: ` ./kafka-consumer-groups.sh --bootstrap-server sentry-kafka:9092 --list` (Note that I replaced (`kafka` with `sentry-kafka` here)
5. Executing the 3rd command from the troubleshooting guide gives me this: `Error: Assignments can only be reset if the group 'snuba-consumers' is inactive, but the current state is Stable.`
6. In the original issue somebody suggests that [all other containers must be stoped](https://github.com/getsentry/onpremise/issues/478#issuecomment-667102906). So I executed this: `kubectl scale --namespace sentry --replicas=0 deployment/sentry-sessions-consumer`. I also executed this for the deployments `sentry-ingest-consumer`, `sentry-sessions-consumer`, `sentry-snuba-outcomes-consumer`, `sentry-snuba-outcomes-con`
7. Now the 3rd and 4th command worked
8. I brought all 4 deployments back up by repeating step 6 with  `--replicas=1` (or whatever count it was before)
9. I repeated the 3rd and 4th command also with the groups `snuba-subscription-consumers` and ` snuba-events-subscriptions-consumers`.

I hope that this will resolve the problem for now...

**Comment by rlukin** [comment]
Expanding @flixx answer:
1. Scale down consumer deployments: `for d in $(kubectl get deployments -n sentry -o name| grep consumer); do echo kubectl scale --namespace sentry --replicas=0 ${d}; done | bash -x` 
2. Exec into `sentry-kafka-0` pod - `kubectl exec -ti -n sentry sentry-kafka-0 -- bash` 
3. `cd /opt/bitnami/kafka/bin/`
4. _Optional_: Check all groups state `for g in $(./kafka-consumer-groups.sh --bootstrap-server sentry-kafka:9092 --list) ; do ./kafka-consumer-groups.sh --bootstrap-server sentry-kafka:9092 --group ${g} -describe; done`
5. Set offset to latest `./kafka-consumer-groups.sh --bootstrap-server sentry-kafka:9092 --all-groups --all-topics --reset-offsets --to-latest --execute`
6. Scale up deployments back `for d in $(kubectl get deployments -n sentry -o name| grep consumer); do echo kubectl scale --namespace sentry --replicas=1 ${d}; done | bash -x`

_Remove `| bash -x` to check what will run_

**Comment by rkmudunuru** [comment]
@rlukin - I believe you would need to scale down post-process deployment alongside consumer in step 1. 

`kubectl scale --namespace sentry --replicas=0 deploy/sentry-post-process-forward`
