### ISSUE TITLE
Create admin user config in values.yaml not working

### ISSUE THREAD

**Issue by lapwat** [sentry-kubernetes/charts#513]
I get inside sentry web pod

```
k exec -it sentry-web-xxxxxxxxxx-xxxxx -- bash
```

And create a new user

```
root@sentry-web-xxxxxxxxxx-xxxxx:/# sentry createuser --no-input --superuser --email superuser@email.com --password bbbb
16:31:52 [WARNING] sentry.utils.geo: settings.GEOIP_PATH_MMDB not configured.
16:31:57 [INFO] sentry.plugins.github: apps-not-configured
Added to organization: sentry
User created: superuser@email.com
```

All good until I try to login on the web interface:

![image](https://user-images.githubusercontent.com/7073651/139108392-897cc7fb-2bd0-4674-bb32-fa7c5a3a36b4.png)

Translation: Please enter valid username and password.

I have discovered this error because the chart `sentry` does not create the admin user as specified in `values.yaml`

I think that the command below is not working properly.

https://github.com/sentry-kubernetes/charts/blob/8f4350763160b5c5c7dcea7b56ea957f403d8a1d/sentry/templates/hooks/user-create.yaml#L55-L59

Note: Signing up from the web interface works as expected, but does not give me super admin rights.

**Comment by yurymkomarov** [comment]
@lapwat you've said that the chart doesn't create the admin user from values.yaml data

Can u show an example, how did you pass data to values, please?

**Comment by lapwat** [comment]
Thanks for your answer.

# Steps to reproduce

```sh
helm repo add sentry https://sentry-kubernetes.github.io/charts
helm repo update

wget https://raw.githubusercontent.com/sentry-kubernetes/charts/develop/sentry/values.yaml

helm install sentry sentry/sentry -f values.yaml
k port-forward sentry-web-xxxxxxxxxx-xxxxx 9000:9000
```

Go to `http://localhost:9000` and try to connect with`admin@sentry.local:aaaa`.

**Comment by lapwat** [comment]
I was trying to connect to a different Sentry instance...
