### ISSUE TITLE
Worker cannot connect to RabbitMQ

### ISSUE THREAD

**Issue by voslartomas** [sentry-kubernetes/charts#56]
Sentry worker cannot connect to rabbitmq, this cause that issues are not processed I guess .
```
11:36:23 [ERROR] celery.worker.consumer: consumer: Cannot connect to amqp://guest:**@sentry-rabbitmq:5672//: Error opening socket: hostname lookup failed.
```

**Comment by Mokto** [comment]
Could you check if rabbitmq is started? And if so, is the service name correct?

Thanks.

**Comment by voslartomas** [comment]
<img width="827" alt="Screenshot 2020-04-16 at 13 53 25" src="https://user-images.githubusercontent.com/1945040/79453218-a6287c00-7fe9-11ea-9438-04ef348627de.png">

It is up and running, but I don't think URL is correct.

Name of the service is `sentry-rabbitmq-ha`

**Comment by Mokto** [comment]
I created #57 to fix it.

**Comment by voslartomas** [comment]
Still same problem.

**Comment by voslartomas** [comment]
And after re run with new version it has another error.

sentry-db-init-wxrfk
```
django.db.utils.OperationalError: FATAL:  password authentication failed for user "postgres"
```

**Comment by Mokto** [comment]
I think that might be because the postgres password changes every time you re-deploy the chart.

I would advise to remove everything and set up a fixed password.

**Comment by voslartomas** [comment]
Ok, not very convenient though. What about the first problem?

**Comment by Mokto** [comment]
It's not really convenient indeed, but there's nothing we can do about it.

See https://github.com/helm/charts/tree/master/stable/sentry#postgressql

**Comment by Mokto** [comment]
I'll have a look at the other thing as soon as I can

**Comment by Mokto** [comment]
@voslartomas your service name should be `rabbitmq`, not `rabbitmq-ha`, actually.

I tested the whole chart, blank, as you use it, and it works flawlessly.

Maybe it's because your chart was first created before https://github.com/sentry-kubernetes/charts/pull/33 was merged.
