### ISSUE TITLE
13.0.0 chart isn't available in helm repository

### ISSUE THREAD

**Issue by z0rc** [sentry-kubernetes/charts#562]
https://github.com/sentry-kubernetes/charts/releases/tag/13.0.0 is missing from helm repo
```
% helm search repo sentry
NAME                       	CHART VERSION	APP VERSION	DESCRIPTION
sentry/sentry              	12.0.0       	21.8.0     	A Helm chart for Kubernetes
```

Probably due to failing push action. https://github.com/sentry-kubernetes/charts/actions/workflows/push.yaml

**Comment by Mokto** [comment]
Thanks! 
I fixed it & the build.
