### ISSUE TITLE
Chart doesn't work if mail settings are not set

### ISSUE THREAD

**Issue by voslartomas** [sentry-kubernetes/charts#6]
Hi it fails when you leave defaults empty on this error.

```
File "/usr/local/lib/python2.7/site-packages/sentry/options/manager.py", line 270, in validate_option
    raise TypeError("%r: got %r, expected %r" % (key, _type(value), opt.type))
TypeError: 'mail.username': got <type 'NoneType'>, expected string
```

**Comment by voslartomas** [comment]
It's enough to fill in mail settings to go through.

But then there is another error with PVC

```
  Warning  FailedScheduling  61s (x8 over 114s)  default-scheduler  persistentvolumeclaim "sentry" not found
```

I can see only sentry-data PVC created.

**Comment by voslartomas** [comment]
Also there is no ingress.

**Comment by Mokto** [comment]
Thanks for your feedbacks ! I created a new issue for the ingress.

**Comment by voslartomas** [comment]
@Mokto No problem, thank you for this repo :) It saved me lot of time.

I have one more question, now I have sentry 10.0 up and running, but when I send some issue into that, it seems like this

<img width="1448" alt="Screenshot 2020-02-05 at 10 40 04" src="https://user-images.githubusercontent.com/1945040/73829909-0938ae00-4804-11ea-9127-80824baf4311.png">

It seems it gets that issue, because there is number with New Issues, but I can't see it in the list. Have you encountered this problem? I am sending this from react native app, it works on previous version of Sentry (but there I have problems with source maps:)).

**Comment by Mokto** [comment]
I think it's because we need to deploy a consumer with redis (right now it's only with RabbitMQ). I'll have a look at it ASAP.

**Comment by voslartomas** [comment]
I see, are you planning to take a look today? Or can you at least point me out, how to deploy it, I would try it... I can create PR then.

**Comment by voslartomas** [comment]
I can see already Redis instance deployed. But this might be interesting, found in sentry-worker logs

```
21:40:06 [WARNING] sentry.eventstream.kafka.backend: Could not publish message (error: KafkaError{code=_MSG_TIMED_OUT,val=-192,str="Local: Message timed out"}): <cimpl.Message object at 0x7f0af01452d0>
```

**Comment by Mokto** [comment]
Not sure I have the time to look at it today.
What I know is that with the previous sentry helm chart, I used RabbitMQ as a broker (just like here). And I had to run 2 consumers : one for rabbitmq, one for redis.

But what you saw seems like a real issue, yes ! But I don't know much about kafka tbh.

**Comment by voslartomas** [comment]
@Mokto Hey, I am just trying new version 0.6.0, but cannot get it working

```
  Warning  FailedAttachVolume  2m6s  attachdetach-controller                Multi-Attach error for volume "pvc-a1f35083-4762-11ea-9f29-0ed20466a6e5" Volume is already used by pod(s) sentry10-post-process-forward-5ff69cf68-98zx5
```

**Comment by Mokto** [comment]
Yes it's because you're using a ReadWriteOnce volume.

I'm using S3 as filestore to prevent that for example.

**Comment by voslartomas** [comment]
And how is it possible that old sentry was working with RWO?

**Comment by Mokto** [comment]
Thanks to this line : https://github.com/helm/charts/blob/master/stable/sentry/templates/workers-deployment.yaml#L159

persistentWorkers was probably false in your case.

I can try to apply the same thing to the worker + post process forwarder

**Comment by voslartomas** [comment]
Ok, so basically cron, workers etc don't need that pvc... I was trying to have this storage only on web, it started but I couldnt see any issues again :/

**Comment by Mokto** [comment]
The shared PVC (or s3 bucket) is useful when you want to share sourcemaps on a release for example !

That's when persistentWorkers is useful

**Comment by voslartomas** [comment]
Ok, I just read it, I will need this for sure, so I guess it's better to switch to gce.

**Comment by Mokto** [comment]
And it also allows you to scale your sentry-web deployment.

**Comment by voslartomas** [comment]
yeah, right.. perfect thanks, I will work on this and let you know

**Comment by Mokto** [comment]
https://github.com/sentry-kubernetes/charts/pull/15.

That should fix it ;)

**Comment by Mokto** [comment]
You can use the 0.7.0 version.

That should fix the issue

**Comment by voslartomas** [comment]
Also there is one bug 

This is pvc def
```
name: {{ template "sentry.prefix" . }}sentry-data
  labels:
```

but then in deployments you are using 

```
claimName: {{ template "sentry.fullname" . }}
```

**Comment by voslartomas** [comment]
Hey @Mokto , so trying again new version 0.7.0 this time with s3 bucket, but still having same problem, I can't see any issues in the list, but it shows increasing number of issues in release...

**Comment by voslartomas** [comment]
I've noticed this error in kafka-confluent-0
```
[2020-02-10 11:42:33,230] ERROR [Controller id=1013 epoch=13] Controller 1013 epoch 13 failed to change state for partition __consumer_offsets-40 from OfflinePartition to OnlinePartition (state.change.logger)
kafka.common.StateChangeFailedException: Failed to elect leader for partition __consumer_offsets-40 under strategy OfflinePartitionLeaderElectionStrategy(false)
```

**Comment by Mokto** [comment]
I do see issues in the list to be honest. Not sure what this is about...

**Comment by voslartomas** [comment]
It's ok now, I had to remove all the PVs and now it seems working finally. I have two more PRs will send them... (there was error with gcs)
