### ISSUE TITLE
Update to Chart Version 14 without losing Data

### ISSUE THREAD

**Issue by mFeigeInvia** [sentry-kubernetes/charts#602]
Hi,
Is there a way to update to 14 without losing the data?

WARNING: You will lose current event data
Otherwise, you should delete the old ClickHouse volumes in-order to upgrade to this version.

https://github.com/sentry-kubernetes/charts#upgrading-from-13xx-version-of-this-chart-to-1400

thx,
Martin

**Comment by Mokto** [comment]
unfortunately not. Sentry requires a sharded data for Clickhouse.

**Comment by maths22** [comment]
I will say I have done this successfully.  It's a rather laborious process, but I was able to migrate our sentry instance from the old model to the new model.  It requires basically manually following this process for every clickhouse table:
https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replication/#converting-from-mergetree-to-replicatedmergetree

Steps without detailed directions:
1. For each table, run `SHOW CREATE TABLE tablename`
2. Replace e.g. `ENGINE = MergeTree` with `ENGINE = ReplicatedMergeTree('/clickhouse/tables/outcomes/{shard}/default/outcomes_raw_local', '{replica}')` (where outcomes is the appropriate snuba storageset for each table and outcomes_raw_local is the table name.  Also you will need to review snuba source to check which tables use {shard} and which use `all`) and add `_replicated` to the table name
3. Scale down all snuba consumers to 0.  This will allow incoming data to accumulate in kafka without creating additional data
4. Run all the new create table statements
5. For each table, run `clickhouse-client --format=TSVRaw -q"select 'ALTER TABLE default.outcomes_raw_local_replicated ATTACH PARTITION  '''|| partition ||''' FROM default.outcomes_raw_local;\n' from system.parts where table = 'outcomes_raw_local' group by partition" | clickhouse-client -mn` (substituting the table names as appropriate
6. Run the following for each table:
```
clickhouse-client --query 'RENAME TABLE default.outcomes_raw_local TO default.outcomes_raw_local_legacy;'
clickhouse-client --query 'RENAME TABLE default.outcomes_raw_local_replicated TO default.outcomes_raw_local;'
```
7. Scale the snuba consumers back up
8. After you are happy that things are working well, drop all the `*_legacy` tables

If there is interest I can try to figure out how to script it

**Comment by mFeigeInvia** [comment]
> I will say I have done this successfully. It's a rather laborious process, but I was able to migrate our sentry instance from the old model to the new model. It requires basically manually following this process for every clickhouse table: https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replication/#converting-from-mergetree-to-replicatedmergetree
> 
> Steps without detailed directions:
> 
> 1. For each table, run `SHOW CREATE TABLE tablename`
> 2. Replace e.g. `ENGINE = MergeTree` with `ENGINE = ReplicatedMergeTree('/clickhouse/tables/outcomes/{shard}/default/outcomes_raw_local', '{replica}')` (where outcomes is the appropriate snuba storageset for each table and outcomes_raw_local is the table name.  Also you will need to review snuba source to check which tables use {shard} and which use `all`) and add `_replicated` to the table name
> 3. Scale down all snuba consumers to 0.  This will allow incoming data to accumulate in kafka without creating additional data
> 4. Run all the new create table statements
> 5. For each table, run `clickhouse-client --format=TSVRaw -q"select 'ALTER TABLE default.outcomes_raw_local_replicated ATTACH PARTITION  '''|| partition ||''' FROM default.outcomes_raw_local;\n' from system.parts where table = 'outcomes_raw_local' group by partition" | clickhouse-client -mn` (substituting the table names as appropriate
> 6. Run the following for each table:
> 
> ```
> clickhouse-client --query 'RENAME TABLE default.outcomes_raw_local TO default.outcomes_raw_local_legacy;'
> clickhouse-client --query 'RENAME TABLE default.outcomes_raw_local_replicated TO default.outcomes_raw_local;'
> ```
> 
>  7. Scale the snuba consumers back up
> 8. After you are happy that things are working well, drop all the `*_legacy` tables
> 
> If there is interest I can try to figure out how to script it

Thanks for it, maybe there are some other Users of this Chart how are interested in this. I'm not so deep into clickhouse that I am able to do it.
