### ISSUE TITLE
sentry-ingest-consumer error

### ISSUE THREAD

**Issue by sennierer** [sentry-kubernetes/charts#625]
I am getting an error from sentry-ingest-consumer.

It claims that Kafka is returning an error, but actually according to the logs Kafka seems to be running fine. does anyone have an idea how to resolve that?

```RuntimeError: Unknown error when waiting for Kafka topic 'ingest-attachments': KafkaError{code=INVALID_REPLICATION_FACTOR,val=38,str="Broker: Invalid replication factor"}```

Thanks!

**Comment by dev-bobsong** [comment]
If you set kafka's replicaCount to 1, then you should also set defaultReplicationFactor to 1.
```
kafka:
  ...
  defaultReplicationFactor: 1
```

**Comment by sennierer** [comment]
Thanks! I missed that setting. Its working now!
