### ISSUE TITLE
[sentry] Chart 14.1.0 breaks sharded clickhouse/snuba configuration

### ISSUE THREAD

**Issue by ts-mini** [sentry-kubernetes/charts#627]
The [change w.r.t external clickhouse](https://github.com/sentry-kubernetes/charts/pull/608) seemed to cause issues with our sentry deployment on 14.1.0 with default settings.  It looks like it results into a clickhouse config that only queries a single node, not the whole sharded cluster.  The broken snuba config below:
```
# Clickhouse Options
CLUSTERS = [
  {
    "host": env("CLICKHOUSE_HOST", "sentry-clickhouse"),
    "port": int(9000),
    "user":  env("CLICKHOUSE_USER", "default"),
    "password": env("CLICKHOUSE_PASSWORD", ""),
    "database": env("CLICKHOUSE_DATABASE", "default"),
    "http_port": 8123,
    "storage_sets": {
        "cdc",
        "discover",
        "events",
        "events_ro",
        "metrics",
        "migrations",
        "outcomes",
        "querylog",
        "sessions",
        "transactions",
        "transactions_ro",
        "transactions_v2",
        "errors_v2",
        "errors_v2_ro",
        "profiles",
    },
    "single_node": True,
    "cluster_name": "sentry-clickhouse",
    "distributed_cluster_name": "sentry-clickhouse",
  },
]
```

My thoughts:
Normally, the externalClickhouse config was ignored because of the logic, but the recent change caused the above config.

I was able to get around this in the short term by adding this block:
```
externalClickhouse:
  singleNode: false
```

which forces the config to respect the cluster as a whole and resulting in the correct snuba config (no more intermittent/load-balancer-esque issues).  

I'm not sure HOW you would prefer this logic to be remediated - but would be willing to contribute a fix if needed.

**Comment by z0rc** [comment]
Most likely will be fixed with https://github.com/sentry-kubernetes/charts/pull/624
