### ISSUE TITLE
Error: YAML parse error on sentry/templates/configmap-snuba.yaml

### ISSUE THREAD

**Issue by maynewong** [sentry-kubernetes/charts#65]
`helm install sentry` 

Error: YAML parse error on sentry/templates/configmap-snuba.yaml: error converting YAML to JSON: yaml: line 14: did not find expected key

**Comment by Mokto** [comment]
What's was the exact command you runned please?

And with what parameters?

**Comment by maynewong** [comment]
set 
kafka.enabled = false

**Comment by Mokto** [comment]
Hey! 
The PR was already there but not merged.

I just merged it and I'm going to create a new release now.

**Comment by Mokto** [comment]
https://github.com/sentry-kubernetes/charts/pull/43
