### ISSUE TITLE
Sentry running but postgres logs full of errors

### ISSUE THREAD

**Issue by bumarcell** [sentry-kubernetes/charts#664]
Greetings ^_^

I just deployed sentry chart v15 in our k8s cluster with all defaults and it seems to be running just fine.
One thing that came off weird however were the postgres logs:
![image](https://user-images.githubusercontent.com/28063982/178944925-ba052582-0023-4813-882f-b78a2a090e30.png)

Any idea what it's trying to do and why? :)

**Comment by alekitto** [comment]
I think that's the way Sentry works internally: instead of checking things before firing a query, it handles the eventual error.
My postgres too is full of errors, but it tracks app errors and performace events correctly.
