### ISSUE TITLE
Snuba migration 0013_backfill_error fails with external clickhouse

### ISSUE THREAD

**Issue by bumarcell** [sentry-kubernetes/charts#677]
### Environment
How do you use Sentry?
Self-hosted sentry v22.6.0 (from chart v15)
Snuba v22.7.0
External clickhouse 22.1.3.7 (official build), single-node

### Steps to Reproduce
Edit `values.yaml` to use link my external clickhouse server then deploy the chart in k8s

### Expected Result
Deployment goes through just fine

### Actual Result
The snuba-migrate job fails:
`    for packet in self.packet_generator:
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 167, in packet_generator
    packet = self.receive_packet()
  File "/usr/local/lib/python3.8/site-packages/clickhouse_driver/client.py", line 184, in receive_packet
    raise packet.exception
clickhouse_driver.errors.ServerException: Code: 44.
DB::Exception: Illegal column Nullable(FixedString(32)) of first argument of function toString. Stack trace:

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa82d07a in /usr/bin/clickhouse
1. DB::ConvertImpl<DB::DataTypeFixedString, DB::DataTypeString, DB::NameToString, DB::ConvertDefaultBehaviorTag>::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) @ 0xcffd7bd in /usr/bin/clickhouse
2. bool DB::callOnIndexAndDataType<DB::DataTypeString, DB::FunctionConvert<DB::DataTypeString, DB::NameToString, DB::ToStringMonotonicity>::executeInternal(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const::'lambda'(auto const&, auto const&)&, DB::ConvertDefaultBehaviorTag>(DB::TypeIndex, auto&&, DB::ToStringMonotonicity&&...) @ 0xcfec130 in /usr/bin/clickhouse
3. DB::FunctionConvert<DB::DataTypeString, DB::NameToString, DB::ToStringMonotonicity>::executeInternal(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0xcfebc13 in /usr/bin/clickhouse
4. DB::FunctionConvert<DB::DataTypeString, DB::NameToString, DB::ToStringMonotonicity>::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0xcfeb11c in /usr/bin/clickhouse
5. DB::IFunction::executeImplDryRun(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0xcd2960a in /usr/bin/clickhouse
6. DB::FunctionToExecutableFunctionAdaptor::executeDryRunImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0xcd284ce in /usr/bin/clickhouse
7. DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x12e2a165 in /usr/bin/clickhouse
8. DB::IExecutableFunction::executeWithoutSparseColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x12e2a7a8 in /usr/bin/clickhouse
9. DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x12e2b8af in /usr/bin/clickhouse
10. DB::ActionsDAG::updateHeader(DB::Block) const @ 0x1341bac1 in /usr/bin/clickhouse
11. DB::ExpressionStep::ExpressionStep(DB::DataStream const&, std::__1::shared_ptr<DB::ActionsDAG>) @ 0x14acc4e3 in /usr/bin/clickhouse
12. DB::InterpreterSelectQuery::executeExpression(DB::QueryPlan&, std::__1::shared_ptr<DB::ActionsDAG> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x13a7ad4a in /usr/bin/clickhouse
13. DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::__1::optional<DB::Pipe>) @ 0x13a71c95 in /usr/bin/clickhouse
14. DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) @ 0x13a6ff90 in /usr/bin/clickhouse
15. DB::InterpreterSelectWithUnionQuery::buildQueryPlan(DB::QueryPlan&) @ 0x13abfc03 in /usr/bin/clickhouse
16. DB::IInterpreterUnionOrSelectQuery::buildQueryPipeline() @ 0x13a50d53 in /usr/bin/clickhouse
17. DB::InterpreterInsertQuery::execute() @ 0x13a4c449 in /usr/bin/clickhouse
18. ? @ 0x13d1434c in /usr/bin/clickhouse
19. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x13d11e55 in /usr/bin/clickhouse
20. DB::TCPHandler::runImpl() @ 0x147f050f in /usr/bin/clickhouse
21. DB::TCPHandler::run() @ 0x14804259 in /usr/bin/clickhouse
22. Poco::Net::TCPServerConnection::start() @ 0x1745e52f in /usr/bin/clickhouse
23. Poco::Net::TCPServerDispatcher::run() @ 0x17460981 in /usr/bin/clickhouse
24. Poco::PooledThread::run() @ 0x17611609 in /usr/bin/clickhouse
25. Poco::ThreadImpl::runnableEntry(void*) @ 0x1760ed00 in /usr/bin/clickhouse
26. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so
27. clone @ 0x12161f in /lib/x86_64-linux-gnu/libc-2.27.so

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/migrations.py", line 64, in migrate
    runner.run_all(force=force)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 157, in run_all
    self._run_migration_impl(migration_key, force=force)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 217, in _run_migration_impl
    migration.forwards(context, dry_run)
  File "/usr/src/snuba/snuba/migrations/migration.py", line 74, in forwards
    op.execute(logger)
  File "/usr/src/snuba/snuba/migrations/operations.py", line 320, in execute
    self.__func(logger)
  File "/usr/src/snuba/snuba/migrations/snuba_migrations/events/0014_backfill_errors.py", line 180, in backfill_errors
    clickhouse.execute(operation.format_sql())
  File "/usr/src/snuba/snuba/clickhouse/native.py", line 263, in execute
    raise ClickhouseError(e.message, code=e.code) from e
snuba.clickhouse.errors.ClickhouseError: DB::Exception: Illegal column Nullable(FixedString(32)) of first argument of function toString. Stack trace:

0. DB::Exception::Exception(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, int, bool) @ 0xa82d07a in /usr/bin/clickhouse
1. DB::ConvertImpl<DB::DataTypeFixedString, DB::DataTypeString, DB::NameToString, DB::ConvertDefaultBehaviorTag>::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) @ 0xcffd7bd in /usr/bin/clickhouse
2. bool DB::callOnIndexAndDataType<DB::DataTypeString, DB::FunctionConvert<DB::DataTypeString, DB::NameToString, DB::ToStringMonotonicity>::executeInternal(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const::'lambda'(auto const&, auto const&)&, DB::ConvertDefaultBehaviorTag>(DB::TypeIndex, auto&&, DB::ToStringMonotonicity&&...) @ 0xcfec130 in /usr/bin/clickhouse
3. DB::FunctionConvert<DB::DataTypeString, DB::NameToString, DB::ToStringMonotonicity>::executeInternal(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0xcfebc13 in /usr/bin/clickhouse
4. DB::FunctionConvert<DB::DataTypeString, DB::NameToString, DB::ToStringMonotonicity>::executeImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0xcfeb11c in /usr/bin/clickhouse
5. DB::IFunction::executeImplDryRun(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0xcd2960a in /usr/bin/clickhouse
6. DB::FunctionToExecutableFunctionAdaptor::executeDryRunImpl(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long) const @ 0xcd284ce in /usr/bin/clickhouse
7. DB::IExecutableFunction::executeWithoutLowCardinalityColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x12e2a165 in /usr/bin/clickhouse
8. DB::IExecutableFunction::executeWithoutSparseColumns(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x12e2a7a8 in /usr/bin/clickhouse
9. DB::IExecutableFunction::execute(std::__1::vector<DB::ColumnWithTypeAndName, std::__1::allocator<DB::ColumnWithTypeAndName> > const&, std::__1::shared_ptr<DB::IDataType const> const&, unsigned long, bool) const @ 0x12e2b8af in /usr/bin/clickhouse
10. DB::ActionsDAG::updateHeader(DB::Block) const @ 0x1341bac1 in /usr/bin/clickhouse
11. DB::ExpressionStep::ExpressionStep(DB::DataStream const&, std::__1::shared_ptr<DB::ActionsDAG>) @ 0x14acc4e3 in /usr/bin/clickhouse
12. DB::InterpreterSelectQuery::executeExpression(DB::QueryPlan&, std::__1::shared_ptr<DB::ActionsDAG> const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) @ 0x13a7ad4a in /usr/bin/clickhouse
13. DB::InterpreterSelectQuery::executeImpl(DB::QueryPlan&, std::__1::optional<DB::Pipe>) @ 0x13a71c95 in /usr/bin/clickhouse
14. DB::InterpreterSelectQuery::buildQueryPlan(DB::QueryPlan&) @ 0x13a6ff90 in /usr/bin/clickhouse
15. DB::InterpreterSelectWithUnionQuery::buildQueryPlan(DB::QueryPlan&) @ 0x13abfc03 in /usr/bin/clickhouse
16. DB::IInterpreterUnionOrSelectQuery::buildQueryPipeline() @ 0x13a50d53 in /usr/bin/clickhouse
17. DB::InterpreterInsertQuery::execute() @ 0x13a4c449 in /usr/bin/clickhouse
18. ? @ 0x13d1434c in /usr/bin/clickhouse
19. DB::executeQuery(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::shared_ptr<DB::Context>, bool, DB::QueryProcessingStage::Enum) @ 0x13d11e55 in /usr/bin/clickhouse
20. DB::TCPHandler::runImpl() @ 0x147f050f in /usr/bin/clickhouse
21. DB::TCPHandler::run() @ 0x14804259 in /usr/bin/clickhouse
22. Poco::Net::TCPServerConnection::start() @ 0x1745e52f in /usr/bin/clickhouse
23. Poco::Net::TCPServerDispatcher::run() @ 0x17460981 in /usr/bin/clickhouse
24. Poco::PooledThread::run() @ 0x17611609 in /usr/bin/clickhouse
25. Poco::ThreadImpl::runnableEntry(void*) @ 0x1760ed00 in /usr/bin/clickhouse
26. start_thread @ 0x76db in /lib/x86_64-linux-gnu/libpthread-2.27.so
27. clone @ 0x12161f in /lib/x86_64-linux-gnu/libc-2.27.so
`
The log on other pods is maybe simpler to read:
`2022-07-21 09:05:06,841 Attempting to connect to Clickhouse cluster dev-datawarehouse-kaj01.linguee.internal:9000 (attempt 0)
2022-07-21 09:05:06,847 Connecting. Database: sentrydev. User: default
2022-07-21 09:05:06,847 Connecting to dev-datawarehouse-kaj01.linguee.internal:9000
2022-07-21 09:05:06,945 Connected to ClickHouse server version 22.1.3, revision: 54455
2022-07-21 09:05:06,945 Query: SELECT version()
2022-07-21 09:05:06,946 Block "" send time: 0.000042
2022-07-21 09:05:07,047 Query: SELECT group, migration_id, status FROM migrations_local FINAL WHERE group IN ('system', 'events', 'transactions', 'discover', 'outcomes', 'metrics', 'sessions', 'generic_metrics')
2022-07-21 09:05:07,047 Block "" send time: 0.000040
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/migrations.py", line 64, in migrate
    runner.run_all(force=force)
  File "/usr/src/snuba/snuba/migrations/runner.py", line 145, in run_all
    pending_migrations = self._get_pending_migrations()
  File "/usr/src/snuba/snuba/migrations/runner.py", line 297, in _get_pending_migrations
    raise MigrationInProgress(str(migration_key))
snuba.migrations.errors.MigrationInProgress: events: 0014_backfill_errors`

I tried force reversing the migration the running it again but I always come to the same error.
On clickhouse side I checked the created tables and they're all empty except for the table `migrations_local`:
<img width="841" alt="image" src="https://user-images.githubusercontent.com/28063982/180177074-59b4f14e-90ea-41b4-937d-e396e5c0ef69.png">

@fpacifici said in a similar issue that this could bew caused by having "a very old definition of the `sentry_local` table" but I'm not sure how to tacle that..

**Comment by cortopy** [comment]
same here but version `21.8.15.7` of clickhouse seems to work
