### ISSUE TITLE
Operation cannot be fulfilled on resourcequotas

### ISSUE THREAD

**Issue by boskiv** [sentry-kubernetes/charts#69]
When I did
```
➜  ~ helm install sentry/sentry --generate-name
```
I've got
```
Error: Operation cannot be fulfilled on resourcequotas "iskiridomov": the object has been modified; please apply your changes to the latest version and try again
```
Any help?

**Comment by DandyDeveloper** [comment]
I don't think this is related to Sentry specifically, considering this is an install. I'd check to make sure there aren't any pending updates or something trying to apply to your API Server that may potentially be impacting your cluster as a whole. 

Maybe double check that no prior installs or Sentry are present in the `default` namespace.

**Comment by boskiv** [comment]
I have very strict installation. I have only my namespace availible to use.

**Comment by Mokto** [comment]
Yes, It means you haven't respected the resource quotas on your namespace. 
Either ask for more to your cluster administrator, or decrease the resources from this charts (but init jobs might fail).

**Comment by Mokto** [comment]
I'll close it. Let me know if anything else.
