### ISSUE TITLE
Chart version not immutable

### ISSUE THREAD

**Issue by 0x0013** [sentry-kubernetes/charts#697]
Hi,

I noticed when installing the sentry chart with a pinned version, it can include changes which were not present at the time of said version release.

For example, the chart version v15.0.0, released on 2022-07-05, deployed in a278e23add99712e0564a3299a93701fdc72dded, does not include [configmap-memcached](https://github.com/sentry-kubernetes/charts/blob/develop/sentry/templates/configmap-memcached.yaml) but installing the same pinned version chart after 2022-07-18, it includes the bugfix with memcached, thus the chart creates said configmap-memcached. It seems the chart with the same version is overwritten in ccb054ce17e697fc5b587ef3452e5b0366ebe752.

I can see similar examples of this behavior for other versions as well. Is this on purpose, or a bug in chart deployment pipeline? AFAIK each new change or bugfix should have a new tag, and the already created tags should be immutable.

**Comment by Mokto** [comment]
Thanks !

That's a bug, I had previously implemented something that would never overwrite an existing chart version.
At that time, it was fine merging code without bumping the version, but it's clearly obviously a major issue now.

I'll make sure it's not the case anymore.
