### ISSUE TITLE
Could I reset clickhouse and swipe all the data? If so, how?

### ISSUE THREAD

**Issue by rayw000** [sentry-kubernetes/charts#707]
I installed this chart with Helm on Kubernetes.

**Chart Version: sentry-13.1.0**
**App Version: 21.8.0**

My ClickHouse statefulset has 3 replicas.

Since there was something wrong with my GlusterFS, I manually stopped the `clickhouse-0` pod and deleted its volume and recreated a volume for it.

Now pods `sessions-consumer`, `snuba-consumer`, `snuba-outcomes` and `snuba-transactions-consumer` are complaining about
```
Received from sentry-clickhouse-0.sentry-clickhouse-headless.sentry.svc.cluster.local:9000. DB::Exception: Table default.transactions_local doesn't exist.
```

This sentry instance is installed for test, so **I don't really care about the data stored in ClickHouse, but I want to keep the data stored in PostgreSQL.** Is it possible to just re-initialize ClickHouse? How could I do it?

Thanks!

**Comment by eugenberend** [comment]
@rayw000 Yes it is possible,
Just `kubectl exec` into `snuba-api` pod and run `snuba migrations migrate --force`
All clickhouse tables will be re-created
