### ISSUE TITLE
wrong value for external postgres password

### ISSUE THREAD

**Issue by echel0n** [sentry-kubernetes/charts#715]
https://github.com/sentry-kubernetes/charts/blob/412841202e136f64266139132ebc96037a43d9ca/sentry/templates/cronjob-sentry-cleanup.yaml#L83

shouldn't this be `sentry.externalPostgresql.password` instead?

**Comment by Mokto** [comment]
This is the case already: https://github.com/sentry-kubernetes/charts/blob/develop/sentry/templates/_helper.tpl#L241

**Comment by echel0n** [comment]
ah, thanks!
