### ISSUE TITLE
sentry-web is getting stuck in pending state after update if using PVC with ReadWriteOnce

### ISSUE THREAD

**Issue by sagor999** [sentry-kubernetes/charts#77]
if `filestore` is configured with PVC with access mode `ReadWriteOnce` then during update sentry-web will be stuck in pending state, as by default it will attempt to perform rolling update. It will create new instance of sentry-web, while old one is running, and new instance will never get to running state, as it will not be able to mount PVC while old instance is still running.

Fix for this is simple:
Add following to `deployment-sentry-web.yaml`:
```
  strategy:
    type: Recreate
```
That will enforce shut down of old sentry-web before creating a newer instance of sentry-web.
Possibly might be worth adding it only if `filestore.filesystem.persistence.accessMode` is set to `ReadWriteOnce`.

**Comment by DandyDeveloper** [comment]
@sagor999 Sorry you haven't had a response on this. 

I've experienced this too and I'm trying to work out a good way to deal with this. The current logic in Sentry web isn't sensible as it won't allow scaling up through replicas due to the persistence options and it being a deployment. 

The best / obvious thing here is to just move it to a statefulset as it will be managing state in it's filestore, then just have the PVC managed within the statefulset itself without the need for a dedicated claim. 

It's on my radar.

**Comment by tombh** [comment]
Does this mean that we can't scale `sentry-web`? What is stored on the PVC? Is it possible to run `sentry-web` without a PVC?

**Comment by Mokto** [comment]
Sorry for the late response. On the PVC are stored the release artefacts you upload, for example.

I think it should be possible, but haven't tried, to be honest.

**Comment by J0sh0nat0r** [comment]
@tombh Yes, configuring an alternative filestore will remove the PVC requirement. For example S3:
```Yaml
filestore:
  backend: s3
  filesystem:
    persistence:
      enabled: false
  s3:
    accessKey: 
    secretKey: 
    bucketName: 
    endpointUrl: 
    default_acl: private
```

**Comment by Mokto** [comment]
I think @tombh was talking about no filestore at all.

For more infos you can also check this page : https://develop.sentry.dev/services/filestore/

**Comment by sagor999** [comment]
@J0sh0nat0r do you know what will happen if I reconfigure existing sentry-web from PVC to using S3? I assume it will lose existing data that it has on PVC? And what type of data does it store there, do you know?
thank you!

**Comment by J0sh0nat0r** [comment]
@sagor999 Yes the existing data would be lost, although it should be possible to manually upload existing data to S3 according to [this](https://forum.sentry.io/t/migration-of-files-from-filesystem-to-s3/5208) forum post. I'm afraid I'm not really sure what's stored on there beyond what Mokto mentioned though

@Mokto Maybe we should optionally deploy minio (maybe even by default?) to allow scaling?

**Comment by sagor999** [comment]
Is S3 fully supported? 
```
  ## Currently unconfigured and changing this has no impact on the template configuration.
  s3: {}
  #  accessKey:
  #  secretKey:
  #  bucketName:
  #  endpointUrl:
  #  signature_version:
  #  region_name:
  #  default_acl:
```
Also in code I see it only checks if backend is filesystem or gsc, but no checks and code for s3. 
I assume it is not implemented? I wonder if anyone has it already working and maybe there is a pull request for that already?

**Comment by sagor999** [comment]
nvm. Seems like that comment is out of date, and `gsc` is checked in code everywhere due to the way gsc auth is done. 
I switched it over to s3 and it seems to be working fine now.
Closing this issue.

**Comment by james64** [comment]
Hey! Filestore is valid storage option and not everyone can re-solve this issue by migrating to different one. I am actually one of them now. For this reason I would like to see `deployment-sentry-web` to support chaning strategy. Let's have `RollingUpdate` as default but that way at least user can change it. Now that is not an option (maintaining a fork is not ideal here). What do you think?

**Comment by sagor999** [comment]
@Mokto I added PR that addresses this:
https://github.com/sentry-kubernetes/charts/pull/216
