### ISSUE TITLE
Attempting to update to latest sentry tag caused Internal errors for sentry

### ISSUE THREAD

**Issue by sagor999** [sentry-kubernetes/charts#78]
I attempted to use latest tags for sentry and snuba:
`getsentry/sentry:00ae12b89402f10158e36413d35a94d642b56082`
`getsentry/snuba:3b11c3b64901d91fbbd0622ca718bcb7d871dd4a`
But once rolled out, sentry became unusable, with every page giving internal error. 

`snuba-api`, `snuba-consumer` were logging this error:
`clickhouse_driver.errors.NetworkError: Code: 210. Cannot assign requested address (localhost:9000)`
I wonder if something changed with regards to how they expect clickhouse address to be provided? Since it shouldn't be using `localhost` to connect to clickhouse.

@J0sh0nat0r you mentioned previously that you are running using latest tags for sentry? Did you do anything differently on your end to make it work?

This is using chart version 1.3.1

**Comment by J0sh0nat0r** [comment]
@sagor999 The changes in my [fork](https://github.com/J0sh0nat0r/sentry-kubernetes-charts) fix this, notably the configuration for Snuba was changed to use the `CLUSTERS` array. I was hoping @Mokto could verify the latest tags are working for him before opening a PR as I'm relatively sure the changes won't be backward compatible

**Comment by Mokto** [comment]
I'll check tomorrow morning ;)

**Comment by Mokto** [comment]
Same issue here !
And I was supposed to check for the "No events found" issue, I can't even do that.

**Comment by J0sh0nat0r** [comment]
@Mokto Just to confirm, did you deploy using my fork? The latest Snuba tag isn't compatible with the config in the current Chart version.

**Comment by Mokto** [comment]
Nope, I thought you were going to create a PR that I could test. Sorry about the misunderstanding.

**Comment by J0sh0nat0r** [comment]
@Mokto No worries, my bad :) I'll go ahead and open a draft one

**Comment by sagor999** [comment]
@Mokto @J0sh0nat0r 
Hey guys. I updated to latest chart version. Everything works, except all of my old events are reporting: `Sorry, the events for this issue could not be found.`
Any new events that are coming after upgrade are working though.
Anyway to restore old events? And do you see same issue on your end by any chance?

I tried re-running hooks, but that did not help. Also none of them reported any errors and log for each looked fine.
snuba-consumer works fine. no errors.
Everything else also seems to be working fine. Cannot find any errors in logs.

**Comment by sagor999** [comment]
Sentry reports this internal error: `ChunkLoadError: Loading chunk 167 failed.`

**Comment by sagor999** [comment]
One more note: noticed that I think some events have changed their reported time.
For example, it was: 
`June 11 2020 05:35:05 PDT`
but now reported as:
`June 10 2020 21:35:05 PDT`

Maybe this is related to clickhouse timezone change? And that somehow it messed up old events?

**Comment by sagor999** [comment]
Sorry for spam. :)
db-init actually reporting this:
```
2020-06-11 23:57:34,012 Column '_start_date' exists in local ClickHouse but not in schema!
2020-06-11 23:57:34,012 Column '_finish_date' exists in local ClickHouse but not in schema!
```

**Comment by sagor999** [comment]
More info: 
I tried to set timezone for clickhouse back to original -> it restored timestamps on old events, but still getting `Sorry, the events for this issue could not be found.` :( 
So I think it most probably related to timezone change? But most probably it messed up data to the point where it might not be recoverable? 
Hopefully you guys can shed some light on this.

**Comment by J0sh0nat0r** [comment]
@sagor999 That sounds about right, unfortunately I didn't see this in prod as my timezone was previously set to UTC. It should be possible to run a query to update all timestamps created before the timezone change however.

**Comment by sagor999** [comment]
@J0sh0nat0r ah, I see. I am not very familiar with clickhouse. Do you know how can I run the query and what it would look like? Appreciate your help!

**Comment by J0sh0nat0r** [comment]
@sagor999 I'll fire up my local testing environment and experiment for a bit, watch this space :)

**Comment by J0sh0nat0r** [comment]
@sagor999 Unfortunately it looks like ClickHouse is unable to update key columns. However, it seems that after creating some events with Clickhouse in the `America/Los_Angeles` timezone and switching over to `UTC` the dates are stored correctly and the events are visible. Could something more subtle be the culprit here?

**Comment by sagor999** [comment]
@J0sh0nat0r thank you for looking into it!
When I updated timezone back to original `Asia/Shangai` my timestamps returned back to normal. So timezone definitely is messing something up. 

Looking some more. When I query the event that is missing, I see this in log for sentry-web:
```
02:07:32 [WARNING] sentry.eventstore.snuba.backend: eventstore.missing-snuba-event (event_id=u'9b7bf7e2de90486382d17fb6151b2261' project_id=40L)
02:07:32 [WARNING] django.request: Not Found: /api/0/projects/sentry/sample-project/events/9b7bf7e2de90486382d17fb6151b2261/ (status_code=404 request=<WSGIRequest: GET u'/api/0/projects/sentry/...
```

So I guess it cannot find that event in snuba backend... not sure why though. Since it does query it by id, so timezone shouldn't matter in theory at all. 
What backend does it refer though?

**Comment by J0sh0nat0r** [comment]
@sagor999 Ok, I was able to re-create the issue by using the `Asia/Shanghai` timezone, initially I had been using PDT as I assumed that was your Clickhouse TZ. After some research it seems that it is in-fact possible to rectify this! Firstly make sure ClickHouse is running in the `UTC` timezone then run the following query on each node / replica:
```SQL
INSERT INTO sentry_local
SELECT event_id,
       project_id,
       group_id,
       timestamp + INTERVAL 8 HOUR         AS timestamp,
       deleted,
       retention_days,
       platform,
       message,
       primary_hash,
       received + INTERVAL 8 HOUR          AS received,
       search_message,
       title,
       location,
       user_id,
       username,
       email,
       ip_address,
       geo_country_code,
       geo_region,
       geo_city,
       sdk_name,
       sdk_version,
       type,
       version,
       offset,
       partition,
       message_timestamp + INTERVAL 8 HOUR AS message_timestamp,
       os_build,
       os_kernel_version,
       device_name,
       device_brand,
       device_locale,
       device_uuid,
       device_model_id,
       device_arch,
       device_battery_level,
       device_orientation,
       device_simulator,
       device_online,
       device_charging,
       level,
       logger,
       server_name,
       transaction,
       environment,
       `sentry:release`,
       `sentry:dist`,
       `sentry:user`,
       site,
       url,
       app_device,
       device,
       device_family,
       runtime,
       runtime_name,
       browser,
       browser_name,
       os,
       os_name,
       os_rooted,
       `tags.key`,
       `tags.value`,
       _tags_flattened,
       `contexts.key`,
       `contexts.value`,
       http_method,
       http_referer,
       `exception_stacks.type`,
       `exception_stacks.value`,
       `exception_stacks.mechanism_type`,
       `exception_stacks.mechanism_handled`,
       `exception_frames.abs_path`,
       `exception_frames.filename`,
       `exception_frames.package`,
       `exception_frames.module`,
       `exception_frames.function`,
       `exception_frames.in_app`,
       `exception_frames.colno`,
       `exception_frames.lineno`,
       `exception_frames.stack_level`,
       culprit,
       sdk_integrations,
       `modules.name`,
       `modules.version`
FROM sentry_local
WHERE timestamp < toDateTime('REPLACE_ME') + INTERVAL 8 HOUR;
```
Replacing `REPLACE_ME` with the time Sentry was upgraded at in `UTC` (it should suffice to grab the timestamp from the first correctly received event after the upgrade and take a second off that)
in the following format `yyyy-mm-dd hh:mm:ss`

**Comment by sagor999** [comment]
@J0sh0nat0r thank you!!! It works now! All timestamps are correct and events are accessible now. Appreciate your help!

**Comment by J0sh0nat0r** [comment]
@sagor999 No worries, glad to hear it's all working! Happy to help :)

**Comment by Mokto** [comment]
Wow nice, thanks! I'll add upgrade notes to the readme.
