### ISSUE TITLE
Can`t finish db-check job

### ISSUE THREAD

**Issue by Chengshihao1018** [sentry-kubernetes/charts#783]
When i try deploy sentry from helm, i get this error
![rZLSyT4gL3](https://user-images.githubusercontent.com/31720199/201813058-7dada2cf-70fa-4a41-ad4b-5337d25aedc4.jpg)

however the kafka、zookeeper runs just fine
![image](https://user-images.githubusercontent.com/31720199/201813477-6582a185-d574-4909-ae0c-0593e15fb15e.png)
 
and the kafka can be pinged through
![image](https://user-images.githubusercontent.com/31720199/201814452-588c9632-33f9-42a4-8371-278827109c40.png)

There is something wrong in using nc in k8s？

**Comment by Chengshihao1018** [comment]
i have resloved

**Comment by matiosfree** [comment]
> i have resloved

Can you tell pls how you did that?

**Comment by matiosfree** [comment]
We found the issue. The thing is there were **istio** enabled. Because of that "post-install" hook was stuck and not all pods were run.
we had to add an annotation:
`sidecar.istio.io/inject: "false"`
