### ISSUE TITLE
Metrics Support

### ISSUE THREAD

**Issue by ts-mini** [sentry-kubernetes/charts#81]
From the previous chart there was support for statsd/prometheus via 

https://github.com/helm/charts/pull/14355

Is there any plans for this type of 'native' integration in this chart? a-la `metrics.enabled=true`?

**Comment by Mokto** [comment]
A good nice to have but it's not on top of my priorities to be honest !

PR welcomed.

**Comment by ts-mini** [comment]
Awesome! I'll see if I can find a few extra minutes to work on it - are there any guidelines/random things I have to sign to contribute in this repo (like old helm-charts/stable) - I don't see anything atm?
