### ISSUE TITLE
Add cleanup jobs with a CronJob

### ISSUE THREAD

**Issue by Mokto** [sentry-kubernetes/charts#84]
Should run:
- Sentry
- Snuba
- Symbolicator

**Comment by DandyDeveloper** [comment]
@Mokto I wonder if this could replace the cron pod entirely? I still don't fully understand what the cron pod does...

**Comment by Mokto** [comment]
The weekly report for example :

https://github.com/getsentry/sentry/blob/master/src/sentry/conf/server.py#L673

**Comment by jmijn** [comment]
Also missing a configuration option in the values to set the retention days. Now its set to 90 always:
https://github.com/sentry-kubernetes/charts/blob/develop/sentry/templates/configmap-sentry.yaml#L138

**Comment by hairmare** [comment]
👍 on getting rid of the cron pod entirely! I didn't take the time to figure out what it does but I'd totally agree that all of it should be achievable through proper K8s CronJobs.

**Comment by BYK** [comment]
The `cron` worker on Sentry would still be needed as it is actually celery-beat but other `-cleanup` images built from base images with Cron layered on top should be trivial to get rid of with k8s scheduled event runs. The reason we have them this way is `docker-compose` not having this functionality.

**Comment by Mokto** [comment]
Closing as 5.2.0 solves this issue.
