### ISSUE TITLE
Does sentry-web send email alerts?

### ISSUE THREAD

**Issue by hyunkj42** [sentry-kubernetes/charts#859]
Hello.

In the environment I use, the network of smtp server and sentry is blocked.

Therefore, in order to use email as an alarm reception method, network acl must be registered.

Are you sending emails from sentry-web?
Or worker?

If anyone knows, please reply.

**Comment by pavels** [comment]
Workers are responsible for sending emails

**Comment by hyunkj42** [comment]
There is a web pod and a worker pod, but it is the worker pod that sends mail, right?

**Comment by pavels** [comment]
Yes - worker pod sends emails

**Comment by hyunkj42** [comment]
@pavels 
thank you for confirmation. :)
Let's test it.

**Comment by hyunkj42** [comment]
For reference, the mailing of the user invitation is sent from the web pod.
