### ISSUE TITLE
Add sentry relay

### ISSUE THREAD

**Issue by Mokto** [sentry-kubernetes/charts#86]
https://github.com/getsentry/relay

**Comment by untitaker** [comment]
fwiw relay is configured in getsentry/onpremise. I would recommend following whatever we do there to get this service set up.

We're also getting bug reports about this helm chart as the store endpoint is gone in sentry master in favor of relay.

**Comment by Mokto** [comment]
Agreed ! Unfortunately I'm quite busy, so I can't do that right now

**Comment by mitchfriedman** [comment]
I'd be happy to contribute a PR of adding in relay support.

Since this is a breaking change architecturally in sentry, it's going to be breaking here as well (by pinning the latest images of sentry + relay that no longer play well with older versions).

**Comment by Mokto** [comment]
Hey! When do you plan on implementing that ?
I think because of [this issue](https://github.com/sentry-kubernetes/charts/issues/127), it is more and more a priority.

If you don't have time, I can have a look at it.

Thanks!

**Comment by mitchfriedman** [comment]
Hey, sorry I haven't had as much time as I was expecting - feel free to pick this up, not sure i'll be able to get around to it this week or next.

**Comment by Mokto** [comment]
Closed with 7ae3651
