### ISSUE TITLE
No events sent from local to fresh sentry installation on version 18.0.1

### ISSUE THREAD

**Issue by anshuman852** [sentry-kubernetes/charts#885]
Hi, i just setup a fresh sentry install using the helm chart and here is my helm release 
```apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sentry
  namespace: sentry
spec:
  chart:
    spec:
      chart: sentry
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: sentry
  targetNamespace: sentry
  interval: 1m0s
  values:
    service:
      name: sentry
      type: ClusterIP
      externalPort: 9000
      internalPort: 9000
    ingress:
      enabled: false
    nginx:
      enabled: false
```

I have disabled the ingress because , i directly point the sentry.example.com thru a cloudflare tunnel 
But then when i try to send events from my local using the python sdk and fastapi
i get 403 - CSRF Verification Failed, 

Thanks a lot in advance, any help is appreciated

**Comment by aidenpearce001** [comment]
Any update, cause i have same problem
