### ISSUE TITLE
Missing release 19

### ISSUE THREAD

**Issue by Glaaj** [sentry-kubernetes/charts#925]
I have renovatebot setup to check if there is a new release available, it shows that 19.4 is available:
![image](https://github.com/sentry-kubernetes/charts/assets/83582518/8e9b336b-f7d7-4073-9f98-42eb7683bd8f)

Why is there no "official" release of version 19 available in github?

**Comment by imw** [comment]
Wondering the same. Please let me know if I can help cut a release.

**Comment by Glaaj** [comment]
Well since this is out already: https://github.com/sentry-kubernetes/charts/releases/tag/20.0.0

I'll close this one 🥉
