### ISSUE TITLE
Adopting the incubator/sentry-kubernetes chart

### ISSUE THREAD

**Issue by hairmare** [sentry-kubernetes/charts#93]
Would you consider adopting the `incubator/sentry-kubernetes` chart into this repo?

* sentry-kubernetes logs kubernetes events to sentry: https://github.com/getsentry/sentry-kubernetes
* incubator chart: https://github.com/helm/charts/tree/master/incubator/sentry-kubernetes
* missing maintainers/helm v3 deprecation warning: https://github.com/getsentry/sentry-kubernetes/issues/23#issuecomment-588977946

**Comment by Mokto** [comment]
Hey!

Yes definitely, as an optional add-on.

Good idea.

**Comment by DandyDeveloper** [comment]
@Mokto Can you look into adding this: https://github.com/apps/auto-assign-issues

I've been very disconnected recently because I didn't realise we had activity haha. 

This looks good though, I'll be reviewing the changes in the PR as soon as I can.
