### ISSUE TITLE
Unable to fetch/view project details, after the upgrade.

### ISSUE THREAD

**Issue by prasadkris** [sentry-kubernetes/charts#946]
I have opened [issues/2312](https://github.com/getsentry/self-hosted/issues/2312) for this in the Sentry-hosted repo. However, based on the interactions there, it seems this issue could be related to the sentry-chart/snuba-migration. Therefore, I'm also creating the issue here for further discussion.

We got a sentry deployment on our self-hosted Kubernetes cluster (k8s version: v1.25.7) which was deployed using the Sentry-Kubernetes Helm chart, version 15.x.x, and it worked fine without any issues. I attempted an upgrade to a new version (23.6.1) by following the [suggested](https://github.com/sentry-kubernetes/charts) Helm chart upgrade path (15.x.x -> 16.x.x -> 17.x.x -> 18.x.x -> 19.5.1). The upgrade went smoothly without any issues.

However, after the upgrade, a few of our projects are having problems. When I go to the issues pages, I see an error screen with "unable to fetch project details" message as seen below, also I am unable to access the general settings page for these projects.

<img width="1100" alt="to share" src="https://github.com/sentry-kubernetes/charts/assets/97734766/74a6618d-fbe0-44e6-9361-2299fed010c7">

<img width="1204" alt="image2" src="https://github.com/sentry-kubernetes/charts/assets/97734766/c04a531d-92b1-47de-ad54-6fc54dc03c07">

This issue only exists in 2 of our 14 total projects we have in Sentry, The following exceptions are seen in the `sentry-web` and the `snuba-api` pod logs when I navigate to the "problematic"  projects:

```
QueryExecutionError)(
sentry.utils.snuba.QueryExecutionError: DB::Exception: Illegal column for DataTypeNullable
```

The `sentry-web` pod logs are available [here](https://gist.github.com/prasadkris/4bdd68a91dd455f9cb38bb6b624d2b80) and the `snuba-api` logs are available [here](https://gist.github.com/prasadkris/94a1830f23cca46a4929ab3925e7e024), The `values.yaml` file used for the deployment can be found [here](https://gist.github.com/prasadkris/7e420fa85163ac51e639640a400644c9), Any help on fixing would be much appreciated. Thanks!

**Comment by prasadkris** [comment]
I have investigated and tested the upgrades again by provisioning a brand new test setup and can confirm that this issue starts when we upgrade from version `17.x.x` of this chart to `18.x.x`. (sentry version 22.11.0 to 23.3.1)

The upgrade from `15.x.x to 16.x.x to 17.x.x` worked very well, but there seems to be a problem with the upgrade from `17.x.x to 18.x.x`. which results in the behavior and errors explained above.

Could this be due to some issues with the `snuba-migrate` job in the chart? I reviewed the pod logs of the `sentry-snuba-migrate` and `sentry-snuba-db-init` jobs, but they didn't provide any pointers. The logs are available [here](https://gist.github.com/prasadkris/59f4b1d02ac837e1b266633e0eb9f538) for your reference. 

This issue can be easily reproduced by attempting to upgrade from version 17.x.x of this chart to 18.x.x (my test was from version 17.11.3 to 18.0.1). After the upgrade, navigate to the issues in the default `Internal` project, you'll see a message stating `Unable to fetch project details`. Trying to navigate to `Settings -> Projects -> Internal` will result in the display of an `Oops, something went wrong` message, accompanied by a spinning wheel at the top, as shown in my initial screenshot images. Inspect the logs from the `sentry-web` and `snuba-api`, we will see errors/exceptions.

```
QueryExecutionError)(
sentry.utils.snuba.QueryExecutionError: DB::Exception: Illegal column for DataTypeNullable
```
complete stacktrace/log can be found [here](https://gist.github.com/prasadkris/c22a06b7fd70d5f45cdb1c8854f2614a).

Any pointers on fixing this would be greatly appreciated. Please let me know if you need any further details. Thanks! 🙏

**Comment by ntcong** [comment]
> Illegal column for DataTypeNullable

I think this is probably some clickhouse version problem.

**Comment by prasadkris** [comment]
Thank you, @ntcong 🙏🏻 We were using clickhouse version `v20.8.19.4`, and I have updated it to `20.12.8.5`. This update indeed helped to fix the issue. 🎉
