### ISSUE TITLE
Unable to enable tabix ingress.

### ISSUE THREAD

**Issue by pravk** [sentry-kubernetes/charts#97]
I am getting the following error while trying to enable tabix ingress using values.yaml file.

```Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(Ingress.spec.rules): invalid type for io.k8s.api.extensions.v1beta1.IngressSpec.rules: got "map", expected "array"```

The template file ```https://github.com/sentry-kubernetes/charts/blob/develop/clickhouse/templates/ingress-clickhouse.yaml``` seems to be the issue. spec/rules should be array instead of a map.

**Comment by Mokto** [comment]
Thanks for the report ! 
Fixed in #99

**Comment by Mokto** [comment]
Should be fixed in in 3.0.1 ;)
