### ISSUE TITLE
Fresh install: Hard stop

### ISSUE THREAD

**Issue by cabrinha** [sentry-kubernetes/charts#972]
DB Init job fails with "hard stop" on fresh install of latest version: `Error: It looks like you've skipped a hard stop in our upgrade process. Please follow the upgrade process here: https://develop.sentry.dev/self-hosted/releases/#hard-stops`

**Comment by sschamp** [comment]
We're gonna need some more info here I think.
I did a fresh install with:
Chart Version 20.4.0
App Version 23.7.2

And all installed just fine, except for Kraft, install failed when I tried to enable it on fresh install, so going to use Zookeeper.


Are you sure it's a fresh install?
Did you create a new namespace for Sentry and fully delete the namespace before trying again?
Also check for lingering Persistent Volumes.

**Comment by cabrinha** [comment]
App version: 23.7.2
Chart version: 20.4.0

No previous deployment was present.

**Comment by geckiss** [comment]
How did you solve this issue?

**Comment by garvit-jain-pw** [comment]
To fix this run in your postgres database

`CREATE EXTENSION citext;`
