### ISSUE TITLE
missed_checkins after 23.7.2 update

### ISSUE THREAD

**Issue by zetaab** [sentry-kubernetes/charts#973]
we updated our sentry from 23.6.1 to 23.7.2 version and after that some of the cron monitors stopped working. I can see from logs that celery tasks are executed fine, but for some reason the cron monitors are failing.

<img width="2204" alt="Screenshot 2023-08-22 at 14 27 52" src="https://github.com/sentry-kubernetes/charts/assets/22482503/b959d05e-70ee-4f0e-80d2-460d82015c0d">
<img width="1492" alt="Screenshot 2023-08-22 at 14 30 17" src="https://github.com/sentry-kubernetes/charts/assets/22482503/a617bdff-f4b9-4630-8c4e-79c54906e302">

How to fix these failing monitors?

**Comment by zetaab** [comment]
Also transactions were somehow "stuck". I restarted all pods but still, transactions were not visible in performance page.

I rolled back to --version 20.0.0 chart (23.6.1) and now I can see that transactions are flowing in again. Something is broken in newer release

**Comment by stevenyongzion** [comment]
Getting the same issues on 23.7.2, not too sure if this is serious. I have to temporarily disable the crons for now and unsure the impacts.

**Comment by zetaab** [comment]
@stevenyongzion at least for us it was critical, for instance performance section stopped working.

**Comment by emoyly** [comment]
I am also experiencing this (at least I think it is the same) on v23.6.1
![chrome_qyDK3fsJu6](https://github.com/sentry-kubernetes/charts/assets/24597604/fffe45a2-0672-4262-8b66-0301ae094770)

**Comment by stevenyongzion** [comment]
Yeah then it seems to have started since v23.6.1 instead of earlier suspected version Sentry v23.7.2. 

I have stopped moving forward using newer version now until this is fixed or will there someone even know how to fix. While we are not using Performance feature which these errors are impacting, it does not look a very good sign to move onto these version.

**Comment by stevenyongzion** [comment]
Hmmm, we tried setting up from scratch using latest 23.8.0, all good, no more missing_checkins errors.

Weird, looks like a migration problem.

**Comment by adonskoy** [comment]
FYI: crons are automatically added by sentry-sdk. When they become useless whey won't be deleted automatically. 

Remove such crons from the sentry, restart the cron and worker deployments. If none of the deleted jobs are added again, then they are no longer needed

**Comment by stevenyongzion** [comment]
This is now resolved for me. Turn out in the newer version of Sentry, some old crons are not used anymore.

Delete the invalid crons, restart all pods, even the error `Excepton in check_monitors - backlog 62 is > 0` is gone now.

**Comment by Mokto** [comment]
Thanks! I'll then close the issue.
