### ISSUE TITLE
Kubernetes 1.16 support

### ISSUE THREAD

**Issue by voslartomas** [sentry-kubernetes/charts#98]
Hello just upgraded to 1.16 kubernetes version and I got stuck with sentry helm

```
Error: unable to build kubernetes objects from current release manifest: unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"
```

I guess statefulSet in apps/v1beta2 is deprecated and apps/v1 should be used instead, any chance of fix?

https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

**Comment by Mokto** [comment]
Are you sure it's coming from this chart ?
I've been using Kubernetes 1.16 for a while now, without any issue.

I'm not using the internal redis/rabbitmq/postgres but I checked the inside and everything is using apps/v1

**Comment by voslartomas** [comment]
It seems like something from this helm chart

```
helm_release.sentry: Modifying... [id=sentry]
helm_release.sentry: Still modifying... [id=sentry, 10s elapsed]
helm_release.sentry: Still modifying... [id=sentry, 20s elapsed]
helm_release.sentry: Still modifying... [id=sentry, 30s elapsed]

Error: unable to build kubernetes objects from current release manifest: unable to recognize "": no matches for kind "StatefulSet" in version "apps/v1beta2"

  on main.tf line 96, in resource "helm_release" "sentry":
  96: resource "helm_release" "sentry" {
```

If I change some configuration in other charts, it works well. I was trying to change config for sentry and this happens when I update via terraform. Not sure how to get more info? Also I am using redis, rabbitmq and postgres from this chart.

**Comment by kimxogus** [comment]
This error can be occurred when your pre-deployed chart has deprecated version, not only new version.
You need to re-enable deprecated api versions using `runtimeConfig` and retry it, then you can disable them.

**Comment by voslartomas** [comment]
@kimxogus thanks that helped.
